<?php

$language_words = array(
  'values' => array(
    'null', 'false', 'true',
  ),
  'blocks' => array(
    'include', 'while', 'return', 'if', 'else'
  ),
  'types' => array(
    'const', 'fixed', 'void', 
    'int', 'bool', 
    'playergroup', 'trigger', 'string', 'color', 'text', 'unit', 'unitgroup', 'point', 'region', 
    'camerainfo', 'order', 'abilcmd', 'timer', 'soundlink', 'transmissionsource', 'unitfilter', 
    'actor', 'actorscope', 'wave', 'marker', 
  ),
  'natives' => array(
      'IntToFixed', 'IntToString', 'FixedToInt', 'FixedToString', 'StringToInt', 'StringToFixed', 'StringLength',
      'StringCase', 'StringSub', 'StringEqual', 'StringContains', 'SquareRoot', 'Pow', 'ModF', 'Sin', 'Cos',
      'Tan', 'ASin', 'ACos', 'ATan', 'ATan2', 'Point', 'PointWithOffset', 'PointGetX', 'PointGetY',
      'AngleBetweenPoints', 'DistanceBetweenPoints', 'RegionEmpty', 'RegionRect', 'RegionCircle',
      'RegionAddRect', 'RegionAddCircle', 'RegionAddRegion', 'RegionSetCenter', 'RegionContainsPoint',
      'RegionGetBoundsMin', 'RegionGetBoundsMax', 'RegionGetCenter', 'ColorGetComponent',
      'TriggerAddEventUnitRegion', 'TimerStart', 'TimerRestart', 'TimerPause', 'TimerGetElapsed',
      'TimerGetRemaining', 'TimerGetDuration', 'TriggerAddEventTimer', 'PlayerGetPropertyInt', 'EventPlayer',
      'PlayerGroupEmpty', 'PlayerGroupSingle', 'PlayerGroupClear', 'PlayerGroupCount', 'PlayerGroupHasPlayer',
      'OrderGetTargetPoint', 'OrderGetTargetUnit', 'UnitLastCreated', 'UnitKill', 'UnitRemove', 'UnitGetType',
      'UnitGetOwner', 'UnitSetOwner', 'UnitGetPosition', 'UnitGetFacing', 'UnitSetFacing',
      'UnitSetPropertyFixed', 'UnitIssueOrder', 'TriggerAddEventUnitDied', 'EventUnit', 'EventUnitRegion',
      'Return', 'EventUnitDamageAmount', 'EventUnitDamageSourceUnit', 'EventUnitDamageSourcePlayer',
      'EventUnitDamageSourcePoint', 'EventUnitOrder', 'UnitGroupEmpty', 'UnitGroupClear', 'UnitGroupIssueOrder',
      'UnitGroupHasUnit', 'TriggerEnable', 'TriggerIsEnabled', 'TriggerGetEvalCount', 'TriggerGetExecCount',
      'TriggerEvaluate', 'TriggerExecute', 'TriggerDebugWindowOpen', 'TriggerDebugOutput',
      'TriggerAddEventMapInit', 'TriggerAddEventChatMessage', 'EventChatMessage', 'customscriptaction',
      'ArithmeticIntMult', 'ArithmeticRealMult', 'ArithmeticInt', 'ArithmeticReal', 'CombineStringsMult',
      'CombineStrings', 'And', 'Or', 'AndOrMult', 'AndOr', 'SetVariable', 'IfThenElse', 'SkipRemaining',
      'ConsoleCommand', 'UnitLastCreatedGroup', 'MeleeInitResourcesForPlayer', 'MeleeInitResources',
      'MeleeInitUnitsForPlayer', 'MeleeInitUnits', 'MeleeSetOption', 'MeleeGetOption', 'MeleeInitOptions',
      'UnitMoverExists', 'MeleeInitAI', 'PlayerStartLocation', 'UnitAbilityEnable', 'UnitAbilityExists',
      'UnitAbilityCheck', 'PlayerRace', 'TechTreeUpgradeAddLevel', 'VisEnable', 'VisIsEnabled',
      'VisRevealerCreate', 'VisRevealerLastCreated', 'VisRevealerDestroy', 'VisRevealerEnable',
      'VisRevealerUpdate', 'TechTreeBehaviorAllow', 'TechTreeBehaviorIsAllowed', 'UnitSelect',
      'UnitClearSelection', 'UnitIsSelected', 'UnitGroupSelect', 'UnitGroupSelected', 'SoundStop',
      'SoundSetVolume', 'SoundSetPosition', 'Color', 'ColorWithAlpha', 'UnitTestState', 'PlayerGroupAll',
      'TimerCreate', 'TimerIsPaused', 'RandomInt', 'RandomFixed', 'GameOver', 'MinimapPing', 'CameraInfoDefault',
      'CameraInfoSetValue', 'CameraInfoGetValue', 'CameraInfoSetTarget', 'CameraInfoGetTarget',
      'TriggerAddEventUnitCargo', 'EventUnitCargo', 'UnitMagazineCount', 'UnitGroupCopy', 'UnitGroupUnit',
      'PlayerGroupCopy', 'PlayerGroupPlayer', 'UnitIsAlive', 'TriggerGetCurrent', 'TriggerAddEventUnitSelected',
      'TechTreeRequirementsEnable', 'UnitSetScale', 'UnitCargo', 'UnitCargoGroup', 'PlayerSetAlliance',
      'PlayerGetAlliance', 'PointWithOffsetPolar', 'Wait', 'EventUnitDamageDeathCheck', 'CreepAdjacent',
      'CreepIsPresent', 'PowerLevel', 'PowerIsProvidedBy', 'TechTreeAbilityCount', 'TechTreeBehaviorCount',
      'TechTreeUnitCount', 'TechTreeUpgradeCount', 'UnitBehaviorTransfer', 'UnitTechTreeBehaviorCount',
      'UnitTechTreeUnitCount', 'UnitTechTreeUpgradeCount', 'AIWaveCreate', 'AIWaveInfoCreate', 'AIWaveAddUnit',
      'AIWaveTargetUnitPoint', 'AIWaveTargetUnit', 'TriggeringProgressEffect', 'TriggeringProgressUpgrade',
      'TriggeringProgressUnitType', 'TriggerAddEventUnitHighlight', 'TriggerAddEventUnitClick',
      'BankLastCreated', 'BankExists', 'BankName', 'BankSectionCount', 'BankSectionName', 'BankKeyCount',
      'BankKeyName', 'BankSectionExists', 'BankKeyExists', 'BankValueIsType', 'BankLoad', 'BankRemove',
      'BankSave', 'BankSectionRemove', 'BankKeyRemove', 'BankValueSetFromFixed', 'BankValueSetFromFlag',
      'BankValueSetFromInt', 'BankValueSetFromString', 'BankValueSetFromUnit', 'BankValueGetAsFixed',
      'BankValueGetAsFlag', 'BankValueGetAsInt', 'BankValueGetAsString', 'BankValueGetAsUnit',
      'EventUnitAbilityStage', 'EventUnitTargetPoint', 'EventUnitTargetUnit', 'EventUnitAbility', 'AIStart',
      'CameraLockInput', 'ForEachUnitInGroup', 'OrderGetPlayer', 'UnitTestPlane', 'GameSetNextMap',
      'TriggerQueueIsEmpty', 'OrderGetFlag', 'Repeat', 'UnitLevel', 'EventUnitXPDelta', 'UnitXPTotal',
      'EventUnitBehavior', 'RegionEntireMap', 'UnitFilterSetState', 'UnitFilterGetState', 'UnitGroup',
      'CameraUseModel', 'AIWaveTargetPlayer', 'AIWaveInfoSuicide', 'CatalogEntryCount', 'CatalogEntryGet',
      'CatalogEntryParent', 'CatalogEntryScope', 'CatalogFieldCount', 'CatalogFieldGet', 'CatalogFieldValueGet',
      'UnitAbilityCount', 'UnitAbilityGet', 'UnitBehaviorCount', 'UnitBehaviorGet', 'UnitPauseAll',
      'UnitXPGainEnable', 'GameTimeOfDaySet', 'GameTimeOfDayPause', 'GameTimeOfDayGet', 'GameTimeOfDayIsPaused',
      'UnitQueueItemCount', 'UnitQueueItemTypeCheck', 'PlayerSetState', 'SoundWait', 'TriggerSkippableBegin',
      'PlayerGetState', 'EventUnitProgressUnit', 'UIUnitColorStyleOverride', 'UIUnitColorStyleClearOverride',
      'ConversationDestroy', 'ConversationReplyCreate', 'ConversationReplyDestroy', 'ConversationVisible',
      'ConversationLastCreated', 'ConversationReplyLastCreated', 'TriggerAddEventConversationReplySelected',
      'ObjectiveLastCreated', 'ObjectiveDestroy', 'ObjectiveSetName', 'ObjectiveSetDescription',
      'ObjectiveSetState', 'BoardLastCreated', 'BoardDestroy', 'BoardShowAll', 'BoardSetName', 'BoardSetState',
      'BoardSetColumnCount', 'BoardSetRowCount', 'BoardSetColumnWidth', 'BoardSetGroupCount', 'BoardRowSetGroup',
      'BoardItemSetText', 'BoardItemSetTextColor', 'BoardItemSetBackgroundColor', 'BoardItemSetIcon',
      'BoardItemSetAlignment', 'BoardItemSetSortValue', 'BoardSort', 'BoardSetPlayerColumn', 'BoardPlayerAdd',
      'EventConversation', 'EventConversationReply', 'TimerWindowLastCreated', 'TimerWindowDestroy',
      'TimerWindowShow', 'TimerWindowSetTimer', 'TimerWindowSetTitle', 'TimerWindowSetFormat',
      'TimerWindowSetColor', 'TextTagLastCreated', 'TextTagSetPosition', 'TextTagAttachToUnit',
      'TextTagSetVelocity', 'TextTagShow', 'TextTagPause', 'TextTagSetColor', 'TextTagSetTime',
      'cai_wave_enable', 'UISetChallengeHighScore', 'PathGetSourcePoint', 'SetWalkAnimMoveSpeed',
      'UnitIsVisibleToPlayer', 'TriggerAddEventUnitReviveProgress', 'UnitGroupAlliance', 'DialogSetPosition',
      'AIGetMinPeonCount', 'DialogControlGetPropertyAsControl', 'cai_startall', 'DialogItemMaximumValue',
      'AIWaveEval', 'UnitQueueItemTime', 'TimerWindowSetPosition', 'MercenarySetScenePath', 'AbsI',
      'ActorCreate', 'CatalogLinkReplacement', 'VictoryPanelSetMissionTitle', 'PingSetTooltip',
      'WaitForConditionWithMaximumDuration', 'ConversationDataRun', 'AICombatDiffFlagCatSplashHighPrio',
      'AnimSetTime', 'ConversationDataLineCount', 'PingGetPlayerGroup', 'UnitSetInfoText', 'CatalogReferenceSet',
      'UISetResourceVisible', 'MakeUnitUncommandable', 'SetAnimationTime', 'EventMouseMovedPosYWorld',
      'ResearchItemIsRecentlyPurchased', 'DialogControlGetSelectedItem', 'ActorSend', 'UIDisplayMessage',
      'PlanetSetMissionTitle', 'AIDefaultGetFirstUnfinishedReq', 'CatalogFieldValueSet', 'UnitLoadModel',
      'MakeMsgTextureVideoPlay', 'PlanetPanelSetBackgroundImage', 'ActorSendToAsText',
      'ConversationDataStateName', 'AISetAPM', 'EventPlayerPropertyChangeFixed', 'HelpPanelDisplayPage',
      'DialogClearSubtitlePositionOverride', 'GameSetMissionTimePaused', 'KillModel', 'PingDestroyAll',
      'TriggeringProgressAbility', 'UnitGroupWaitUntilIdle', 'EventUnitCreatedBehavior',
      'ActorScopeFromPortrait', 'ConversationDataChoiceSetPicked', 'TriggerAddEventBattleReportPanelExit',
      'FlashScreenButton', 'OrderTargetingRelativePoint', 'AISetUnitTacticalDisabled', 'DataTableGetActor',
      'AIIsTownHarvestRunning', 'CampaignProgressSetCampaignFinished', 'PathDestroy',
      'TransmissionSourceSetPauseAllowed', 'UnitGetPropertyResources', 'AISetFilterAlliance',
      'DataTableSetConversation', 'TechTreeRestrictionsEnabled', 'UIHideCinematicText',
      'ConversationDataStateImageEdge', 'UnitControlGroupAddUnits', 'ResearchTierLastCreated',
      'UISetCommandAllowed', 'DialogGetRelativeAnchor', 'ActorScopeOrphan', '_StoreGameUIVisibleStates',
      'QueryPersistent', 'UnitInventoryLastCreated', 'DataTableGetBank', 'AICombatDiffFlagTieBreakInjured',
      'ScreenImageDialogItem', 'MoverSetAcceleration', 'UnitSetVariation', 'PathSetLineTexture',
      'VictoryPanelSetPlanetModelLink', 'PortraitSetTintColor', 'UserDataInstance',
      'AICombatDiffFlagTieBreakDetector', 'ShowHidePlacementModels', 'SetPlayerGroupAlliance',
      'SoundStopAllModelSounds', 'SendActorMessageToGameRegionWithFilters', 'UserDataLoadType',
      'UserDataGetImagePath', 'DataTableSetPortrait', 'CreateDialogItemButton', 'ConversationDataWasSkipped',
      'UnitBehaviorRemove', 'UnitBehaviorDuration', 'AIWaveTargetRegion', 'MakeMsgTransition',
      'DataTableSetPlayerGroup', 'ObjectiveDestroyAll', 'UnitBehaviorSetDurationRemaining',
      'BoardItemSetProgressColor', 'DialogControlInvokeAsString', 'AITransportSetPanic', 'TextureVideoStop',
      'ConvertPresetToPurchasable', 'MovieStopRecording', 'TechTreeUpgradeAllow', 'AnimBaselineStop',
      'PlayerInCinematicMode', 'TextTagAttachToUnitPoint', 'ConversationDataActiveCamera',
      'HideAllCinematicPortraits', 'EngineReset', 'UserDataSetInt', 'BankVerify', 'UnitCargoCreate',
      'FogSetDensity', 'TriggerAddEventUnitSpecializeProgress', 'MoverSetSpeed', 'ConversationDestroyAll',
      'ObjectiveSetPlayerGroup', 'DataTableGetPlanet', 'WaitForCutsceneToEnd', 'AIGetGatherDefLocation',
      'ObjectiveCreateForPlayers', 'ForEachUIFrame', 'AIGetFullMakeTime', 'UnitGroupIsDead',
      'ConversationDataStateIndexCount', 'TechTreeUnitHelpDefault', 'UnitIsInsideTransport',
      'UnitAbilityGetLevel', 'TriggerAddEventBattleReportPanelPlayMission', 'PurchaseItemSetSlot',
      'ConvertCatalogEntryToString', 'UnitAbilityGetChargeUsed', 'AISetStock', 'CreateLookAtTargetAtPoint',
      'EventPlanetPanelDifficultySelected', 'TextTagDestroy', 'UnitCargoValue', 'TerrainShowRegion',
      'UnitSetPosition', 'CutsceneGoToBookmark', 'EventPlayerEffectUsedPoint', 'CreateCopy', 'AISetFilterBits',
      'SetDialogItemActor', 'HelpPanelDestroyAllTutorials', 'DialogControlSetPropertyAsFixed',
      'DataTableGetControl', 'GamePlayTime', 'ActorLastCreated', 'GameSetSeedLocked', 'TechTreeAbilityAllow',
      'UserDataGetString', 'ConversationDataLineId', 'SaveDataTableValueDifficultyLevel', 'DialogIsOffscreen',
      'CameraSetChannelOnPortrait', 'TriggerDebugSetTypeColor', 'FixedToText', 'PlayerInStoryMode',
      'DialogControlCreate', 'DataTableSetMarker', 'PathCreateForUnitType', 'FogSetStartHeight',
      'EventCustomDialogResult', 'DataTableSetSoundLink', 'UISetRestartLoadingScreen', 'LastReplacedUnit',
      'DataTableGetAIFilter', 'DataTableGetActorScope', 'SetTeamColor', 'SetScale', 'TextTagSetAlignment',
      'ForEachInteger2', 'BoardMinimizeSetColor', 'cai_wave_createdWave', 'ConversationReplySetState',
      'EventUnitCreatedUnit', 'VictoryPanelSetCustomStatisticValue', 'AIFindUnits',
      'EventBattleReportPanelDifficultySelected', 'TechTreeRestrictionsEnable', 'PurchaseGroupSetSlot',
      'PlayerPauseAllCharges', 'SoundLengthQueryWait', 'AIWaveDelete', 'AIAttackWaveSetTargetPoint',
      'SoundtrackSetContinuous', 'Round', 'DataTableSetSound', 'TriggerAddEventMercenaryPanelPurchase',
      'AIBuild', 'PingSetUnit', 'AIClearCloakedAttacker', 'AISetUnitNotUsableInWaves',
      'TriggerAddEventGameCreditsFinished', 'AIWaveTargetGatherO', 'PlanetSetTechnologyTitle',
      'PlayerPauseAllCooldowns', 'OrderGetTargetItem', 'PingSetVisible', 'ConvertBearingsToString',
      'PlayerScoreValueSetFromFixed', 'PlanetPanelSetDismissButtonEnabled', 'UnitBehaviorAddChargeRegen',
      'ModelAnimationLoad', 'SendTransmissionSimple', 'StoryMode', 'MercenarySetUnitText', 'PlayerGroupAdd',
      'UnitStatusBarClearOverride', 'DialogItemMinimumValue', 'PingSetScale', 'ConversationDataChoiceGetPicked',
      'HideScreenImage', 'UnitControlGroupClear', 'DataTableGetInt', 'PathGetUnit', 'SoundSetMuted',
      '_BB_HPBorderWidth', 'DataTableValueCount', 'DataTableGetAbilCmd', 'CatalogFieldTypeCategory',
      'PortraitSetPaused', 'EventMouseMovedPosXUI', 'DialogControlGetPropertyAsColor', 'ResearchItemPurchase',
      'AIAttackWaveAddWaypoint', 'TriggerAddEventUnitCreated', 'PortraitSetTransitionModel',
      'AIWaveTargetAddWaypoint', 'EventTimer', 'ObjectiveShow', 'UnitGroupLoopCurrent',
      'GameWaitForResourcesToComplete', 'UnitIsValid', 'PingCreate', 'WithinBounds',
      'TriggerAddEventConversationStateChanged', 'PlayerGetCooldown', 'MakeModelFaceAngle', 'AttachSetRotation',
      'DataTableSetCinematic', 'ListRemove', 'DataTableSetUnit', 'UserDataGetInt', 'BattleReportSetBonusText',
      'UnitInventoryContainer', 'ConversationDataSaveStateValue', 'PlanetClearSelected', 'AIMakeOnce',
      'GameSaveCreate', 'UnitOrder', 'GameAttributePlayerValue', 'ConversationDataGetSound',
      'VictoryPanelAddTrackedStatistic', 'AIDefaultGetMaker', 'ActorWorldParticleFXDestroy',
      'PlayerAddChargeUsed', 'ObjectiveCreate', 'UnitCheckProgressState', 'TextTagSetEdgeImage',
      'PingSetPosition', 'UnitRemoveCooldown', 'FormatNumber', 'UIClearBattleNetButtonOffset',
      'SoundStopAllTriggerSounds', 'TriggerAddEventUnitProperty', 'AICast', 'TextureVideoSetTime',
      'RegionAttachToUnit', 'AIGetUnitsInWavesWithTarget', 'PortraitSetMuted', 'AIGetMaxPeonCount',
      'PreloadObject', 'StringReplaceWord', 'DataTableSetWave', 'PreloadSoundLength', 'PreloadSoundObject',
      'RescueUnit', 'UserDataGetText', 'UserDataInstanceCount', 'TriggerAddEventUnitAcquiredTarget',
      'CameraLookAt', 'ActionImpact', 'MakeMsgRefCreate', 'DialogLastCreated', 'StringToText222',
      'BankConditionEvaluate', 'PlanetSetTechnologyName', 'ConversationDataLoadStateValue',
      'GameTimeOfDayGetLength', 'MercenarySetAvailabilityText', 'UnitBehaviorGetCooldown', 'GameTerrainSet',
      'UserDataGetAbilCmd', 'VictoryPanelSetAchievementsTitle', 'UnitInventoryRemove', 'UnitBehaviorHasFlag',
      'AIWaveTargetMerge', 'UnitCanAttackTarget', 'DataTableGetUnit', 'ResearchTierDestroyAll', 'UnitInRegion',
      'EventUnitAttributePoints', 'TriggerAddEventCutsceneBookmarkFired', 'SetBossBarRace', 'AIAttackWaveCancel',
      'AIBaseThink', 'GameIsTransitionMap', 'BoardItemSetFontSize', 'ActorScopeKill',
      'ConversationDataStateModel', 'DialogSetSubtitlePositionOverrideControl', 'HelpPanelShowTechTreeRace',
      'AIRandomSpawnPoint', 'GameMapIsBlizzard', 'BoolToInt', 'PingGetPosition', 'MoverSetDestinationZ',
      'AIAttackWaveAddUnits4', 'CutscenePause', 'UnitBehaviorCountAll', 'TriggerDebugEnableType',
      'UnitBehaviorRemovePlayer', 'UnitAbilityAddCooldown', 'EventPingedMinimap', 'UnitSetProgressComplete',
      'UnitIsUnderConstruction', 'DialogSetSize', 'PurchaseGroupCreate', 'PurchaseGroupSetIconFilePath',
      'GameGetChargeRegen', 'UnitGroupFilterRegion', 'EventKeyControl', 'ConversationDataChoiceId',
      'TriggerAddEventSelectedPurchaseItemChanged', 'TextureVideoSetPaused', 'ConversationReplyGetText',
      'ConvertBooleanToText', 'AIAttackWaveSetTargetMelee', 'MercenarySetImageFilePath', 'AIAttackWaveUseUnit',
      'VictoryPanelSetBackgroundFilePath', 'PortraitSetActor', 'PortraitForceTransition',
      'PlayerScoreValueEnable', 'UnitCanCreateEffectAtPoint', 'CatalogFieldType', 'SetAnimationTimeScale',
      'TextureVideoStopAll', 'CreateExplosionAtPoint', 'AIWaveEvalRatio', 'UnitOrderIsValid', 'SoundLinkAsset',
      'AIWaveTargetUnitGroup', 'SetDialogItemTextWriteoutDuration', 'UIStatusBarOverride',
      'MakeMsgSetPhysicsState', 'DifficultyEnabled', '_BB_HPBarHeight', 'MercenaryCreate',
      'SetDialogItemImageType', 'TriggerAddEventCutsceneEndSceneFired', 'SetDialogItemAnimationDuration',
      'ValueFromDataTableDialogItem', 'BankValueSetFromPoint', 'DialogControlIsVisible',
      'PurchaseItemSetTooltipText', 'UnitAbilityReset', 'RandomPercent', 'DataTableGetPoint',
      'ConversationDataChoiceCount', 'AIIsScriptControlled', 'AISetStockEx', 'SetDialogItemCustomTooltip',
      'UnitStatusBarOverride', 'AIRemoveGroupFromAnyWaves', 'UIHideTextCrawl', 'PlayerDifficulty',
      'SoundPlayOnUnit', 'UnitWeaponCheck', 'EventUnitOwnerOld', 'AttachModelToActor', 'ActorRegionSend',
      'GameAttributePlayersForTeam', 'EventCameraMoveReason', 'UnitAddOnParent', 'ObjectiveGetPlayerGroup',
      'PurchaseSetSelectedPurchaseItem', 'ConvertStringToCatalogEntry', 'PauseUnit',
      'AICombatDiffFlagTieBreakRange', 'UserDataSetUnit', 'UnitBehaviorEffectPlayer', 'SetPosition',
      'PreloadSound', 'EventDialogControl', 'RegionRandomPoint', 'PortraitSetMouseTarget', 'UISetWorldVisible',
      'PlanetPanelSetBackButtonShortcut', 'ConversationDataChoiceGetPickedCount', 'UISetChallengeCompleted',
      'AchievementAward', 'RefDestroy', 'EventMouseMovedPosZWorld', 'TextTimeFormat', 'ConvertPresetToReal',
      'ConvertPresetToString', 'DataTableSetActor', 'TriggerAddEventMercenaryPanelSelectionChanged',
      'PerfTestStop', 'PlanetSetTechnologyTooltipText', 'UserDataSetCompare', 'UnitWaitUntilIdle',
      'PathGetDestinationPoint', 'PlayerCanCreateEffectOnUnit', 'AISetScoutTimes', 'ArithmeticRealClamp',
      'DialogControlGetPropertyAsString', 'TriggerAddEventPlanetMissionSelected',
      'TriggerAddEventVictoryPanelPlayMissionAgain', 'UIClearMessages', 'DataTableGetPortrait',
      'ConversationReplySetText', 'EventPlayerWave', 'UnitRallyPointTargetPoint', 'RandomPointBetweenPoints',
      'DialogControlForceTransition', 'SoundChannelSetVolume', 'GamePauseAllCooldowns', 'PlayerHasLicense',
      'WorldHeight', 'EventGenericName', 'PingGetUnit', 'SetRenderToTextureEnabled', 'DialogControlSelectItem',
      'TechTreeUnitHelp', 'SetAnimationDuration', 'ConvertPresetToTrigger', 'MovieAddTriggerFunction',
      'TextTagSetFontSize', 'DialogControlGetPropertyAsText', 'MoverSetDeceleration', 'SetTacticalAIThink',
      'ConvertXYToString', 'TurnAllAnimationPropertiesOff', 'PreloadModel', 'DialogControlAddItem',
      'UISetNextLoadingScreenTextPosition', 'PurchaseItemSetState', 'ConversationDataStateGetValue',
      'QueuedUnitTypeInTrainingQueueSlot', 'BattleReportAddAchievement', 'DataTableSetAIFilter',
      'AICombatDiffFlagTieBreakLowHP', 'DialogClearSubtitlePositionOverrideControl',
      'TriggerAddEventMovieFunction', 'Log2', 'GameGetChargeUsed', 'SwooshCamera', 'ResearchItemSetTooltipText',
      'TextureGroupApply', 'SetBearingsFrom', 'TextureDump', 'GameGetSpeedValue', 'DataTableGetText',
      'SoundChannelStop', 'ConvertPlayerColorToColor', 'cai_waves_enable', 'GameAddCooldown',
      'GamePauseAllCharges', 'DialogGetAnchor', 'UnitFilterMatch', 'DialogGetTransparency', 'UserDataSetModel',
      'AIAttackWaveSetTargetPlayer', 'PlanetSetTechnologyIconFilePath', 'DialogGetOffsetY',
      'DialogControlHookup', 'BankOptionSet', 'AIAttackWaveSend', 'SwitchCase', 'DifficultyIstwo',
      'AttachModelToUnit', 'UnitAbilityChargeInfo', 'DataTableSetUnitFilter',
      'DialogControlSetPropertyAsControl', 'AIGetRawGasNumSpots', 'ResearchItemDestroy',
      'UnitGroupFilterAlliance', 'EventPlayerEffectUsedUnitType', 'EventPingUnit', 'PathGetLineWidth',
      'ScreenImageDialog', 'PingSetModel', 'SetAllSoundChannelVolumes', 'AIWaveHarassRetreat',
      'StringExternalAsset', 'PurchaseItemSetRecentlyPurchased', 'TriggerAddEventUnitBehaviorChange', 'Print',
      'ConvertTargetFilterStringToUnitFilter', 'SetPosition2DH', 'SetDialogItemStyle',
      'ConvertStringToCatalogFieldName', 'GameCheatsEnabled', 'AIControlWantsToMove', 'SimpleLookAtStop',
      'PlayerRemoveChargeUsed', 'TruncI', 'TriggerAddEventUnitRemoved', 'PlanetSetTechnologyText',
      'TransmissionSend', 'CutsceneShow', 'TextTagSetBackgroundOffset', 'AISetFilterLifePerMarker',
      'MainActorofUnit', 'ResearchCategorySetLastLevel', 'AchievementPanelSetVisible',
      'TriggerAddEventPurchaseExit', 'PortraitSetAnim', 'Pow2I', 'PurchaseCategoryDestroyAll',
      'TimerWindowCreate', 'ShowHideUnit', 'UnitGroupSearch', 'BattleReportSetMissionImage',
      'DataTableGetPlayerGroup', 'DialogSetChannel', 'UnitCanAttackUnit', 'GameIsTestMap', 'AISetFilterPlane',
      'CopyOfCameraObject', 'EventBattleReportPanelMissionSelected', 'ActorFromScope', 'AIHarvestRate',
      'UnitBehaviorRemoveChargeUsed', 'MercenaryIsRecentlyPurchased', 'UnitRallyPoint', 'LastCreatedActorScope',
      'DataTableSetBank', 'RestartGame', 'PortraitSetRenderType', 'AIAttackWaveSetKeepAlive',
      'ShowHideLeaderboard', 'PurchaseItemDestroyAll', 'VictoryPanelSetVictoryText', 'UISetCursorVisible',
      'PurchaseItemIsRecentlyPurchased', 'AIWaveGetUnits', 'UnitRemoveChargeUsed', 'ConvertPresetToUnitFilter',
      'BattleReportSetState', 'EventMouseClickedPosXUI', 'CampaignInitAI', 'ResearchItemLastCreated',
      'GameDestroyEffects', 'SoundChannelPause', 'OrderTargetingPoint',
      'TriggerAddEventSelectedPurchaseCategoryChanged', 'SetDialogItemTeamColorIndex', 'ShareVisionofUnit',
      'AIWaveTargetPoint', 'TriggerAddEventUnitBecomesIdle', 'DifficultyNameCampaign', 'AnimSetPaused',
      'ModelAnimationLoadOverriding', 'UnitQueueGetProperty', 'AILastAttacker', 'MercenaryLastCreated',
      'DataTableSetOrder', 'TextTagSetText', 'UserDataSetImageAttachPoint', 'VictoryPanelSetMissionTimeTitle',
      'EventMouseClickedPosYWorld', 'TriggerAddEventButtonPressed', 'DialogControlRemoveItem',
      'TriggerAddEventUnitAttributeChange', 'DataTableGetWaveTarget', 'PurchaseCategorySetState',
      'UnitAbilityMaxLevel', 'SetDialogItemChecked', 'ConversationDataChoiceSetPickedCount',
      'TriggerAddEventPlanetMissionLaunched', 'ValueFromDataTableDifficultyLevel', 'ActorRegionCreate',
      'AddUnitGroupToUnitGroup', 'TriggerAddEventPlanetPanelReplayPressed', 'RegionPlayableMap',
      'GameTimeOfDaySetLength', 'AIAttackWaveSetTargetUnit', 'PurchaseCategoryDestroy', 'DataTableGetReply',
      'ObjectiveSetPriority', 'UserDataSetString', 'CatalogEntryClass', 'TriggerAddEventUnitInventoryChange',
      'SetAnimationCompletion', 'GameAddChargeUsed', 'OrderGetTargetType', 'EventPingPoint',
      'UnitBehaviorRemoveCategory', 'Convert3DVectorToString', 'UnitFlashSelection',
      'UnitTypeMoveBlockersFromPoint', 'GameSetSeed', 'DataTableGetColor', 'EventMouseMovedPosYUI',
      'AIReqCountAsBuiltObject', 'TextureGetSlotComponent', 'FogSetDensityOverTime', 'ActorGetText',
      'HideScreenButton', 'EventMouseClickedPosZWorld', 'ConversationDataLoadNodeState',
      'UnitTypeIsAffectedByUpgrade', 'UnitSetCustomValue', 'PingGetRotation', 'PortraitSetBackgroundVisible',
      'UnitIsHidden', 'SimpleLookAtStart', 'CameraSetMouseRotates', 'SoundPlayScene', 'ObjectiveGetName',
      'GlobalCinematicSetting', 'SetDialogItemToggled', 'UIShowCustomMenu', 'AIAttackWaveSetTargetPatrol',
      'UserDataSetSound', 'AIWaveTargetMelee', 'GameMapDescription', 'DialogControlLastCreated',
      'GameCheatAllow', 'EventUnitTarget', 'CutsceneSetFilter', 'UnitAgent', 'AIGetFilterGroup',
      'OrderSetTargetItem', 'UnitTypeGetName', 'PlayMovieTextureOnUnitActor', 'AIGetGasAmountLeft',
      'PlanetSetBackgroundModelLink', 'CatalogReferenceGet', 'BoardMinimizeEnable', 'ActorFromDoodad',
      'DialogControlInvokeAsText', 'ActorLastCreatedSend', 'MoverSetSpeedFromDuration', 'AIDeclareTown',
      'UISetMiniMapBackGroundColor', 'CatalogFieldValueCount', 'StringFind', 'cai_wave_createdUnits',
      'ConversationShow', 'DialogControlGetRelativeAnchor', 'UnitEventSetNullVariableInvalid',
      'MakeMsgRefTableDump', 'PlanetGetSelected', 'EventPlanetPanelMissionSelected', 'UnitAddChargeRegen',
      'PathLastCreated', 'MakeUnitInvulnerable', 'BoardCreate', 'CameraSave', 'BankLastRestoredUnit',
      'UserDataFieldIsModifiable', 'DataTableSetWaveInfo', 'PickEachPlayerInGroup',
      'VictoryPanelSetStatisticsTitle', 'MakeMsgTextureSelectByMatch', 'AliasRemove', 'ActorFromDialogControl',
      'UIAlert', 'TechTreeUnitAllow', 'MercenarySetSpecialText', 'UserDataSetMovie',
      'QueuedBehaviorTypeInTrainingQueueSlot', 'PointSetHeight', 'RegionGetAttachUnit',
      'AIDefaultGetFullMakeTime', 'ConvertIntegerToDebugMessageType', 'UISetGameMenuItemVisible',
      'TriggerAddEventUnitPowerup', 'DifficultyAPM', 'DialogControlSetPropertyAsString', 'UserDataSaveInstance',
      'CreateDialogItemCheckBox', 'PlayerValidateEffectUnit', 'AIExpand', 'UnitInventoryIndex', 'Destroy',
      'BankValueGetAsText', 'UnitInventoryCreate', 'SoundSetFactors', 'TriggerAddEventPlayerLeft',
      'MovieStartRecording', 'TriggerAddEventUnitLearnProgress', 'StringToText', 'AIGetDefaultBuildFlags',
      'EventTrigger', 'TriggerAddEventUnitRevive', 'ConversationDataResetNodeState',
      'EventUnitProgressObjectType', 'RemovePlayerGroupFromPlayerGroup', 'EventCutsceneBookmark', 'PreloadUnit',
      'UnitAbilityGetCooldown', 'PlanetSetRewardTitle', 'SetLocalTintColor', 'WaterSetState',
      'TriggerDebugSetTypeName', 'MercenaryPanelSetDismissButtonEnabled', 'DialogControlCreateInPanel',
      'AITransportSetReturn', 'GameRemoveCooldown', 'AttachActorToUnit',
      'TriggerAddEventPlanetPanelDeathComplete', 'ResearchItemSetDescriptionText', 'SoundLinkId', 'cai_runall',
      'DataTableGetUnitRef', 'UserDataGetActor', 'EventGameMenuItemSelected', 'AnimBlendTimeApply',
      'TriggerAddEventUnitGainLevel', 'GameRemoveChargeRegen', 'BoardItemSetProgressValue',
      'GameSetSpeedValueMinimum', 'DialogItemTooltip', 'EventMouseClickedButton', 'TextTagCreate',
      'ActorLookAtStop', 'UISetNextLoadingScreen', 'CutsceneCreateNew', 'UISetButtonFaceHighlighted',
      'TimerWindowVisible', 'Order', 'FogSetEnabled', 'DialogItemStyle', 'PlanetLastCreated',
      'AISetSpecificState', 'AIWaveInfoAttack', 'ConvertPresetToRevealer', 'SoundtrackPause',
      'GameGetMissionTime', 'CombineTextMultiple', 'PointPathingCost', 'PurchaseItemLastCreated',
      'SoundSubtitleText', 'ActorScopeGetText', 'PurchaseGroupLastCreated', 'AbilityCommandGetAction',
      'DialogGetRelativeDialog', 'MoverSetDestination2D', 'UnitSetHeight', 'EventBattleReportPanelSceneSelected',
      'TriggerAddEventUnitDamaged', 'DialogControlCreateFromTemplate', 'SetDialogItemMovie',
      'AINearestTownBullyRebuild', 'ActorScopeCreate', 'UISetNextLoadingScreenImageScale',
      'DataTableValueExists', 'CeilingI', 'CliffLevel', 'SoundSetOffset', 'DataTableSetPing',
      'UnitBehaviorSetDuration', 'BoardPlayerRemove', 'AIWaveState', 'AIMeleeStart',
      'TriggerAddEventPlanetPanelBirthComplete', 'DialogItemIsChecked', 'PlayAnimationOnDoodadsInRegion',
      'DialogControlSetPropertyAsInt', 'AIAttackWaveSetTargetEscort', 'UnitCanCreateEffectOnUnit',
      'AbilityCommandGetAbility', 'UnitWeaponDamage', 'MercenarySetState', 'PlayerGetChargeRegen',
      'EventUnitCreatedAbil', 'BattleReportSetDifficultyLevelBestTimeText', 'AIToggleBulliesInRegion',
      'StatusDecrement', 'UnitTypeGetProperty', 'PlayerGetColorIndex', 'TextTagSetFadedTransparency',
      'DialogControlGetOffsetY', 'DataTableSetPoint', 'UserDataGetMovie', '_BB_PortraitBorderHeight',
      'UnitAddCooldown', 'AIEvalSetCustomIndex', 'CreateDialogItemLabel', 'StatusIncrement',
      'UnitValidateEffectUnit', 'CrossCliff', 'TextTagSetMaxSize', 'ResearchItemSetState',
      'UnitTypeAnimationLoad', 'DialogItemImage', 'SetDialogItemRenderPriority', 'GameSetGlobalTimeScale',
      'CameraSetData', 'ActorLookAtTypeStop', 'UnitCreateEffectPoint', 'PlanetSetTechnologyUnitLink',
      'TurnAnimationPropertiesOff', 'SetDialogItemAnimationTime', 'AIWaveGetTimeInCombat', 'SoundPortraitModel',
      'TransmissionSourceFromUnit', 'PingDestroy', 'UserDataGetUserType', 'DialogGetHeight',
      'PortraitSetModelAnim', 'cai_wave_isEnabled', 'AISetMainTown', 'UserDataResetInstance', 'HideGameUI',
      'DifficultyName', 'UnitRemoveChargeRegen', 'CameraLookAtActor', 'UserDataField', 'CameraShake',
      'TextTagSetBackgroundBorderSize', 'DataTableGetSound', 'AIGetTownThreats', 'ScreenButton',
      'UserDataResetAll', 'GameGetCooldown', 'DataTableValueRemove', 'PreloadModelAnimation', 'AnimPlaySequence',
      'AICombatDiffFlagCatSortBuildingsPrio', 'AISetGroupTacticalDisabled',
      'AIRemoveGroupFromAnyWavesAndSetHome', 'GameGetSpeed', 'ForEachInteger', 'UserDataSetText', 'ActionDamage',
      'MercenarySetModelLink', 'UnitBehaviorAddCooldown', 'CutscenePlayCutsceneRangeOverTime',
      'UserDataGetCompare', 'SetDialogItemDesaturationColor', 'SetDialogItemFlash', 'UnitSetCursor',
      'SoundtrackDefault', 'AbsF', 'DataTableSetString', 'PortraitSetModel', 'DataTableGetObjective',
      'AIGlobalSuicide', 'VisRevealArea', 'EventPlayerPropertyChangeInt', 'AttachSetPositionFrom',
      'CameraLookAtUnit', 'DifficultyHigh', 'EventUnitProperty', 'ActorTextureGroupApplyGlobal',
      'PathGetUnitType', 'cai_getCustomData', 'AIGrabUnit', 'DialogControlGetPropertyAsUnit', 'SetBearingsH',
      'MakeMsgTextureVideoSetTime', 'VictoryPanelSetSummaryBackgroundFilePath', 'TriggerStop',
      'DialogControlGetType', 'TechTreeAbilityIsAllowed', 'TriggerAddEventUnitGainExperience',
      'PlayerSetColorIndex', 'RoundI', 'TextTagFogofWar', 'AIRemoveUnitFromAnyWaves', 'CreateActorAtPoint',
      'PingLastCreated', 'TransmissionSetOption', 'AISetUnitSuicide', 'MoveBossBar', 'UnitSetState',
      'AISetIgnoredByWave', 'AIGetBuildingCountInTown', 'PlanetPanelSetContactButtonState',
      'DialogControlDestroy', 'AIGetMineralNumSpots', 'UISetResourceTradeCountdownTime', 'Floor',
      'VictoryPanelClearCustomStatisticTable', 'ConversationDataLineGetPickedCount', 'UnitCreate',
      'AchievementsDisable', 'AttachSetPosition', 'UnitBehaviorEnabled', 'ListAdd', 'ActorLookAtStart',
      'CameraSetVerticalFieldOfView', 'AIDefaultGetFirstMissingReq', 'UnitForceStatusBar',
      'UnitGetPropertyKills', 'TriggerAddEventUnitOrder', 'DialogControlSetPropertyAsText',
      'TriggerAddEventTimePeriodic', 'AISetGroupNotUsableInWaves', 'AnimBlendTimeRemove', 'ActorScopeFromUnit',
      'PointGetHeight', 'TriggerAddEventResearchPanelPurchase', 'BattleReportSetPriority',
      'AIWaveTargetMeleeHarass', 'SetDialogItemUnit', 'AIMarker', 'AnimSetDuration', 'GameGetGlobalTimeScale',
      'TriggerGetFunction', 'MakeMsgAnimPlay', 'PlayAnimation', 'SetRotation', 'TextureGroupRemove',
      'ConversationDataStateSetValue', 'PointSetFacing', 'PointPathingIsConnected',
      'AIAttackWaveSetTargetGatherD', 'PortraitSetChannel', 'AISetStockOpt', 'AIState', 'UnitWeaponCount',
      'WaveLastCreated', 'UnitResetSpeed', 'DeathCustomize', 'CatalogFieldValueGetAsInt',
      'GameIsMissionTimePaused', 'TimerLastStarted', 'While', 'ResearchTierSetMaxPurchasesAllowed',
      'UISetSelectionTypeEnabled', 'PortraitDestroyAll', 'TriggerAddEventUnitAttacked', 'PurchaseItemCreate',
      'SaveDataTableValueDialogItem', 'DialogSetVisible', 'ConversationDataChoiceGetState',
      'SendActorMessageToGameRegion', 'DialogControlCreateInPanelFromTemplate', 'MovieAddSubTitle',
      'BoardItemSetProgressRange', 'AICombatDiffFlagCatWorkersNormalPrio', 'BankDeleteCampaignBanks',
      'UnitCreateEffectUnit', 'AIGetClosestTown', 'GameSetBackground', 'VictoryPanelSetMissionTimeText',
      'DataTableSetObjective', 'AIGetFirstMissingReq', 'PurchaseGroupDestroyAll', 'DataTableValueName',
      'TransmissionClearAll', 'ActionQueueAdd', 'CreepModify', 'MakeUnitLookAtUnit', 'DialogControlIsFullDialog',
      'PowI', 'SoundSetReverb', 'PurchaseItemSetMovieFilePath', 'ActorFromActor', 'PlanetSetSelected',
      'SoundtrackWait', 'MoviePlayAfterGame', 'SetBossBarMaximumValue', 'ResearchItemSetSelected',
      'DifficultyValueInt', 'ConversationDataLineSetPickedCount', 'PortraitSetVisible', 'EventPurchaseMade',
      'DialogControlGetPropertyAsBool', 'PathSetLineTileLength', 'PingGetTooltip', '_BB_TitleBarHeight',
      'PingGetScale', 'EventPlayerEffectUsed', 'BoardMinimizeShow', 'CutsceneGoToNextBookmark',
      'UISetBattleNetButtonOffset', 'CameraGetYaw', 'EventCutsceneId', 'ConversationDataPreloadLines',
      'UnitTypeTestAttribute', 'PlanetSetContactModelLink', 'CinematicDataRun', 'UIAlertPoint',
      'DialogSetPositionRelative', 'UserDataGetImageAttachPoint', 'DialogControlGetRelativeControl', 'MinI',
      'ConversationDataStateText', '_BB_TitleBarWidth', 'ConvertCatalogFieldNameToString',
      'DialogSetTransparency', 'StopLooping', 'MakeMsgTextureVideoStop', 'TextureSelectByID',
      'CreateDialogItemAchievement', 'TransmissionSendAdvanced',
      'UnitsInRegionWithAllianceToPlayerMatchingCondition', 'ConversationDataActiveLine', 'AISetFilterLife',
      'DataTableSetByte', 'PortraitSetFullscreen', 'UISetCommandDisallowedMessage', 'SquareRootI',
      'EventUnitOwnerNew', 'BoardMinimizeSetState', 'StringToText23', 'DataTableSetCameraInfo', 'BankPreload',
      'FixedToTextAdvanced', 'LookAtTargetFromUnitAttachPoint', 'SetPositionFrom', 'SoundAddDSP',
      'AIGetGatherLocation', 'DialogSetFullscreen', 'PlayerScoreValueSetFromInt', 'AISetGeneralRebuildCount',
      'ConversationReplyGetState', 'ConversationDataStateUpgrade', 'TerrainTexture', 'PlanetSetState',
      'ConvertPresetToUnit', 'SoundtrackSetShuffle', 'PlanetPanelSetBackButtonTooltip', 'UnitSetPingCursor',
      'PlayerScoreValueGetAsFixed', 'ConvertStringToGameLink', 'AIClearTrainQueue', 'AttachActorToActor',
      'AIWaveType', 'AICombatDiffFlagCatSpecialHighPrio', 'DataTableGetBool',
      'BattleReportPanelGetSelectedBattleReport', 'cai_wave_run', 'UIFlyerHelperClearOverride',
      'ResearchCategoryCreate', 'BattleReportSetShownInMissionTotal', 'Trunc', 'ArithmeticIntClamp',
      'AIDefaultCombatPriority', 'BattleReportSetDifficultyLevelCompleted', 'PurchaseGroupSetNameText',
      'TriggerWaitForTrigger', 'TriggerAddEventVictoryPanelExit', 'DataTableSetColor',
      'StopAllVideoTexturesOnUnit', 'UnitGetCustomValue', 'TriggerAddEventUnitTrainProgress',
      'DataTableSetPlanet', 'BankPlayer', 'DisplayScreenButton', 'EventUnitInventoryChange', 'UnitGroupCount',
      'CatalogFieldExists', 'UnitBehaviorSpawn', 'ConvertStringToImageFile', 'DifficultyValueFixed',
      'DataTableSetTransmission', 'ResearchCategorySetCurrentLevel', 'UnitWeaponRemove', 'SoundPlay',
      'SoundLengthQuery', 'BattleReportSetSceneImage', 'CreateLookAtTargetAtUnitAttachPoint',
      'ConvertCatalogScopeToString', 'UnitIsPaused', 'CatalogFieldIsScope', 'PlayerGroupLoopCurrent',
      'AIRemoveUnitFromAnyWavesAndSetHome', 'DataTableGetTimer', 'DialogSetObservedType', 'RestoreUnitSelection',
      'AIWaveIsInCombat', 'AIReleaseUnit', 'AIEvalRatio', 'AIUnitGetWave', 'GameSetSpeedLocked', 'CombineText',
      'EventMouseClickedPosYUI', 'UserDataGetUserInstance', 'PlayerSetLighting', 'QueryRegion',
      'PathSetLineWidth', 'SetPosition2D', 'AIGetCurPeonCount', 'AchievementPanelSetCategory',
      'UnitBehaviorAddChargeUsed', 'TimerSet', 'TriggerAddEventBattleReportPanelPlayScene', 'AIDefaultEconomy',
      'MakeUnitLookAtPoint', 'AISameCommand', 'TipAlertPanelClear', 'AIPathingCostMap', 'AIAttackWaveAddUnits3',
      'cai_waves_stop', 'UISetChallengeScoreText', 'PurchaseItemSetDescriptionText', 'ShowHideBossBar',
      'UnitSetTeamColorIndex', 'GameSetToDLighting', 'VictoryPanelSetRewardCredits',
      'TriggerAddEventCustomDialogDismissed', 'TriggerAddEventUnitArmMagazineProgress',
      'UnitRallyPointTargetCount', 'MovieDynamicSubtitlesandDuration', 'PlayerGetChargeUsed',
      'TransmissionCommentConversation', 'ResearchItemSetIconFilePath', 'Color255FromFixed',
      'UnitGroupFilterPlayer', 'AISetStockFree', 'AIClearResearchQueue', 'SetDialogItemClickOnDown',
      'SetDialogItemImage2', 'UnitTypePlacementFromPoint', 'PurchaseItemPurchase', 'UISetDragSelectEnabled',
      'WidthOfRegion', 'cai_waves_run', 'DataTableGetRegion', 'MaxF', 'AliasAdd', 'UISetCursorAutoHide',
      'GameSetTransitionMap', 'AISetAllStates', 'UIFlyerHelperOverride', '_BB_HPBarFormatLabel',
      'ConvertCatalogFieldPathToString', 'DialogGetTitle', 'UserDataSetUser', 'UIShowCustomDialog',
      'UserDataSetAbilCmd', 'ConversationDataStateFixedValue', 'PointPathingPassable', 'AISetDefenseRadii',
      'CameraClearChannelOnPortrait', 'CameraSetChannel', 'UISetMode', 'TransmissionSourceFromMovie',
      'AISetFlag', 'OrderSetAutoCast', 'UnitControlGroupRemoveUnit', 'StopPulsingScreenImage',
      'PortraitGetTriggerControl', 'ResearchItemGetSelected', 'GameAddChargeRegen', 'CinematicMode',
      'UnitGroupRemove', 'ConvertStringToUserDataInstance', 'BattleReportSetButtonImage',
      'UnitTypeAnimationUnload', 'PlanetPanelGetContactButtonState', 'UnitRevive', 'Switch', 'AnimBaselineStart',
      'PortraitSetBorderVisible', 'AIKnownUnitCount', 'DialogControlGetPropertyAsFixed', 'PlanetSetBonusText',
      'AIGetCloakedAttacker', 'AICombatDiffFlagTieBreakBonusDamage', 'UnitWeaponPeriod', 'ConvertColorToString',
      'VictoryPanelSetCustomStatisticText', 'AISetStockExpand', 'SetDialogItemCurrentValue', 'CutsceneSetTime',
      'PurchaseGroupSetPlayerGroup', 'CampaignProgressSetImageFilePath', 'UnitAbilityAddChargeRegen',
      'HelpPanelDestroyHelpItem', 'AISetStockAlias', 'AIGetTownState', 'HelpPanelDestroyAllTips', 'UnitGroupAdd',
      'PlayerModifyPropertyInt', 'BankValueSetFromText', 'UIStatusBarClearOverride', 'AIResearch',
      'UserDataSetUpgrade', 'BattleReportDestroy', 'AnimSetTimeScaleGlobal', 'StringToText22',
      'TransmissionWait', 'PlayerAddCooldown', 'VictoryPanelSetRewardTitle', 'DataTableSetRegion',
      'DialogControlSetFullDialog', 'DataTableSetTrigger', 'PurchaseGroupSetTooltipText', 'AIWaveSet',
      'CameraSetValue', 'SetDialogItemColor', 'UserDataResetType', 'DialogGetImage',
      'UnitBehaviorRemoveCooldown', 'ConversationDataRegisterUnit', 'UnitWeaponIsEnabled',
      'ConvertPresetToColor', 'OrderTargetingUnitGroup', 'CharacterSheetPanelSetNameText',
      'HelpPanelAddTutorial', '_BB_PortraitWidth', 'TextTagSetTextShadow', 'PlayerValidateEffectPoint',
      'DisplayBossBar', 'ConversationDataCanRun', 'ResearchItemCreate',
      'CharacterSheetPanelSetPortraitModelLink', 'ResearchCategoryDestroy', 'StoreUnitSelection',
      'CameraRestore', 'TriggerAddEventKeyPressed', 'UserDataGetSound', 'UISetCustomMenuItemShortcut', 'SetZ',
      'ObjectiveGetDescription', 'CostOfAbility', 'GameAttributeGameValue', 'PreloadAsset',
      'RegionPlayableMapSet', 'UIAlertClear', 'DataTableSetWaveTarget', 'UISetResourceTradingAllowed',
      'ResearchItemSetNameText', 'TriggerSendEvent', 'AILastAttack', 'SoundPause', 'FullscreenPortrait',
      'AIWaveAddUnitPriority', 'DialogSetImageVisible', 'UnitAbilityRemoveChargeRegen',
      'TriggerAddEventMouseClicked', 'UISetGameMenuItemText', 'ResearchTierDestroy', '_BB_HPBorderHeight',
      'KillDoodadsInRegion', 'UnitBehaviorGetChargeRegen', 'PurchaseItemDestroy', 'RemoveUnitGroupFromUnitGroup',
      'TextureGetSlotName', 'FogSetColor', 'SoundtrackPlay', 'ReviveOrderWithNoTarget', '_BB_HPBarChange',
      'AnimDumpDB', 'AbilityCommandGetCommand', 'UnitMagazineArm', 'UILaunchNydusLink', 'PickEachInteger',
      'PlanetSetPlanetText', 'CreateModelAtPoint', 'AnimClear', 'TriggerAddEventResearchPanelExit',
      'PurchaseItemSetNameText', 'AIEnableStock', 'SetUpgradeLevelForPlayer', 'PlanetSetBonusTitle',
      'AIWaveInfoAdd', 'CutsceneCreateNoPosition', 'TriggerAddEventPlayerEffectUsed', 'AIAddBully',
      'UIFrameFlagCheck', 'PingSetPlayerPingsShown', 'TriggerAddEventPlanetPanelCanceled',
      'MakeMsgAnimBracketStart', 'UnitGetProgressComplete', 'TextCase', 'RefreshBossBar', 'StringWord',
      'TriggerAddEventMouseMoved', 'ActorScopeLastCreatedSend', 'UnitTypeFromString', 'IncrementInteger',
      'CameraApplyInfo', 'PortraitSetTeamColor', 'DataTableSetDoodad', 'DataTableSetRevealer',
      'MercenaryPanelSetCloseButtonEnabled', 'AIAttackWaveSetTargetUnitGroup', 'EventConversationState',
      'ConvertPresetToReply', 'CameraClearChannel', 'AIInitCampaignTowns', 'PortraitSetCamera',
      'TransmissionSourceFromModel', 'DialogControlSetPosition', 'UISetCustomMenuItemVisible',
      'DialogControlSetPositionRelative', 'EventUnitInventoryItemTargetUnit', 'AIHarvest', 'PlanetDestroy',
      'PortraitLastCreated', '_BB_PortraitHeight', 'UserDataGetColor', 'UnitInventoryMove', 'EventButtonPressed',
      'ActorScopeSend', 'TriggerAddEventPing', 'FogSetDisableAtUltra', 'AISetBullyAttackWavePercent',
      'PurchaseItemSetIconFilePath', 'UserDataSetImageEdge', 'EventPlayerProperty', 'ClearPortraitAnimation',
      'PlayerHandle', 'PlanetSetSecondaryObjectiveText', 'PortraitWaitForLoad', 'CameraForceMouseRelative',
      'DialogGetOffsetX', 'AIGetFlag', 'FogSetColorOverTime', 'UnitTypeTestFlag', 'UserDataGetFixed',
      'StringReplace', 'ConversationDataStateAttachPoint', 'DataTableSetActorScope',
      'MakeMsgTextureSelectBySlot', 'HostSiteOpsSet', 'PortraitSetOffscreen', 'ResearchCategoryDestroyAll',
      'VictoryPanelAddCustomStatisticLine', 'TextureVideoSetFrame', 'UnitAbilityRemoveChargeUsed',
      'PlanetPanelSetBackButtonText', 'AIGetAllEscortsGroup', 'ConvertPresetToPoint',
      'FogSetStartHeightOverTime', 'ActorScopeFrom', 'PlayerType', 'CampaignProgressSetTutorialFinished',
      'EventKeyAlt', 'GameIsSpeedLocked', 'RefClear', 'DialogIsVisible', 'UnitQueueItemGet',
      'UnitControlGroupRemoveUnits', 'FormatDuration', 'UnitGroupAddUnitGroup', 'DialogDestroyAll',
      'CampaignMode', 'ConversationDataStateIndex', 'PingSetColor', 'AIFilter', 'PlayerGroupRemove',
      'TimerWindowSetStyle', 'AISetGroupSuicide', 'TurnAnimationPropertiesOnWithBlendInOut', 'DialogItemValue',
      'AINearestTownLimitWaveGather', 'DataTableGetUnitGroup', 'CameraUseHeightSmoothing',
      'MoverSetDestinationFrom', 'PortraitSetLight', 'cai_setDefGather', 'DialogControlGetOffsetX',
      'AIAttackWaveSetTargetRegion', 'AISetUnitScriptControlled', 'SetBearings', 'ObjectiveVisible',
      'PlanetSetSecondaryObjectiveTitle', 'CinematicOverlay', 'UnitControlGroupAddUnit',
      'PlayerCreateEffectPoint', 'UnitBehaviorEffectUnit', '_BB_HPBarCurrentWidth', 'UnitHasBehavior',
      'GameIsDebugOptionSet', 'EventUnitPropertyChangeInt', 'PurchaseGetSelectedPurchaseItem', 'AIGetBaseName',
      'AchievementTermQuantitySet', 'TextTagSetFogVisibility', 'DataTableGetMarker', 'RefSet',
      'CatalogFieldIsArray', 'UnitAbilityGetChargeRegen', 'CatalogEntryIsDefault', 'KillingUnit',
      'AIAttackWaveSetTargetMeleeHarass', 'UISetFrameVisible', 'ConversationDataRegisterCamera',
      'SetDialogItemBehavior', 'ConvertStringToCatalogFieldPath', 'ActorFromPortrait', 'AnimGroupRemoveAll',
      '_BB_HPBarWidth', 'CatalogReferenceGetAsInt', 'PlanetSetResearchTitle', 'AIIsTacticalDisabled',
      'EventUnitPropertyChangeFixed', 'DataTableGetByte', 'SoundtrackSetDelay', 'UnitGetTag',
      'StringExternalHotkey', 'UserDataFieldType', 'PlayerCanCreateEffectAtPoint', 'UserDataResetValue',
      'LastCreatedActor', 'PlayerRemoveChargeRegen', 'DataTableGetUnitFilter', 'RefSetFromMsg', 'RefDump',
      'PurchaseItemSetCost', 'PurchaseCategorySetSlot', 'AIGetBestTarget', 'PathSetColor', 'DialogItemImageType',
      'MoverSetDestinationH', 'PointFromXYZ', 'TechTreeUpgradeIsAllowed', 'PlanetSetPrimaryObjectiveText',
      'TriggerAddEventUnitConstructProgress', 'Log2I', 'TriggerAddEventGeneric', 'BattleReportLastCreated',
      'TriggerAddEventPurchaseMade', 'AnimSetTimeScale', 'PathGetLineTexture', 'UnitBehaviorRemoveChargeRegen',
      'SetDialogItemBlendMode', 'PathSetVisible', 'QueryRadius', 'UserDataSetActor',
      'AIAttackWaveSetTargetEscortNL', 'AttachSetRotationFrom', 'LookAtTargetFromPointWithZOffset',
      'AISetFilterMarker', 'UnitGetAIOption', 'FogSetFallOffOverTime', 'CampaignProgressSetText',
      'CameraFollowUnitGroup', 'EventVictoryPanelDifficultySelected', 'FogSetFallOff', 'AICastFlee',
      'AbilityCommand', 'PlanetDestroyAll', 'UserDataLoadInstance', 'AIIsNotUsableInWaves', 'UnitInventoryItem',
      'UnitInventoryCount', 'TriggerAddEventDialogControl', 'ForEachPlayerInGroup', 'ObjectiveGetPrimary',
      'UserDataSetImagePath', 'DataTableSetBool', 'PurchaseGroupDestroy', 'UnitAbilityShow',
      'SetNextMissionDifficulty', 'PlayerName', 'ValueFromDataTableTextTag', 'SetOpacity', 'EventCheatUsed',
      'AIInitCampaignHarvest', 'DialogControlSetSize', 'TransmissionCommentSound',
      'SaveDataTableValuePlayerColor', 'ConversationReplyDestroyAll', 'DialogControlDestroyAll',
      'TextTagSetBackgroundImage', 'MoverMove', 'Not', 'UnitInventoryGroup', 'CameraSetMouseRotationSpeed',
      'TriggerAddEventUnitStartedAttack', 'TextHasBeenSet', 'TriggerAddEventPlayerPropChange',
      'SaveDataTableValueTextTag', 'CinematicPortrait', 'Cycle', 'PlayerGroupAlliance',
      'BattleReportPanelSetSelectedBattleReport', 'UnitGroupRandomUnit', 'PlanetSetPlanetName',
      'DataTableGetWaveInfo', 'ConversationDataActiveSound', 'Convert3DRotationToString', 'AIWaveTargetGatherD',
      'EventUnitInventoryItemContainer', 'QueuedUpgradeTypeInTrainingQueueSlot', 'UnitGetHeight', 'AIWaveGet',
      'ColorFromIndex', 'EventUnitRangeUnit', 'AIGetMaker', 'DataTableGetRevealer', 'AIClearBuildQueue',
      'SetDialogItemText', 'AddPlayerGroupToPlayerGroup', 'ResearchItemSetConfirmationText',
      'ClosestUnitToPoint', 'DisplayScreenImage', 'EventPlayerEffectUsedUnit', 'ConvertUnitToUnitGroup',
      'DialogControlSetPropertyAsColor', 'GameSetLighting', 'IfThen', 'AISetFilterShields',
      'MakeMsgAnimGroupApply', 'DialogIsEnabled', 'AIHasRes', 'DataTableSetReply', 'SoundPlayAtPoint',
      'AIWaveToText', 'EventUnitBehaviorChange', 'DifficultyValueUnitType', 'DataTableSetUnitRef',
      'StringExternal', 'ResearchTierSetRequiredLevel', 'AITimePause', 'ConversationDataStateAbilCmd',
      'UnitGroupClosestToPoint', 'DialogControlSetPropertyAsBool', 'AICombatDiffFlagTieBreakHealers',
      'StorySetChange', 'DialogIsFullscreen', 'DifficultyIsone', 'MakeMsgAnimBracketResume',
      'AIWaveGetTimeSinceOrdered', 'PlayerScoreValueEnableAll', 'DialogCreate', 'PlanetCreate', 'TextTagVisible',
      'SoundPlaySceneFile', 'DialogIsModal', 'MoverStopNow', 'PathCreateForUnit',
      'DialogControlGetPropertyAsInt', 'PulseScreenImage', 'TimerKill', 'TriggerAddEventTimeElapsed',
      'SoundtrackStop', 'DialogSetEnabled', 'IfThenMultiple', 'UnitGetChargeRegen', 'SoundLengthSync',
      'PurchaseGetSelectedPurchaseCategory', 'PurchaseCategorySetNameText', 'AIAttackWaveSetTargetMerge',
      'AIAttackWaveSetTargetGatherO', 'StopFlashingScreenButton', 'EventPlayerEffectUsedAmountFixed',
      'ModelSwap', 'FloorI', 'PortraitUseTransition', 'BankOptionGet', 'CenterOfUnitGroup', 'DataTableGetDialog',
      'PurchaseCategoryCreate', 'BattleReportSetMissionText', 'MercenarySetSelected', 'MercenaryDestroy',
      'EventUnitInventoryItemTargetPoint', 'PingSetPlayerGroup', 'AIGoodGame', 'SetAlliance',
      'ActorScopeFromDialogControl', 'UserDataGetUnit', 'PreloadModelObject', 'AttachSetBearings',
      'OrderTargetingItem', 'DataTableGetTransmission', 'DialogItemText', 'AISetDifficulty',
      'TriggerAddEventResearchPanelSelectionChanged', 'DataTableGetCameraInfo', 'TextWithColor', 'Comparison',
      'BankValueGetAsPoint', 'ConvertPresetToTransmission', 'ValueFromDataTablePlayerColor', 'UnitBehaviorAdd',
      'MercenarySetTitleText', 'PickEachUnitInGroup', 'DataTableSetFixed', 'TransmissionSource',
      'SetDialogItemImageType2', 'AIWaveTargetEscort', 'CutscenePlay', 'CutsceneStop', 'UnitAbilitySpend',
      'PlanetSetContactTooltipText', 'UISetChallengeMode', 'SetDialogItemMinimumValue',
      'TriggerAddEventSaveGame', 'DialogControlFadeTransparency', 'ResearchCategorySetNameText',
      'UnitGetPropertyFixed', 'AISetFilterSelf', 'AIGetObjectType', 'UserDataFieldCount', 'SetAllianceOneWay',
      'AIGetAllEscorts', 'PreloadMovie', 'AIWaveTargetEscortNL', 'AICombatDiffFlagCatTimedLowPrio', 'AIGivingUp',
      'TransmissionIsComplete', 'DataTableGetCinematic', 'PathSetDestinationPoint', 'MercenarySetPlayerGroup',
      'UIClearCustomMenuItemList', 'AIScout', 'UnitCreateFacingPoint', 'ReviveOrderTargetingPoint', 'AndOrMult2',
      'ConversationDataLoadStateValues', 'AITrain', 'ActorSendTo', 'ConvertStringToCutsceneFile',
      'DataTableGetPing', 'DialogGetChannel', 'AIWaveTargetPatrol', 'UISetResourceTradingMinorStep',
      'AchievementErase', 'AISetStockUnitNext', 'PortraitCreate', 'DialogSetOffscreen', 'UIAlertUnit',
      'PlanetSetPlayerGroup', 'DialogItemEditValue', 'SoundLastPlayed', 'UISetMiniMapCameraFoVVisible',
      'AIGetBuildAtName', 'PlayerIsEnemy', 'Ceiling', 'AIGetNextScoutLoc', 'AIWaveGetTarget',
      'TriggerActiveCount', 'UserDataGetUpgrade', 'DialogControlHookupUnitStatus', 'PlayerSetDifficulty',
      'KillingPlayer', 'SetVisibility', 'UnitBehaviorAddPlayer', 'AIDefaultExpansion', 'DataTableSetControl',
      'TriggerAddEventGameMenuItemSelected', 'TimerWindowSetGapWidth', 'DeclareNextTown', 'UnitGetChargeUsed',
      'DialogControlHookupStandard', 'UnitStatsStart', 'MinF', 'UnitDamage', 'UIShowTextCrawl',
      'VictoryPanelSetRewardText', 'EventKeyPressed', 'UnitAbilityChangeLevel', 'AIClearAllBullies',
      'DataTableGetConversation', 'UnitOrderCount', 'DataTableSetUnitGroup', 'ConvertStringToMovieFile',
      'PortraitGetPlanetPanel', 'PlayerAddChargeRegen', 'AIIsCampaign', 'PlanetSetResearchText', 'UnitWeaponAdd',
      'TriggerAddEventPlayerAllianceChange', 'UnitWeaponPeriodRemaining', 'AIMakeAlways', 'RepeatForever',
      'DialogSetPositionRelativeToUnit', 'AIGetScout', 'TriggerAddEventPlayerAIWave', 'OrderGetTargetPosition',
      'DialogControlSetEnabled', 'AIWaveToString', 'UserDataSetGameLink', 'CreateDialogItemImage',
      'TriggerAddEventUnitAbility', 'PurchaseCategoryLastCreated', 'AIDefaultGetObjectType', 'IntLoopCurrent',
      'MercenarySetDescriptionText', 'AIGetFirstUnfinishedReq', 'SetTacticalAIRange', 'CatalogLinkReplace',
      'EventUnitInventoryItem', 'VictoryPanelAddAchievement', 'ConvertPresetToRegion', 'DataTableGetSoundLink',
      'TriggerAddEventAbortMission', 'UISetCustomMenuItemText', 'AISetFilterRange', 'UIFrameVisible',
      'DialogSetImage', 'AIAttackWaveUseGroup', 'UISetAlertTypeVisible', 'ActorScopeFromActor', 'RandomAngle',
      'TriggerQueueClear', 'AISetFilterLifeMod', 'EventMouseMovedPosXWorld', 'UnitCargoLastCreatedGroup',
      'GameIsSeedLocked', 'DialogControlGetAnchor', 'CutsceneFade', 'AIWaveRemoveUnit',
      'ConversationDataSaveStateValues', 'HelpPanelAddTip', 'AIAttackWaveAddEscortUnit', 'AIWaveUnitCount',
      'SelectMainShadowLight', 'BattleReportSetBestTimeText', 'UnitStatsStop', 'MoverSetSpeedMax',
      'WaitForTimer', 'DialogSetSubtitlePositionOverride', 'CutsceneLastCreated', 'RemoveDeathModelsinRegion',
      'CameraGetPitch', 'UIShowCinematicText', 'PlanetPanelSetBackButtonEnabled', 'UnitGroupIdle',
      'SetScreenButtonBorderImage', 'SetTintColor', 'ConversationDataStateImagePath', 'VisExploreArea',
      'PathSetSourcePoint', 'DataTableGetDoodad', 'DialogControlGetHeight', 'PathGetLineTileLength',
      'MovieAddSubTitleText', 'AIGetDifficulty', 'MakeUnitFacePoint', 'SoundLink', 'PathDestroyAll',
      'AIAttackWaveSetGatherEarlyNoReplace', 'AITimeIsPaused', 'DataTableGetString', 'SetDialogItemUnitLink',
      'ConvertPresetToConversation2', 'MercenarySetCost', 'SetDialogItemImage', 'EventMouseClickedPosXWorld',
      'EventUnitInventoryItemSlot', 'ConversationDataStateMoviePath', 'UnitSetProgressStage',
      'AIResetBullyRebuildCountsInRegion', 'TriggerAddEventBattleReportPanelSelectionChanged',
      'UserDataFieldValueCount', 'CameraShakeStop', 'BattleReportSetBonusTitle', 'AIClearStock',
      'TriggerAddEventMercenaryPanelExit', 'UnitGroupFilter', 'MaxI', 'PreloadLayout', 'DataTableGetOrder',
      'PointPathingCliffLevel', 'DialogControlGetWidth', 'cai_start', 'CinematicFade',
      'TriggerAddEventUnitResearchProgress', 'UserDataGetGameLink', 'BattleReportSetSceneText',
      'UserDataGetImageEdge', 'RemoveDoodadsinRegion', 'AIAttackWaveSetGatherPoint', 'MissileTentacleReturn',
      'DialogIsImageVisible', 'PlanetSetRewardText', 'DialogControlSetPropertyAsUnit', 'DialogItemColor',
      'UnitTypeMoveBlockersFromUnit', 'PathGetColor', 'UIGetChallengeHighScore', 'SetDialogItemTextWriteout',
      'TurnAnimationPropertiesOn', 'PortraitSetPosition', 'ConversationDataRegisterPortrait', 'IncrementReal',
      'AITechFlag', '_BB_PortraitBorderWidth', 'MakeMsgTextureVideoSetPaused', 'PurchaseGroupSetUnitLink',
      'DataTableValueType', 'PointGetFacing', 'Signal', 'ConversationDataPreloadLinesQueue', 'PortraitSetSize',
      'BoardResetPosition', 'EventPlayerEffectUsedUnitOwner', 'PointSet', 'TechTreeUnitIsAllowed',
      'DataTableGetTrigger', 'UnitSetAIOption', 'ConversationReplyGetIndex', 'UnitAbilityRemoveCooldown',
      'CameraPan', 'AbilityClass', 'UnitTypeGetCost', 'PlanetSetTooltipText', 'SetHeight',
      'TextTagShowBackground', 'DifficultyLow', 'PurchaseCategorySetPlayerGroup', 'AISetGroupScriptControlled',
      'BoardSetPosition', 'UnitValidateEffectPoint', 'PerfTestStart', 'AISetNumScouts',
      'TransmissionSourceSetStreamingAllowed', 'PerfTestGetFPS', 'PortraitGetGame', 'PathSetDestinationUnit',
      'HeightOfRegion', 'PreloadScript', 'ResearchTierCreate', 'HelpPanelEnableTechTreeButton', 'StringToText24',
      'UnitInventorySlot', 'UnitTypeAnimationLoadOverriding', 'EventKeyShift', '_CineModeStoreCheatStatus',
      'PortraitDestroy', 'UnitGetAttachmentPoint', 'WaterPause', 'ResearchItemSetMovieFilePath',
      'ObjectiveSetPrimary', 'AcquiredTarget', 'GameGetSpeedValueMinimum', 'SendActorMessageToUnit',
      'ConversationDataSimulateRun', 'UnitUnloadModel', 'PointReflect', 'PathGetVisible',
      'DataTableSetTransmissionSource', 'UserDataTypeFromReference', 'TriggerAddEventUnitRangePoint',
      'UserDataSetFixed', 'AICampaignStart', 'PlayerScoreValueGetAsInt', 'PathGetDestinationUnit',
      'DataTableClear', 'PlayerRemoveCooldown', 'DialogControlSetVisible', 'PurchaseGroupSetState',
      'ResearchCategoryLastCreated', 'SetCinematicTransitionStyle', 'VictoryPanelSetMissionText', 'AITechCount',
      'PlanetSetPlanetModelLink', 'RefSetRefreshName', 'ObjectiveGetState', 'TriggerAddEventTriggerSkipped',
      'AIGetNextUnusedTownSlot', 'OrderGetAbilityCommand', 'StringToText2', 'UnitRallyPointTargetUnit',
      'DialogControlRemoveAllItems', 'ActorLookAtTypeStart', 'TriggerAddEventUnitRange', 'AttachSetBearingsFrom',
      'ActorTextureGroupPush', 'SetScreenButtonFlashingBorderImage', 'SetRotationFrom', 'HelpPanelAddHint',
      'PointOffsetTowardsPoint', '_CineModeRestoreCheatStatus', 'BattleReportSetResearchText', 'RefSetFromActor',
      'CatalogEntryIsValid', 'DialogSetTitle', 'PreloadImage', 'PreloadScene', 'BattleReportSetButtonText',
      'ActorTextureGroupRemoveGlobal', 'CutsceneCreate', 'AchievementPercentText', 'SetDialogItemTooltip',
      'EventUnitDamageEffect', 'AIPathingCostUnit', 'GameRemoveChargeUsed', 'WaitForCondition',
      'ModelAnimationUnload', 'ConvertPresetToConversation', 'UnitWeaponGet', 'CriticalSection',
      'AISetMinimumBullyCount', 'DataTableSetDialog', 'CreepSetSpeed', 'BattleReportSetResearchTitle',
      'AIWaveTargetClearWaypoints', 'SetDialogItemDesaturated', 'UnitGroupFilterPlane', 'ActorFrom',
      'ConversationDataChoiceSetState', 'TextReplaceWord', 'AIBestTargetPoint', 'UnitAddOnChild',
      'CameraUseHeightDisplacement', 'UISetButtonHighlighted', 'DataTableSetTimer', 'IntToText',
      'SetDialogItemAchievement', 'UnitGetCooldown', 'DataTableSetAbilCmd', 'TriggerAddEventCheatUsed',
      'AIAttackWaveSetTargetUnitPoint', 'RefNotify', 'MakeMsgRefSetFromRequest', 'UserDataSetColor',
      'PlanetSetPrimaryObjectiveTitle', 'ActorSendAsText', 'ModelEventSuppress', 'PlanetSetContactTitle',
      'TransmissionSourceFromUnitType', 'SetBossBarCurrentValue', 'AIGetMineralAmountLeft',
      'MakeMsgAnimGroupRemove', 'UIErrorMessage', 'DialogControlGetItemCount', 'UnitIsInvulnerable', 'SetFacing',
      'AIWaveMerge', 'DialogControlSetObservedType', 'ModI', 'DialogGetWidth', 'GameSetSpeedValue',
      'PlayerCreateEffectUnit', 'PointWithZOffset', 'UnitGroupRemoveUnitGroup', 'AISetStockTown',
      'MercenaryGetSelected', 'PointFromPositionAndAngle', 'PlanetSetDescriptionText',
      'PurchaseSetSelectedPurchaseCategory', 'CharacterSheetPanelSetDescriptionText',
      'PurchaseItemSetPlayerGroup', 'ActorScopeLastCreated', 'CreatePingFacingAngle', 'SoundChannelMute',
      'UserDataSaveType', 'UnitClearInfoText', 'DataTableGetWave', 'UnitAddChargeUsed', 'TransmissionClear',
      'UnitAbilityAddChargeUsed', 'GameIsExaminable', 'SoundSetPaused', 'AIAttackWaveAddEscortType',
      'DataTableSetInt', 'MercenarySetCostText', 'PlayerStatus', 'CreateUnitsAtPoint2',
      'CutsceneSetGlobalFilter', 'SetScaleAbsolute', 'CreateUnitsWithDefaultFacing', 'ActorTextureGroupPop',
      'EventUnitPowerupUnit', 'MercenaryPurchase', 'AIGetTownLocation', 'PreloadSoundtrack', 'UnitInventoryUnit',
      'SetDialogItemMaximumValue', 'AIIsSuicideUnit', 'FormatTipTitle', 'PlanetSetContactName',
      'BattleReportCreate', 'MakeMsgTextureVideoSetFrame', 'PlayerGroupActive', 'CameraSetBounds',
      'DataTableSetText', 'PingIsVisible', 'TriggerAddEventSaveGameDone', 'ConversationDataResetStateValues',
      'CatalogReferenceCount', 'DialogDestroy', 'EventDialogControlEventType', 'Pow2', 'UnitRallyPointCount',
      'SetBossBarBoss', 'HelpPanelLastCreatedHelpItem', 'ReplaceUnit', 'ScreenButtonDialog', 'EnvironmentShow',
      'UnitGroupCenterOfGroup', 'TimerWindowResetPosition', 'SetDialogItemRotation', 'CameraGetTarget',
      'DataTableGetTransmissionSource', 'OrderTargetingUnit', 'UnitTransport', 'PingSetRotation',
      'SetDialogItemEditorValue', 'BoardItemSetProgressShow', 'UserDataInstanceFromReference',
      'DialogControlGetDialog', 'GameMapName', 'AIWaveInfo', 'EventPlayerEffectUsedAmountInt',
      'CameraShakeStart', 'ResearchItemSetRecentlyPurchased', 'UnitCheckAbilCmdState', 'TextTagSetTextAlignment',
      'AIWaveSetType', 'ConvertStringToCatalogScope', 'UnitWeaponSpeedMultiplier', 'ActorRegionSendSimple',
      'CinematicDataStop', 'PingGetColor', 'AIWaveGetTimeSinceCombat', 'AnimClearAllBut', 'AIIsIgnoredByWave',
      'DialogControlIsEnabled', 'RescueUnit2', 'HelpPanelEnableTechGlossaryButton', 'MakeMsgAnimBracketStop',
      'TextureDumpDB', 'SetPositionH', 'AISetSpecificRebuildCount', 'TriggerQueuePause', 'AnimSetCompletion',
      'MultiplyScale', 'ConversationCreate', 'ConvertBooleanToString', 'PingSetDuration',
      'ConvertPresetToInteger', 'UnitBehaviorGetChargeUsed', 'UISetResourceTradingMajorStep',
      'ConversationDataSaveNodeState', 'UnitTypePlacementFromUnit', 'MercenarySetRecentlyPurchased',
      'ClearAnimationOnDoodadsInRegion', 'PortraitSetBorderTexture', 'TransmissionLastSent', 'DataTableGetFixed',
      'PortraitVisible', 'ConversationDataStop', 'StringToAbilCmd', 'PlanetSetMissionName',
      'TriggerAddEventCameraMove', 'UnitCargoLastCreated', 'TriggerAddEventUnitChangeOwner', 'MoverStop',
      'UserDataGetModel', 'TriggerDebugSetTypeFile', 'ChangeUnitDamage', 'Create', 'ClearAnimation',
      'PingGetDuration', 'ActorScopeRefGet', 'ActorScopeRefSet', 'ActorRefGet', 'ActorRefSet', 'DoodadFromId',
      'BattleReportSetWorldText', 'BattleReportSetObjectiveTitle', 'BattleReportSetObjectiveText',
      'BattleReportSetAchievementTitle', 'BoardTitleShow', 'BoardTitleSetText', 'BoardTitleSetColor',
      'BoardTitleSetIcon', 'BoardTitleSetAlignment', 'BoardTitleSetClickable', 'CameraInfoFromId',
      'TriggerAddEventCutsceneConversationLine', 'PathingModify', 'PathingUpdate', 'PathingReset',
      'GameSetAbsoluteTimeRemaining', 'GameGetAbsoluteTimeRemaining', 'GameSetAbsoluteTimeRemainingPaused',
      'GameGetAbsoluteTimeRemainingPaused', 'GameCheatIsAllowed', 'GameDataIsFullyDownloaded', 'IntLoopBegin',
      'IntLoopStep', 'IntLoopDone', 'IntLoopEnd', 'PlayerGroupLoopBegin', 'PlayerGroupLoopStep',
      'PlayerGroupLoopDone', 'PlayerGroupLoopEnd', 'UnitGroupLoopBegin', 'UnitGroupLoopStep',
      'UnitGroupLoopDone', 'UnitGroupLoopEnd', 'Marker', 'MarkerCastingPlayer', 'MarkerCastingUnit',
      'MarkerSetCastingPlayer', 'MarkerGetCastingPlayer', 'MarkerSetCastingUnit', 'MarkerGetCastingUnit',
      'MarkerSetMatchFlag', 'MarkerGetMatchFlag', 'MarkerSetMismatchFlag', 'MarkerGetMismatchFlag',
      'MercenarySetTooltipText', 'TriggerAddEventMovieStarted', 'TriggerAddEventMovieFinished',
      'OrderSetAbilityCommand', 'OrderSetPlayer', 'OrderSetTargetPlacement', 'OrderSetTargetPoint',
      'OrderSetTargetUnit', 'OrderSetTargetPassenger', 'OrderSetFlag', 'PlayerModifyPropertyFixed',
      'PlayerGetPropertyFixed', 'PlayerColorName', 'PlayerBeaconClearTarget', 'PlayerBeaconIsAutoCast',
      'PlayerBeaconIsFromUser', 'PlayerBeaconIsSet', 'PlayerBeaconGetTargetPoint', 'PlayerBeaconGetTargetUnit',
      'PlayerBeaconSetAutoCast', 'PlayerBeaconSetTargetPoint', 'PlayerBeaconSetTargetUnit', 'PlayerBeaconAlert',
      'PlayerBeaconGetNumAllies', 'PlayerBeaconGetAllyPlayerId', 'PlayerBeaconGetAllyText',
      'PlayerBeaconSelectDropoff', 'PlayerBeaconRequestedMinerals', 'PlayerBeaconRequestedVespene',
      'PlayerBeaconSetCustomBuildCount', 'PlayerBeaconSetCustomBeaconCount', 'PlayerBeaconSetCustomBuildInfo',
      'PlayerBeaconSetCustomBeaconInfo', 'PlayerBeaconGetCurrentBuild', 'PointFromId', 'PointsInRange',
      'RegionFromId', 'RegionSetOffset', 'RegionGetOffset', 'ResearchCategorySetPlayerGroup',
      'ResearchCategorySetSlot', 'ResearchTierSetPlayerGroup', 'ResearchTierSetSlot', 'ResearchItemDestroyAll',
      'ResearchItemSetPlayerGroup', 'ResearchItemSetSlot', 'SoundAttachUnit', 'TextExpressionSetToken',
      'TextExpressionAssemble', 'TechTreeBehaviorProducedAbilCmd', 'TechTreeBehaviorProducedAbilCmdCount',
      'TechTreeRequirementsEnabled', 'TechTreeUnitAliasCount', 'TechTreeUnitCountEx',
      'TechTreeUnitProducedAbilCmd', 'TechTreeUnitProducedAbilCmdCount', 'TechTreeUnitProducesUnit',
      'TechTreeUnitProducesUnitCount', 'TechTreeUnitProducesUpgrade', 'TechTreeUnitProducesUpgradeCount',
      'TechTreeUpgradeProducedAbilCmd', 'TechTreeUpgradeProducedAbilCmdCount', 'TriggerCreate', 'TriggerFind',
      'TriggerDestroy', 'TriggerResetCounts', 'TriggerQueueEnter', 'TriggerQueueExit', 'TriggerSkippableEnd',
      'UnitFromId', 'UnitResetTeamColorIndex', 'UnitSetPropertyInt', 'UnitGetPropertyInt',
      'UnitAbilityEffectInstantGetRange', 'UnitMarker', 'UnitMarkerAdd', 'UnitMarkerCount', 'UnitMarkerRemove',
      'UnitOrderHasAbil', 'UnitIsHarvesting', 'UnitWeaponRange', 'UnitWeaponsPlaneTest', 'UnitFilter',
      'UnitFilterStr', 'UnitGroupFromId', 'UnitGroupFilterThreat', 'UnitGroupTestPlane', 'UnitGroupNearestUnit',
      'UnitRefFromUnit', 'UnitRefFromVariable', 'UnitRefToUnit', 'UIGameMenuItemVisible',
      'UICustomMenuItemVisible',
  ),
);