<?php
/*************************************************************************************
 * jass.php
 * -------
 * Author: Rasmus Abrahamsen (ralleab@gmail.com)
 * Copyright: (c) 2011 Rasmus Abrahamsen (http://www.hiveworkshop.com)
 * Release Version: 1
 * Date Started: 2011/14/09
 *
 * JASS language file for GeSHi.
 *
 *************************************************************************************
 *
 *   This file is part of GeSHi.
 *
 *   GeSHi is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   GeSHi is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with GeSHi; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 ************************************************************************************/

/*
1: jass_keyword
2: jass_primitiveType
3: jass_nativeType
4: jass_constantNativeFunction
5: jass_constant
6: jass_nativeFunction
7: jass_bjConstant
8: jass_bjVariable
9: jass_bjFunction
*/

$language_data = array (
  'LANG_NAME' => 'vJASS',
  'COMMENT_SINGLE' => array(
    1 => '//!',
    2 => "//",
    ),
  'COMMENT_MULTI' => array('/*' => '*/'),
  // 'COMMENT_REGEXP' => array(2 => "/\[(=*)\[.*?\]\1\]/s"),
  'CASE_KEYWORDS' => GESHI_CAPS_NO_CHANGE,
  'QUOTEMARKS' => array("'", '"'),
  'ESCAPE_CHAR' => '',
  'ESCAPE_REGEXP' => array(
    //Simple Single Char Escapes
    1 => "#\\\\[\\\\abfnrtv\'\"]#i",
    //Octal Char Specs
    2 => '#\\\\\d{1,3}#'
    ),
  'NUMBERS' =>
    GESHI_NUMBER_INT_BASIC | GESHI_NUMBER_INT_CSTYLE | GESHI_NUMBER_HEX_PREFIX |
    GESHI_NUMBER_FLT_NONSCI | GESHI_NUMBER_FLT_NONSCI_F |
    GESHI_NUMBER_FLT_SCI_SHORT | GESHI_NUMBER_FLT_SCI_ZERO,
  'KEYWORDS' => array(
    1 => array( // jass_keyword
      'function', 'endfunction', 'takes', 'returns', 'return', 'call', 'set', 'local', 'loop', 'endloop',
      'exitwhen', 'not', 'and', 'or', 'if', 'else', 'elseif' , 'endif', 'then', 'requires' , 'struct', 'endstruct',
      'method', 'endmethod', 'scope', 'endscope', 'library', 'endlibrary', 'globals', 'endglobals', 'public',
      'protected', 'private', 'constant', 'uses', 'module', 'endmodule', 'static', 'extends', 'readonly',
      'implement'
    ),
    2 => array( // jass_primitiveType
      'thistype' , 'integer', 'real', 'boolean', 'array', 'nothing', 'false', 'true', 'null'
    ),
    3 => array( // jass_nativeType
      'event', 'player', 'widget', 'unit', 'destructable', 'item', 'ability', 'buff', 'force', 'group', 'trigger',
      'triggercondition', 'triggeraction', 'timer', 'location', 'region', 'rect', 'boolexpr', 'sound',
      'conditionfunc', 'filterfunc', 'unitpool', 'itempool', 'race', 'alliancetype', 'racepreference', 'gamestate',
      'igamestate', 'fgamestate', 'playerstate', 'playerscore', 'playergameresult', 'unitstate', 'aidifficulty',
      'eventid', 'gameevent', 'playerevent', 'playerunitevent', 'unitevent', 'limitop', 'widgetevent',
      'dialogevent', 'unittype', 'gamespeed', 'gamedifficulty', 'gametype', 'mapflag', 'mapvisibility',
      'mapsetting', 'mapdensity', 'mapcontrol', 'playerslotstate', 'volumegroup', 'camerafield', 'camerasetup',
      'playercolor', 'placement', 'startlocprio', 'raritycontrol', 'blendmode', 'texmapflags', 'effect',
      'effecttype', 'weathereffect', 'terraindeformation', 'fogstate', 'fogmodifier', 'dialog', 'button', 'quest',
      'questitem', 'defeatcondition', 'timerdialog', 'leaderboard', 'multiboard', 'multiboarditem', 'trackable',
      'gamecache', 'version', 'itemtype', 'texttag', 'attacktype', 'damagetype', 'weapontype', 'soundtype',
      'lightning', 'pathingtype', 'image', 'ubersplat'
    ),
    4 => array( // jass_constantNativeFunction
      'ConvertRace', 'ConvertAllianceType', 'ConvertRacePref', 'ConvertIGameState', 'ConvertFGameState',
      'ConvertPlayerState', 'ConvertPlayerScore', 'ConvertPlayerGameResult', 'ConvertUnitState',
      'ConvertAIDifficulty', 'ConvertGameEvent', 'ConvertPlayerEvent', 'ConvertPlayerUnitEvent',
      'ConvertWidgetEvent', 'ConvertDialogEvent', 'ConvertUnitEvent', 'ConvertLimitOp', 'ConvertUnitType',
      'ConvertGameSpeed', 'ConvertPlacement', 'ConvertStartLocPrio', 'ConvertGameDifficulty', 'ConvertGameType',
      'ConvertMapFlag', 'ConvertMapVisibility', 'ConvertMapSetting', 'ConvertMapDensity', 'ConvertMapControl',
      'ConvertPlayerColor', 'ConvertPlayerSlotState', 'ConvertVolumeGroup', 'ConvertCameraField',
      'ConvertBlendMode', 'ConvertRarityControl', 'ConvertTexMapFlags', 'ConvertFogState', 'ConvertEffectType',
      'ConvertVersion', 'ConvertItemType', 'ConvertAttackType', 'ConvertDamageType', 'ConvertWeaponType',
      'ConvertSoundType', 'ConvertPathingType', 'OrderId', 'OrderId', 'UnitId', 'UnitId', 'AbilityId', 'AbilityId',
      'GetObjectName', 'GetGamePlacement', 'GetGameSpeed', 'GetGameDifficulty', 'GetResourceDensity',
      'GetCreatureDensity', 'GetStartLocationX', 'GetStartLocationY', 'GetStartLocationLoc', 'GetFilterUnit',
      'GetEnumUnit', 'GetFilterDestructable', 'GetEnumDestructable', 'GetFilterItem', 'GetEnumItem',
      'GetFilterPlayer', 'GetEnumPlayer', 'GetTriggeringTrigger', 'GetTriggerEventId', 'GetTriggerEvalCount',
      'GetTriggerExecCount', 'GetEventGameState', 'GetWinningPlayer', 'GetTriggeringRegion', 'GetEnteringUnit',
      'GetLeavingUnit', 'GetTriggeringTrackable', 'GetClickedButton', 'GetClickedDialog',
      'GetTournamentFinishSoonTimeRemaining', 'GetTournamentFinishNowRule', 'GetTournamentFinishNowPlayer',
      'GetTournamentScore', 'GetSaveBasicFilename', 'GetTriggerPlayer', 'GetLevelingUnit', 'GetLearningUnit',
      'GetLearnedSkill', 'GetLearnedSkillLevel', 'GetRevivableUnit', 'GetRevivingUnit', 'GetAttacker',
      'GetRescuer', 'GetDyingUnit', 'GetKillingUnit', 'GetDecayingUnit', 'GetConstructingStructure',
      'GetCancelledStructure', 'GetConstructedStructure', 'GetResearchingUnit', 'GetResearched',
      'GetTrainedUnitType', 'GetTrainedUnit', 'GetDetectedUnit', 'GetSummoningUnit', 'GetSummonedUnit',
      'GetTransportUnit', 'GetLoadedUnit', 'GetSellingUnit', 'GetSoldUnit', 'GetBuyingUnit', 'GetSoldItem',
      'GetChangingUnit', 'GetChangingUnitPrevOwner', 'GetManipulatingUnit', 'GetManipulatedItem', 'GetOrderedUnit',
      'GetIssuedOrderId', 'GetOrderPointX', 'GetOrderPointY', 'GetOrderPointLoc', 'GetOrderTarget',
      'GetOrderTargetDestructable', 'GetOrderTargetItem', 'GetOrderTargetUnit', 'GetSpellAbilityUnit',
      'GetSpellAbilityId', 'GetSpellAbility', 'GetSpellTargetLoc', 'GetSpellTargetDestructable',
      'GetSpellTargetItem', 'GetSpellTargetUnit', 'GetEventPlayerState', 'GetEventPlayerChatString',
      'GetEventPlayerChatStringMatched', 'GetTriggerUnit', 'GetEventUnitState', 'GetEventDamage',
      'GetEventDamageSource', 'GetEventDetectingPlayer', 'GetEventTargetUnit', 'GetTriggerWidget', 'GetItemName',
      'GetHeroLevel', 'GetUnitLevel', 'GetUnitX', 'GetUnitY', 'GetUnitLoc', 'GetUnitFacing', 'GetUnitMoveSpeed',
      'GetUnitDefaultMoveSpeed', 'GetUnitState', 'GetOwningPlayer', 'GetUnitTypeId', 'GetUnitRace', 'GetUnitName',
      'GetUnitFoodUsed', 'GetUnitFoodMade', 'GetFoodMade', 'GetFoodUsed', 'GetUnitRallyPoint', 'GetUnitRallyUnit',
      'GetUnitRallyDestructable', 'IsUnitInGroup', 'IsUnitInForce', 'IsUnitOwnedByPlayer', 'IsUnitAlly',
      'IsUnitEnemy', 'IsUnitVisible', 'IsUnitDetected', 'IsUnitInvisible', 'IsUnitFogged', 'IsUnitMasked',
      'IsUnitSelected', 'IsUnitRace', 'IsUnitType', 'IsUnit', 'IsUnitInRange', 'IsUnitInRangeXY',
      'IsUnitInRangeLoc', 'IsUnitHidden', 'IsUnitIllusion', 'IsUnitInTransport', 'IsUnitLoaded', 'IsHeroUnitId',
      'IsUnitIdType', 'Player', 'GetLocalPlayer', 'IsPlayerAlly', 'IsPlayerEnemy', 'IsPlayerInForce',
      'IsPlayerObserver', 'IsVisibleToPlayer', 'IsLocationVisibleToPlayer', 'IsFoggedToPlayer',
      'IsLocationFoggedToPlayer', 'IsMaskedToPlayer', 'IsLocationMaskedToPlayer', 'GetPlayerRace', 'GetPlayerId',
      'GetPlayerUnitCount', 'GetPlayerTypedUnitCount', 'GetPlayerStructureCount', 'GetPlayerState',
      'GetPlayerScore', 'GetPlayerAlliance', 'GetPlayerHandicap', 'GetPlayerHandicapXP', 'SetPlayerHandicap',
      'SetPlayerHandicapXP', 'SetPlayerTechMaxAllowed', 'GetPlayerTechMaxAllowed', 'AddPlayerTechResearched',
      'SetPlayerTechResearched', 'GetPlayerTechResearched', 'GetPlayerTechCount', 'GetFloatGameState',
      'GetIntegerGameState', 'GetCameraBoundMinX', 'GetCameraBoundMinY', 'GetCameraBoundMaxX',
      'GetCameraBoundMaxY', 'GetCameraField', 'GetCameraTargetPositionX', 'GetCameraTargetPositionY',
      'GetCameraTargetPositionZ', 'GetCameraTargetPositionLoc', 'GetCameraEyePositionX', 'GetCameraEyePositionY',
      'GetCameraEyePositionZ', 'GetCameraEyePositionLoc'
    ),
    5 => array( // jass_constant
      'FALSE', 'TRUE', 'JASS_MAX_ARRAY_SIZE', 'PLAYER_NEUTRAL_PASSIVE', 'PLAYER_NEUTRAL_AGGRESSIVE',
      'PLAYER_COLOR_RED', 'PLAYER_COLOR_BLUE', 'PLAYER_COLOR_CYAN', 'PLAYER_COLOR_PURPLE', 'PLAYER_COLOR_YELLOW',
      'PLAYER_COLOR_ORANGE', 'PLAYER_COLOR_GREEN', 'PLAYER_COLOR_PINK', 'PLAYER_COLOR_LIGHT_GRAY',
      'PLAYER_COLOR_LIGHT_BLUE', 'PLAYER_COLOR_AQUA', 'PLAYER_COLOR_BROWN', 'RACE_HUMAN', 'RACE_ORC',
      'RACE_UNDEAD', 'RACE_NIGHTELF', 'RACE_DEMON', 'RACE_OTHER', 'PLAYER_GAME_RESULT_VICTORY',
      'PLAYER_GAME_RESULT_DEFEAT', 'PLAYER_GAME_RESULT_TIE', 'PLAYER_GAME_RESULT_NEUTRAL', 'ALLIANCE_PASSIVE',
      'ALLIANCE_HELP_REQUEST', 'ALLIANCE_HELP_RESPONSE', 'ALLIANCE_SHARED_XP', 'ALLIANCE_SHARED_SPELLS',
      'ALLIANCE_SHARED_VISION', 'ALLIANCE_SHARED_CONTROL', 'ALLIANCE_SHARED_ADVANCED_CONTROL',
      'ALLIANCE_RESCUABLE', 'ALLIANCE_SHARED_VISION_FORCED', 'VERSION_REIGN_OF_CHAOS', 'VERSION_FROZEN_THRONE',
      'ATTACK_TYPE_NORMAL', 'ATTACK_TYPE_MELEE', 'ATTACK_TYPE_PIERCE', 'ATTACK_TYPE_SIEGE', 'ATTACK_TYPE_MAGIC',
      'ATTACK_TYPE_CHAOS', 'ATTACK_TYPE_HERO', 'DAMAGE_TYPE_UNKNOWN', 'DAMAGE_TYPE_NORMAL', 'DAMAGE_TYPE_ENHANCED',
      'DAMAGE_TYPE_FIRE', 'DAMAGE_TYPE_COLD', 'DAMAGE_TYPE_LIGHTNING', 'DAMAGE_TYPE_POISON', 'DAMAGE_TYPE_DISEASE',
      'DAMAGE_TYPE_DIVINE', 'DAMAGE_TYPE_MAGIC', 'DAMAGE_TYPE_SONIC', 'DAMAGE_TYPE_ACID', 'DAMAGE_TYPE_FORCE',
      'DAMAGE_TYPE_DEATH', 'DAMAGE_TYPE_MIND', 'DAMAGE_TYPE_PLANT', 'DAMAGE_TYPE_DEFENSIVE',
      'DAMAGE_TYPE_DEMOLITION', 'DAMAGE_TYPE_SLOW_POISON', 'DAMAGE_TYPE_SPIRIT_LINK', 'DAMAGE_TYPE_SHADOW_STRIKE',
      'DAMAGE_TYPE_UNIVERSAL', 'WEAPON_TYPE_WHOKNOWS', 'WEAPON_TYPE_METAL_LIGHT_CHOP',
      'WEAPON_TYPE_METAL_MEDIUM_CHOP', 'WEAPON_TYPE_METAL_HEAVY_CHOP', 'WEAPON_TYPE_METAL_LIGHT_SLICE',
      'WEAPON_TYPE_METAL_MEDIUM_SLICE', 'WEAPON_TYPE_METAL_HEAVY_SLICE', 'WEAPON_TYPE_METAL_MEDIUM_BASH',
      'WEAPON_TYPE_METAL_HEAVY_BASH', 'WEAPON_TYPE_METAL_MEDIUM_STAB', 'WEAPON_TYPE_METAL_HEAVY_STAB',
      'WEAPON_TYPE_WOOD_LIGHT_SLICE', 'WEAPON_TYPE_WOOD_MEDIUM_SLICE', 'WEAPON_TYPE_WOOD_HEAVY_SLICE',
      'WEAPON_TYPE_WOOD_LIGHT_BASH', 'WEAPON_TYPE_WOOD_MEDIUM_BASH', 'WEAPON_TYPE_WOOD_HEAVY_BASH',
      'WEAPON_TYPE_WOOD_LIGHT_STAB', 'WEAPON_TYPE_WOOD_MEDIUM_STAB', 'WEAPON_TYPE_CLAW_LIGHT_SLICE',
      'WEAPON_TYPE_CLAW_MEDIUM_SLICE', 'WEAPON_TYPE_CLAW_HEAVY_SLICE', 'WEAPON_TYPE_AXE_MEDIUM_CHOP',
      'WEAPON_TYPE_ROCK_HEAVY_BASH', 'PATHING_TYPE_ANY', 'PATHING_TYPE_WALKABILITY', 'PATHING_TYPE_FLYABILITY',
      'PATHING_TYPE_BUILDABILITY', 'PATHING_TYPE_PEONHARVESTPATHING', 'PATHING_TYPE_BLIGHTPATHING',
      'PATHING_TYPE_FLOATABILITY', 'PATHING_TYPE_AMPHIBIOUSPATHING', 'RACE_PREF_HUMAN', 'RACE_PREF_ORC',
      'RACE_PREF_NIGHTELF', 'RACE_PREF_UNDEAD', 'RACE_PREF_DEMON', 'RACE_PREF_RANDOM', 'RACE_PREF_USER_SELECTABLE',
      'MAP_CONTROL_USER', 'MAP_CONTROL_COMPUTER', 'MAP_CONTROL_RESCUABLE', 'MAP_CONTROL_NEUTRAL',
      'MAP_CONTROL_CREEP', 'MAP_CONTROL_NONE', 'GAME_TYPE_MELEE', 'GAME_TYPE_FFA', 'GAME_TYPE_USE_MAP_SETTINGS',
      'GAME_TYPE_BLIZ', 'GAME_TYPE_ONE_ON_ONE', 'GAME_TYPE_TWO_TEAM_PLAY', 'GAME_TYPE_THREE_TEAM_PLAY',
      'GAME_TYPE_FOUR_TEAM_PLAY', 'MAP_FOG_HIDE_TERRAIN', 'MAP_FOG_MAP_EXPLORED', 'MAP_FOG_ALWAYS_VISIBLE',
      'MAP_USE_HANDICAPS', 'MAP_OBSERVERS', 'MAP_OBSERVERS_ON_DEATH', 'MAP_FIXED_COLORS',
      'MAP_LOCK_RESOURCE_TRADING', 'MAP_RESOURCE_TRADING_ALLIES_ONLY', 'MAP_LOCK_ALLIANCE_CHANGES',
      'MAP_ALLIANCE_CHANGES_HIDDEN', 'MAP_CHEATS', 'MAP_CHEATS_HIDDEN', 'MAP_LOCK_SPEED', 'MAP_LOCK_RANDOM_SEED',
      'MAP_SHARED_ADVANCED_CONTROL', 'MAP_RANDOM_HERO', 'MAP_RANDOM_RACES', 'MAP_RELOADED', 'MAP_PLACEMENT_RANDOM',
      'MAP_PLACEMENT_FIXED', 'MAP_PLACEMENT_USE_MAP_SETTINGS', 'MAP_PLACEMENT_TEAMS_TOGETHER', 'MAP_LOC_PRIO_LOW',
      'MAP_LOC_PRIO_HIGH', 'MAP_LOC_PRIO_NOT', 'MAP_DENSITY_NONE', 'MAP_DENSITY_LIGHT', 'MAP_DENSITY_MEDIUM',
      'MAP_DENSITY_HEAVY', 'MAP_DIFFICULTY_EASY', 'MAP_DIFFICULTY_NORMAL', 'MAP_DIFFICULTY_HARD',
      'MAP_DIFFICULTY_INSANE', 'MAP_SPEED_SLOWEST', 'MAP_SPEED_SLOW', 'MAP_SPEED_NORMAL', 'MAP_SPEED_FAST',
      'MAP_SPEED_FASTEST', 'PLAYER_SLOT_STATE_EMPTY', 'PLAYER_SLOT_STATE_PLAYING', 'PLAYER_SLOT_STATE_LEFT',
      'SOUND_VOLUMEGROUP_UNITMOVEMENT', 'SOUND_VOLUMEGROUP_UNITSOUNDS', 'SOUND_VOLUMEGROUP_COMBAT',
      'SOUND_VOLUMEGROUP_SPELLS', 'SOUND_VOLUMEGROUP_UI', 'SOUND_VOLUMEGROUP_MUSIC',
      'SOUND_VOLUMEGROUP_AMBIENTSOUNDS', 'SOUND_VOLUMEGROUP_FIRE', 'GAME_STATE_DIVINE_INTERVENTION',
      'GAME_STATE_DISCONNECTED', 'GAME_STATE_TIME_OF_DAY', 'PLAYER_STATE_GAME_RESULT',
      'PLAYER_STATE_RESOURCE_GOLD', 'PLAYER_STATE_RESOURCE_LUMBER', 'PLAYER_STATE_RESOURCE_HERO_TOKENS',
      'PLAYER_STATE_RESOURCE_FOOD_CAP', 'PLAYER_STATE_RESOURCE_FOOD_USED', 'PLAYER_STATE_FOOD_CAP_CEILING',
      'PLAYER_STATE_GIVES_BOUNTY', 'PLAYER_STATE_ALLIED_VICTORY', 'PLAYER_STATE_PLACED',
      'PLAYER_STATE_OBSERVER_ON_DEATH', 'PLAYER_STATE_OBSERVER', 'PLAYER_STATE_UNFOLLOWABLE',
      'PLAYER_STATE_GOLD_UPKEEP_RATE', 'PLAYER_STATE_LUMBER_UPKEEP_RATE', 'PLAYER_STATE_GOLD_GATHERED',
      'PLAYER_STATE_LUMBER_GATHERED', 'PLAYER_STATE_NO_CREEP_SLEEP', 'UNIT_STATE_LIFE', 'UNIT_STATE_MAX_LIFE',
      'UNIT_STATE_MANA', 'UNIT_STATE_MAX_MANA', 'AI_DIFFICULTY_NEWBIE', 'AI_DIFFICULTY_NORMAL',
      'AI_DIFFICULTY_INSANE', 'PLAYER_SCORE_UNITS_TRAINED', 'PLAYER_SCORE_UNITS_KILLED',
      'PLAYER_SCORE_STRUCT_BUILT', 'PLAYER_SCORE_STRUCT_RAZED', 'PLAYER_SCORE_TECH_PERCENT',
      'PLAYER_SCORE_FOOD_MAXPROD', 'PLAYER_SCORE_FOOD_MAXUSED', 'PLAYER_SCORE_HEROES_KILLED',
      'PLAYER_SCORE_ITEMS_GAINED', 'PLAYER_SCORE_MERCS_HIRED', 'PLAYER_SCORE_GOLD_MINED_TOTAL',
      'PLAYER_SCORE_GOLD_MINED_UPKEEP', 'PLAYER_SCORE_GOLD_LOST_UPKEEP', 'PLAYER_SCORE_GOLD_LOST_TAX',
      'PLAYER_SCORE_GOLD_GIVEN', 'PLAYER_SCORE_GOLD_RECEIVED', 'PLAYER_SCORE_LUMBER_TOTAL',
      'PLAYER_SCORE_LUMBER_LOST_UPKEEP', 'PLAYER_SCORE_LUMBER_LOST_TAX', 'PLAYER_SCORE_LUMBER_GIVEN',
      'PLAYER_SCORE_LUMBER_RECEIVED', 'PLAYER_SCORE_UNIT_TOTAL', 'PLAYER_SCORE_HERO_TOTAL',
      'PLAYER_SCORE_RESOURCE_TOTAL', 'PLAYER_SCORE_TOTAL', 'EVENT_GAME_VICTORY', 'EVENT_GAME_END_LEVEL',
      'EVENT_GAME_VARIABLE_LIMIT', 'EVENT_GAME_STATE_LIMIT', 'EVENT_GAME_TIMER_EXPIRED', 'EVENT_GAME_ENTER_REGION',
      'EVENT_GAME_LEAVE_REGION', 'EVENT_GAME_TRACKABLE_HIT', 'EVENT_GAME_TRACKABLE_TRACK', 'EVENT_GAME_SHOW_SKILL',
      'EVENT_GAME_BUILD_SUBMENU', 'EVENT_PLAYER_STATE_LIMIT', 'EVENT_PLAYER_ALLIANCE_CHANGED',
      'EVENT_PLAYER_DEFEAT', 'EVENT_PLAYER_VICTORY', 'EVENT_PLAYER_LEAVE', 'EVENT_PLAYER_CHAT',
      'EVENT_PLAYER_END_CINEMATIC', 'EVENT_PLAYER_UNIT_ATTACKED', 'EVENT_PLAYER_UNIT_RESCUED',
      'EVENT_PLAYER_UNIT_DEATH', 'EVENT_PLAYER_UNIT_DECAY', 'EVENT_PLAYER_UNIT_DETECTED',
      'EVENT_PLAYER_UNIT_HIDDEN', 'EVENT_PLAYER_UNIT_SELECTED', 'EVENT_PLAYER_UNIT_DESELECTED',
      'EVENT_PLAYER_UNIT_CONSTRUCT_START', 'EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL',
      'EVENT_PLAYER_UNIT_CONSTRUCT_FINISH', 'EVENT_PLAYER_UNIT_UPGRADE_START', 'EVENT_PLAYER_UNIT_UPGRADE_CANCEL',
      'EVENT_PLAYER_UNIT_UPGRADE_FINISH', 'EVENT_PLAYER_UNIT_TRAIN_START', 'EVENT_PLAYER_UNIT_TRAIN_CANCEL',
      'EVENT_PLAYER_UNIT_TRAIN_FINISH', 'EVENT_PLAYER_UNIT_RESEARCH_START', 'EVENT_PLAYER_UNIT_RESEARCH_CANCEL',
      'EVENT_PLAYER_UNIT_RESEARCH_FINISH', 'EVENT_PLAYER_UNIT_ISSUED_ORDER',
      'EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER', 'EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER',
      'EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER', 'EVENT_PLAYER_HERO_LEVEL', 'EVENT_PLAYER_HERO_SKILL',
      'EVENT_PLAYER_HERO_REVIVABLE', 'EVENT_PLAYER_HERO_REVIVE_START', 'EVENT_PLAYER_HERO_REVIVE_CANCEL',
      'EVENT_PLAYER_HERO_REVIVE_FINISH', 'EVENT_PLAYER_UNIT_SUMMON', 'EVENT_PLAYER_UNIT_DROP_ITEM',
      'EVENT_PLAYER_UNIT_PICKUP_ITEM', 'EVENT_PLAYER_UNIT_USE_ITEM', 'EVENT_PLAYER_UNIT_LOADED',
      'EVENT_UNIT_DAMAGED', 'EVENT_UNIT_DEATH', 'EVENT_UNIT_DECAY', 'EVENT_UNIT_DETECTED', 'EVENT_UNIT_HIDDEN',
      'EVENT_UNIT_SELECTED', 'EVENT_UNIT_DESELECTED', 'EVENT_UNIT_STATE_LIMIT', 'EVENT_UNIT_ACQUIRED_TARGET',
      'EVENT_UNIT_TARGET_IN_RANGE', 'EVENT_UNIT_ATTACKED', 'EVENT_UNIT_RESCUED', 'EVENT_UNIT_CONSTRUCT_CANCEL',
      'EVENT_UNIT_CONSTRUCT_FINISH', 'EVENT_UNIT_UPGRADE_START', 'EVENT_UNIT_UPGRADE_CANCEL',
      'EVENT_UNIT_UPGRADE_FINISH', 'EVENT_UNIT_TRAIN_START', 'EVENT_UNIT_TRAIN_CANCEL', 'EVENT_UNIT_TRAIN_FINISH',
      'EVENT_UNIT_RESEARCH_START', 'EVENT_UNIT_RESEARCH_CANCEL', 'EVENT_UNIT_RESEARCH_FINISH',
      'EVENT_UNIT_ISSUED_ORDER', 'EVENT_UNIT_ISSUED_POINT_ORDER', 'EVENT_UNIT_ISSUED_TARGET_ORDER',
      'EVENT_UNIT_HERO_LEVEL', 'EVENT_UNIT_HERO_SKILL', 'EVENT_UNIT_HERO_REVIVABLE',
      'EVENT_UNIT_HERO_REVIVE_START', 'EVENT_UNIT_HERO_REVIVE_CANCEL', 'EVENT_UNIT_HERO_REVIVE_FINISH',
      'EVENT_UNIT_SUMMON', 'EVENT_UNIT_DROP_ITEM', 'EVENT_UNIT_PICKUP_ITEM', 'EVENT_UNIT_USE_ITEM',
      'EVENT_UNIT_LOADED', 'EVENT_WIDGET_DEATH', 'EVENT_DIALOG_BUTTON_CLICK', 'EVENT_DIALOG_CLICK',
      'EVENT_GAME_LOADED', 'EVENT_GAME_TOURNAMENT_FINISH_SOON', 'EVENT_GAME_TOURNAMENT_FINISH_NOW',
      'EVENT_GAME_SAVE', 'EVENT_PLAYER_ARROW_LEFT_DOWN', 'EVENT_PLAYER_ARROW_LEFT_UP',
      'EVENT_PLAYER_ARROW_RIGHT_DOWN', 'EVENT_PLAYER_ARROW_RIGHT_UP', 'EVENT_PLAYER_ARROW_DOWN_DOWN',
      'EVENT_PLAYER_ARROW_DOWN_UP', 'EVENT_PLAYER_ARROW_UP_DOWN', 'EVENT_PLAYER_ARROW_UP_UP',
      'EVENT_PLAYER_UNIT_SELL', 'EVENT_PLAYER_UNIT_CHANGE_OWNER', 'EVENT_PLAYER_UNIT_SELL_ITEM',
      'EVENT_PLAYER_UNIT_SPELL_CHANNEL', 'EVENT_PLAYER_UNIT_SPELL_CAST', 'EVENT_PLAYER_UNIT_SPELL_EFFECT',
      'EVENT_PLAYER_UNIT_SPELL_FINISH', 'EVENT_PLAYER_UNIT_SPELL_ENDCAST', 'EVENT_PLAYER_UNIT_PAWN_ITEM',
      'EVENT_UNIT_SELL', 'EVENT_UNIT_CHANGE_OWNER', 'EVENT_UNIT_SELL_ITEM', 'EVENT_UNIT_SPELL_CHANNEL',
      'EVENT_UNIT_SPELL_CAST', 'EVENT_UNIT_SPELL_EFFECT', 'EVENT_UNIT_SPELL_FINISH', 'EVENT_UNIT_SPELL_ENDCAST',
      'EVENT_UNIT_PAWN_ITEM', 'LESS_THAN', 'LESS_THAN_OR_EQUAL', 'EQUAL', 'GREATER_THAN_OR_EQUAL', 'GREATER_THAN',
      'NOT_EQUAL', 'UNIT_TYPE_HERO', 'UNIT_TYPE_DEAD', 'UNIT_TYPE_STRUCTURE', 'UNIT_TYPE_FLYING',
      'UNIT_TYPE_GROUND', 'UNIT_TYPE_ATTACKS_FLYING', 'UNIT_TYPE_ATTACKS_GROUND', 'UNIT_TYPE_MELEE_ATTACKER',
      'UNIT_TYPE_RANGED_ATTACKER', 'UNIT_TYPE_GIANT', 'UNIT_TYPE_SUMMONED', 'UNIT_TYPE_STUNNED',
      'UNIT_TYPE_PLAGUED', 'UNIT_TYPE_SNARED', 'UNIT_TYPE_UNDEAD', 'UNIT_TYPE_MECHANICAL', 'UNIT_TYPE_PEON',
      'UNIT_TYPE_SAPPER', 'UNIT_TYPE_TOWNHALL', 'UNIT_TYPE_ANCIENT', 'UNIT_TYPE_TAUREN', 'UNIT_TYPE_POISONED',
      'UNIT_TYPE_POLYMORPHED', 'UNIT_TYPE_SLEEPING', 'UNIT_TYPE_RESISTANT', 'UNIT_TYPE_ETHEREAL',
      'UNIT_TYPE_MAGIC_IMMUNE', 'ITEM_TYPE_PERMANENT', 'ITEM_TYPE_CHARGED', 'ITEM_TYPE_POWERUP',
      'ITEM_TYPE_ARTIFACT', 'ITEM_TYPE_PURCHASABLE', 'ITEM_TYPE_CAMPAIGN', 'ITEM_TYPE_MISCELLANEOUS',
      'ITEM_TYPE_UNKNOWN', 'ITEM_TYPE_ANY', 'ITEM_TYPE_TOME', 'CAMERA_FIELD_TARGET_DISTANCE', 'CAMERA_FIELD_FARZ',
      'CAMERA_FIELD_ANGLE_OF_ATTACK', 'CAMERA_FIELD_FIELD_OF_VIEW', 'CAMERA_FIELD_ROLL', 'CAMERA_FIELD_ROTATION',
      'CAMERA_FIELD_ZOFFSET', 'BLEND_MODE_NONE', 'BLEND_MODE_DONT_CARE', 'BLEND_MODE_KEYALPHA', 'BLEND_MODE_BLEND',
      'BLEND_MODE_ADDITIVE', 'BLEND_MODE_MODULATE', 'BLEND_MODE_MODULATE_', 'RARITY_FREQUENT', 'RARITY_RARE',
      'TEXMAP_FLAG_NONE', 'TEXMAP_FLAG_WRAP_U', 'TEXMAP_FLAG_WRAP_V', 'TEXMAP_FLAG_WRAP_UV', 'FOG_OF_WAR_MASKED',
      'FOG_OF_WAR_FOGGED', 'FOG_OF_WAR_VISIBLE', 'CAMERA_MARGIN_LEFT', 'CAMERA_MARGIN_RIGHT', 'CAMERA_MARGIN_TOP',
      'CAMERA_MARGIN_BOTTOM', 'EFFECT_TYPE_EFFECT', 'EFFECT_TYPE_TARGET', 'EFFECT_TYPE_CASTER',
      'EFFECT_TYPE_SPECIAL', 'EFFECT_TYPE_AREA_EFFECT', 'EFFECT_TYPE_MISSILE', 'EFFECT_TYPE_LIGHTNING',
      'SOUND_TYPE_EFFECT', 'SOUND_TYPE_EFFECT_LOOPED'
    ),
    6 => array( // jass_nativeFunction
      'Deg2Rad', 'Rad2Deg', 'Sin', 'Cos', 'Tan', 'Asin', 'Acos', 'Atan', 'Atan2', 'SquareRoot', 'Pow', 'I2R',
      'R2I', 'I2S', 'R2S', 'R2SW', 'S2I', 'S2R', 'SubString', 'StringLength', 'StringCase', 'GetLocalizedString',
      'GetLocalizedHotkey', 'SetMapName', 'SetMapDescription', 'SetTeams', 'SetPlayers', 'DefineStartLocation',
      'DefineStartLocationLoc', 'SetStartLocPrioCount', 'SetStartLocPrio', 'GetStartLocPrioSlot',
      'GetStartLocPrio', 'SetGameTypeSupported', 'SetMapFlag', 'SetGamePlacement', 'SetGameSpeed',
      'SetGameDifficulty', 'SetResourceDensity', 'SetCreatureDensity', 'GetTeams', 'GetPlayers',
      'IsGameTypeSupported', 'GetGameTypeSelected', 'IsMapFlagSet', 'SetPlayerTeam', 'SetPlayerStartLocation',
      'ForcePlayerStartLocation', 'SetPlayerColor', 'SetPlayerAlliance', 'SetPlayerTaxRate',
      'SetPlayerRacePreference', 'SetPlayerRaceSelectable', 'SetPlayerController', 'SetPlayerName',
      'SetPlayerOnScoreScreen', 'GetPlayerTeam', 'GetPlayerStartLocation', 'GetPlayerColor', 'GetPlayerSelectable',
      'GetPlayerController', 'GetPlayerSlotState', 'GetPlayerTaxRate', 'IsPlayerRacePrefSet', 'GetPlayerName',
      'CreateTimer', 'DestroyTimer', 'TimerStart', 'TimerGetElapsed', 'TimerGetRemaining', 'TimerGetTimeout',
      'PauseTimer', 'ResumeTimer', 'GetExpiredTimer', 'CreateGroup', 'DestroyGroup', 'GroupAddUnit',
      'GroupRemoveUnit', 'GroupClear', 'GroupEnumUnitsOfType', 'GroupEnumUnitsOfPlayer',
      'GroupEnumUnitsOfTypeCounted', 'GroupEnumUnitsInRect', 'GroupEnumUnitsInRectCounted',
      'GroupEnumUnitsInRange', 'GroupEnumUnitsInRangeOfLoc', 'GroupEnumUnitsInRangeCounted',
      'GroupEnumUnitsInRangeOfLocCounted', 'GroupEnumUnitsSelected', 'GroupImmediateOrder',
      'GroupImmediateOrderById', 'GroupPointOrder', 'GroupPointOrderLoc', 'GroupPointOrderById',
      'GroupPointOrderByIdLoc', 'GroupTargetOrder', 'GroupTargetOrderById', 'ForGroup', 'FirstOfGroup',
      'CreateForce', 'DestroyForce', 'ForceAddPlayer', 'ForceRemovePlayer', 'ForceClear', 'ForceEnumPlayers',
      'ForceEnumPlayersCounted', 'ForceEnumAllies', 'ForceEnumEnemies', 'ForForce', 'Rect', 'RectFromLoc',
      'RemoveRect', 'SetRect', 'SetRectFromLoc', 'MoveRectTo', 'MoveRectToLoc', 'GetRectCenterX', 'GetRectCenterY',
      'GetRectMinX', 'GetRectMinY', 'GetRectMaxX', 'GetRectMaxY', 'CreateRegion', 'RemoveRegion', 'RegionAddRect',
      'RegionClearRect', 'RegionAddCell', 'RegionAddCellAtLoc', 'RegionClearCell', 'RegionClearCellAtLoc',
      'Location', 'RemoveLocation', 'MoveLocation', 'GetLocationX', 'GetLocationY', 'GetLocationZ',
      'IsUnitInRegion', 'IsPointInRegion', 'IsLocationInRegion', 'GetWorldBounds', 'CreateTrigger',
      'DestroyTrigger', 'ResetTrigger', 'EnableTrigger', 'DisableTrigger', 'IsTriggerEnabled',
      'TriggerWaitOnSleeps', 'IsTriggerWaitOnSleeps', 'ExecuteFunc', 'And', 'Or', 'Not', 'Condition',
      'DestroyCondition', 'Filter', 'DestroyFilter', 'DestroyBoolExpr', 'TriggerRegisterVariableEvent',
      'TriggerRegisterTimerEvent', 'TriggerRegisterTimerExpireEvent', 'TriggerRegisterGameStateEvent',
      'TriggerRegisterDialogEvent', 'TriggerRegisterDialogButtonEvent', 'TriggerRegisterGameEvent',
      'TriggerRegisterEnterRegion', 'TriggerRegisterLeaveRegion', 'TriggerRegisterTrackableHitEvent',
      'TriggerRegisterTrackableTrackEvent', 'TriggerRegisterPlayerEvent', 'TriggerRegisterPlayerUnitEvent',
      'TriggerRegisterPlayerAllianceChange', 'TriggerRegisterPlayerStateEvent', 'TriggerRegisterPlayerChatEvent',
      'TriggerRegisterDeathEvent', 'TriggerRegisterUnitStateEvent', 'TriggerRegisterUnitEvent',
      'TriggerRegisterFilterUnitEvent', 'TriggerRegisterUnitInRange', 'TriggerAddCondition',
      'TriggerRemoveCondition', 'TriggerClearConditions', 'TriggerAddAction', 'TriggerRemoveAction',
      'TriggerClearActions', 'TriggerSleepAction', 'TriggerWaitForSound', 'TriggerEvaluate', 'TriggerExecute',
      'TriggerExecuteWait', 'TriggerSyncStart', 'TriggerSyncReady', 'GetWidgetLife', 'SetWidgetLife', 'GetWidgetX',
      'GetWidgetY', 'CreateDestructable', 'CreateDestructableZ', 'CreateDeadDestructable',
      'CreateDeadDestructableZ', 'RemoveDestructable', 'KillDestructable', 'SetDestructableInvulnerable',
      'IsDestructableInvulnerable', 'EnumDestructablesInRect', 'GetDestructableTypeId', 'GetDestructableX',
      'GetDestructableY', 'SetDestructableLife', 'GetDestructableLife', 'SetDestructableMaxLife',
      'GetDestructableMaxLife', 'DestructableRestoreLife', 'QueueDestructableAnimation',
      'SetDestructableAnimation', 'SetDestructableAnimationSpeed', 'ShowDestructable',
      'GetDestructableOccluderHeight', 'SetDestructableOccluderHeight', 'GetDestructableName', 'CreateItem',
      'RemoveItem', 'GetItemPlayer', 'GetItemTypeId', 'GetItemX', 'GetItemY', 'SetItemPosition',
      'SetItemDropOnDeath', 'SetItemDroppable', 'SetItemPawnable', 'SetItemPlayer', 'SetItemInvulnerable',
      'IsItemInvulnerable', 'SetItemVisible', 'IsItemVisible', 'IsItemOwned', 'IsItemPowerup', 'IsItemSellable',
      'IsItemPawnable', 'IsItemIdPowerup', 'IsItemIdSellable', 'IsItemIdPawnable', 'EnumItemsInRect',
      'GetItemLevel', 'GetItemType', 'SetItemDropID', 'GetItemCharges', 'SetItemCharges', 'GetItemUserData',
      'SetItemUserData', 'CreateUnit', 'CreateUnitByName', 'CreateUnitAtLoc', 'CreateUnitAtLocByName',
      'CreateCorpse', 'KillUnit', 'RemoveUnit', 'ShowUnit', 'SetUnitState', 'SetUnitX', 'SetUnitY',
      'SetUnitPosition', 'SetUnitPositionLoc', 'SetUnitFacing', 'SetUnitFacingTimed', 'SetUnitMoveSpeed',
      'SetUnitFlyHeight', 'SetUnitTurnSpeed', 'SetUnitPropWindow', 'SetUnitAcquireRange', 'SetUnitCreepGuard',
      'GetUnitAcquireRange', 'GetUnitTurnSpeed', 'GetUnitPropWindow', 'GetUnitFlyHeight',
      'GetUnitDefaultAcquireRange', 'GetUnitDefaultTurnSpeed', 'GetUnitDefaultPropWindow',
      'GetUnitDefaultFlyHeight', 'SetUnitOwner', 'SetUnitColor', 'SetUnitScale', 'SetUnitTimeScale',
      'SetUnitBlendTime', 'SetUnitVertexColor', 'QueueUnitAnimation', 'SetUnitAnimation',
      'SetUnitAnimationByIndex', 'SetUnitAnimationWithRarity', 'AddUnitAnimationProperties', 'SetUnitLookAt',
      'ResetUnitLookAt', 'SetUnitRescuable', 'SetUnitRescueRange', 'SetHeroStr', 'SetHeroAgi', 'SetHeroInt',
      'GetHeroStr', 'GetHeroAgi', 'GetHeroInt', 'UnitStripHeroLevel', 'GetHeroXP', 'SetHeroXP',
      'GetHeroSkillPoints', 'UnitModifySkillPoints', 'AddHeroXP', 'SetHeroLevel', 'GetHeroProperName',
      'SuspendHeroXP', 'IsSuspendedXP', 'SelectHeroSkill', 'GetUnitAbilityLevel', 'DecUnitAbilityLevel',
      'IncUnitAbilityLevel', 'SetUnitAbilityLevel', 'ReviveHero', 'ReviveHeroLoc', 'SetUnitExploded',
      'SetUnitInvulnerable', 'PauseUnit', 'IsUnitPaused', 'SetUnitPathing', 'ClearSelection', 'SelectUnit',
      'GetUnitPointValue', 'GetUnitPointValueByType', 'UnitAddItem', 'UnitAddItemById', 'UnitAddItemToSlotById',
      'UnitRemoveItem', 'UnitRemoveItemFromSlot', 'UnitHasItem', 'UnitItemInSlot', 'UnitInventorySize',
      'UnitDropItemPoint', 'UnitDropItemSlot', 'UnitDropItemTarget', 'UnitUseItem', 'UnitUseItemPoint',
      'UnitUseItemTarget', 'SetUnitUseFood', 'UnitShareVision', 'UnitSuspendDecay', 'UnitAddType',
      'UnitRemoveType', 'UnitAddAbility', 'UnitRemoveAbility', 'UnitMakeAbilityPermanent', 'UnitRemoveBuffs',
      'UnitRemoveBuffsEx', 'UnitHasBuffsEx', 'UnitCountBuffsEx', 'UnitAddSleep', 'UnitCanSleep',
      'UnitAddSleepPerm', 'UnitCanSleepPerm', 'UnitIsSleeping', 'UnitWakeUp', 'UnitApplyTimedLife',
      'UnitIgnoreAlarm', 'UnitIgnoreAlarmToggled', 'UnitResetCooldown', 'UnitSetConstructionProgress',
      'UnitSetUpgradeProgress', 'UnitPauseTimedLife', 'UnitSetUsesAltIcon', 'UnitDamagePoint', 'UnitDamageTarget',
      'IssueImmediateOrder', 'IssueImmediateOrderById', 'IssuePointOrder', 'IssuePointOrderLoc',
      'IssuePointOrderById', 'IssuePointOrderByIdLoc', 'IssueTargetOrder', 'IssueTargetOrderById',
      'IssueInstantPointOrder', 'IssueInstantPointOrderById', 'IssueInstantTargetOrder',
      'IssueInstantTargetOrderById', 'IssueBuildOrder', 'IssueBuildOrderById', 'IssueNeutralImmediateOrder',
      'IssueNeutralImmediateOrderById', 'IssueNeutralPointOrder', 'IssueNeutralPointOrderById',
      'IssueNeutralTargetOrder', 'IssueNeutralTargetOrderById', 'GetUnitCurrentOrder', 'SetResourceAmount',
      'AddResourceAmount', 'GetResourceAmount', 'WaygateGetDestinationX', 'WaygateGetDestinationY',
      'WaygateSetDestination', 'WaygateActivate', 'WaygateIsActive', 'AddItemToAllStock', 'AddItemToStock',
      'AddUnitToAllStock', 'AddUnitToStock', 'RemoveItemFromAllStock', 'RemoveItemFromStock',
      'RemoveUnitFromAllStock', 'RemoveUnitFromStock', 'SetAllItemTypeSlots', 'SetAllUnitTypeSlots',
      'SetItemTypeSlots', 'SetUnitTypeSlots', 'GetUnitUserData', 'SetUnitUserData', 'SetPlayerUnitsOwner',
      'CripplePlayer', 'SetPlayerAbilityAvailable', 'SetPlayerState', 'RemovePlayer', 'CachePlayerHeroData',
      'SetFogStateRect', 'SetFogStateRadius', 'SetFogStateRadiusLoc', 'FogMaskEnable', 'IsFogMaskEnabled',
      'FogEnable', 'IsFogEnabled', 'CreateFogModifierRect', 'CreateFogModifierRadius',
      'CreateFogModifierRadiusLoc', 'DestroyFogModifier', 'FogModifierStart', 'FogModifierStop', 'VersionGet',
      'VersionCompatible', 'VersionSupported', 'EndGame', 'ChangeLevel', 'RestartGame', 'ReloadGame',
      'SetCampaignMenuRace', 'SetCampaignMenuRaceEx', 'ForceCampaignSelectScreen', 'LoadGame', 'SaveGame',
      'RenameSaveDirectory', 'RemoveSaveDirectory', 'CopySaveGame', 'SaveGameExists', 'SyncSelections',
      'SetFloatGameState', 'SetIntegerGameState', 'SetTutorialCleared', 'SetMissionAvailable',
      'SetCampaignAvailable', 'SetOpCinematicAvailable', 'SetEdCinematicAvailable', 'GetDefaultDifficulty',
      'SetDefaultDifficulty', 'SetCustomCampaignButtonVisible', 'GetCustomCampaignButtonVisible',
      'DoNotSaveReplay', 'DialogCreate', 'DialogDestroy', 'DialogClear', 'DialogSetMessage', 'DialogAddButton',
      'DialogAddQuitButton', 'DialogDisplay', 'ReloadGameCachesFromDisk', 'InitGameCache', 'SaveGameCache',
      'StoreInteger', 'StoreReal', 'StoreBoolean', 'StoreUnit', 'StoreString', 'SyncStoredInteger',
      'SyncStoredReal', 'SyncStoredBoolean', 'SyncStoredUnit', 'SyncStoredString', 'GetStoredInteger',
      'GetStoredReal', 'GetStoredBoolean', 'GetStoredString', 'RestoreUnit', 'HaveStoredInteger', 'HaveStoredReal',
      'HaveStoredBoolean', 'HaveStoredUnit', 'HaveStoredString', 'FlushGameCache', 'FlushStoredMission',
      'FlushStoredInteger', 'FlushStoredReal', 'FlushStoredBoolean', 'FlushStoredUnit', 'FlushStoredString',
      'GetRandomInt', 'GetRandomReal', 'CreateUnitPool', 'DestroyUnitPool', 'UnitPoolAddUnitType',
      'UnitPoolRemoveUnitType', 'PlaceRandomUnit', 'CreateItemPool', 'DestroyItemPool', 'ItemPoolAddItemType',
      'ItemPoolRemoveItemType', 'PlaceRandomItem', 'ChooseRandomCreep', 'ChooseRandomNPBuilding',
      'ChooseRandomItem', 'ChooseRandomItemEx', 'SetRandomSeed', 'SetTerrainFog', 'ResetTerrainFog', 'SetUnitFog',
      'SetTerrainFogEx', 'DisplayTextToPlayer', 'DisplayTimedTextToPlayer', 'DisplayTimedTextFromPlayer',
      'ClearTextMessages', 'SetDayNightModels', 'SetSkyModel', 'EnableUserControl', 'EnableUserUI',
      'SuspendTimeOfDay', 'SetTimeOfDayScale', 'GetTimeOfDayScale', 'ShowInterface', 'PauseGame',
      'UnitAddIndicator', 'AddIndicator', 'PingMinimap', 'PingMinimapEx', 'EnableOcclusion', 'SetIntroShotText',
      'SetIntroShotModel', 'EnableWorldFogBoundary', 'PlayModelCinematic', 'PlayCinematic', 'ForceUIKey',
      'ForceUICancel', 'DisplayLoadDialog', 'SetAltMinimapIcon', 'DisableRestartMission', 'CreateTextTag',
      'DestroyTextTag', 'SetTextTagText', 'SetTextTagPos', 'SetTextTagPosUnit', 'SetTextTagColor',
      'SetTextTagVelocity', 'SetTextTagVisibility', 'SetTextTagSuspended', 'SetTextTagPermanent', 'SetTextTagAge',
      'SetTextTagLifespan', 'SetTextTagFadepoint', 'SetReservedLocalHeroButtons', 'GetAllyColorFilterState',
      'SetAllyColorFilterState', 'GetCreepCampFilterState', 'SetCreepCampFilterState',
      'EnableMinimapFilterButtons', 'EnableDragSelect', 'EnablePreSelect', 'EnableSelect', 'CreateTrackable',
      'CreateQuest', 'DestroyQuest', 'QuestSetTitle', 'QuestSetDescription', 'QuestSetIconPath',
      'QuestSetRequired', 'QuestSetCompleted', 'QuestSetDiscovered', 'QuestSetFailed', 'QuestSetEnabled',
      'IsQuestRequired', 'IsQuestCompleted', 'IsQuestDiscovered', 'IsQuestFailed', 'IsQuestEnabled',
      'QuestCreateItem', 'QuestItemSetDescription', 'QuestItemSetCompleted', 'IsQuestItemCompleted',
      'CreateDefeatCondition', 'DestroyDefeatCondition', 'DefeatConditionSetDescription', 'FlashQuestDialogButton',
      'ForceQuestDialogUpdate', 'CreateTimerDialog', 'DestroyTimerDialog', 'TimerDialogSetTitle',
      'TimerDialogSetTitleColor', 'TimerDialogSetTimeColor', 'TimerDialogSetSpeed', 'TimerDialogDisplay',
      'IsTimerDialogDisplayed', 'TimerDialogSetRealTimeRemaining', 'CreateLeaderboard', 'DestroyLeaderboard',
      'LeaderboardDisplay', 'IsLeaderboardDisplayed', 'LeaderboardGetItemCount', 'LeaderboardSetSizeByItemCount',
      'LeaderboardAddItem', 'LeaderboardRemoveItem', 'LeaderboardRemovePlayerItem', 'LeaderboardClear',
      'LeaderboardSortItemsByValue', 'LeaderboardSortItemsByPlayer', 'LeaderboardSortItemsByLabel',
      'LeaderboardHasPlayerItem', 'LeaderboardGetPlayerIndex', 'LeaderboardSetLabel', 'LeaderboardGetLabelText',
      'PlayerSetLeaderboard', 'PlayerGetLeaderboard', 'LeaderboardSetLabelColor', 'LeaderboardSetValueColor',
      'LeaderboardSetStyle', 'LeaderboardSetItemValue', 'LeaderboardSetItemLabel', 'LeaderboardSetItemStyle',
      'LeaderboardSetItemLabelColor', 'LeaderboardSetItemValueColor', 'CreateMultiboard', 'DestroyMultiboard',
      'MultiboardDisplay', 'IsMultiboardDisplayed', 'MultiboardMinimize', 'IsMultiboardMinimized',
      'MultiboardClear', 'MultiboardSetTitleText', 'MultiboardGetTitleText', 'MultiboardSetTitleTextColor',
      'MultiboardGetRowCount', 'MultiboardGetColumnCount', 'MultiboardSetColumnCount', 'MultiboardSetRowCount',
      'MultiboardSetItemsStyle', 'MultiboardSetItemsValue', 'MultiboardSetItemsValueColor',
      'MultiboardSetItemsWidth', 'MultiboardSetItemsIcon', 'MultiboardGetItem', 'MultiboardReleaseItem',
      'MultiboardSetItemStyle', 'MultiboardSetItemValue', 'MultiboardSetItemValueColor', 'MultiboardSetItemWidth',
      'MultiboardSetItemIcon', 'MultiboardSuppressDisplay', 'SetCameraPosition', 'SetCameraQuickPosition',
      'SetCameraBounds', 'StopCamera', 'ResetToGameCamera', 'PanCameraTo', 'PanCameraToTimed', 'PanCameraToWithZ',
      'PanCameraToTimedWithZ', 'SetCinematicCamera', 'SetCameraRotateMode', 'SetCameraField', 'AdjustCameraField',
      'SetCameraTargetController', 'SetCameraOrientController', 'CreateCameraSetup', 'CameraSetupSetField',
      'CameraSetupGetField', 'CameraSetupSetDestPosition', 'CameraSetupGetDestPositionLoc',
      'CameraSetupGetDestPositionX', 'CameraSetupGetDestPositionY', 'CameraSetupApply', 'CameraSetupApplyWithZ',
      'CameraSetupApplyForceDuration', 'CameraSetupApplyForceDurationWithZ', 'CameraSetTargetNoise',
      'CameraSetSourceNoise', 'CameraSetTargetNoiseEx', 'CameraSetSourceNoiseEx', 'CameraSetSmoothingFactor',
      'SetCineFilterTexture', 'SetCineFilterBlendMode', 'SetCineFilterTexMapFlags', 'SetCineFilterStartUV',
      'SetCineFilterEndUV', 'SetCineFilterStartColor', 'SetCineFilterEndColor', 'SetCineFilterDuration',
      'DisplayCineFilter', 'IsCineFilterDisplayed', 'SetCinematicScene', 'EndCinematicScene',
      'ForceCinematicSubtitles', 'GetCameraMargin', 'NewSoundEnvironment', 'CreateSound',
      'CreateSoundFilenameWithLabel', 'CreateSoundFromLabel', 'CreateMIDISound', 'SetSoundParamsFromLabel',
      'SetSoundDistanceCutoff', 'SetSoundChannel', 'SetSoundVolume', 'SetSoundPitch', 'SetSoundPlayPosition',
      'SetSoundDistances', 'SetSoundConeAngles', 'SetSoundConeOrientation', 'SetSoundPosition', 'SetSoundVelocity',
      'AttachSoundToUnit', 'StartSound', 'StopSound', 'KillSoundWhenDone', 'SetMapMusic', 'ClearMapMusic',
      'PlayMusic', 'PlayMusicEx', 'StopMusic', 'ResumeMusic', 'PlayThematicMusic', 'PlayThematicMusicEx',
      'EndThematicMusic', 'SetMusicVolume', 'SetMusicPlayPosition', 'SetThematicMusicPlayPosition',
      'SetSoundDuration', 'GetSoundDuration', 'GetSoundFileDuration', 'VolumeGroupSetVolume', 'VolumeGroupReset',
      'GetSoundIsPlaying', 'GetSoundIsLoading', 'RegisterStackedSound', 'UnregisterStackedSound',
      'AddWeatherEffect', 'RemoveWeatherEffect', 'EnableWeatherEffect', 'TerrainDeformCrater',
      'TerrainDeformRipple', 'TerrainDeformWave', 'TerrainDeformRandom', 'TerrainDeformStop',
      'TerrainDeformStopAll', 'AddSpecialEffect', 'AddSpecialEffectLoc', 'AddSpecialEffectTarget', 'DestroyEffect',
      'AddSpellEffect', 'AddSpellEffectLoc', 'AddSpellEffectById', 'AddSpellEffectByIdLoc', 'AddSpellEffectTarget',
      'AddSpellEffectTargetById', 'AddLightning', 'AddLightningEx', 'DestroyLightning', 'MoveLightning',
      'MoveLightningEx', 'GetLightningColorA', 'GetLightningColorR', 'GetLightningColorG', 'GetLightningColorB',
      'SetLightningColor', 'GetAbilityEffect', 'GetAbilityEffectById', 'GetAbilitySound', 'GetAbilitySoundById',
      'GetTerrainCliffLevel', 'SetWaterBaseColor', 'SetWaterDeforms', 'GetTerrainType', 'GetTerrainVariance',
      'SetTerrainType', 'IsTerrainPathable', 'SetTerrainPathable', 'CreateImage', 'DestroyImage', 'ShowImage',
      'SetImageConstantHeight', 'SetImagePosition', 'SetImageColor', 'SetImageRender', 'SetImageRenderAlways',
      'SetImageAboveWater', 'SetImageType', 'CreateUbersplat', 'DestroyUbersplat', 'ResetUbersplat',
      'FinishUbersplat', 'ShowUbersplat', 'SetUbersplatRender', 'SetUbersplatRenderAlways', 'SetBlight',
      'SetBlightRect', 'SetBlightPoint', 'SetBlightLoc', 'CreateBlightedGoldmine', 'IsPointBlighted',
      'SetDoodadAnimation', 'SetDoodadAnimationRect', 'StartMeleeAI', 'StartCampaignAI', 'CommandAI',
      'PauseCompAI', 'GetAIDifficulty', 'RemoveGuardPosition', 'RecycleGuardPosition', 'RemoveAllGuardPositions',
      'Cheat', 'IsNoVictoryCheat', 'IsNoDefeatCheat', 'Preload', 'PreloadEnd', 'PreloadStart', 'PreloadRefresh',
      'PreloadEndEx', 'PreloadGenClear', 'PreloadGenStart', 'PreloadGenEnd', 'Preloader'
    ),
    7 => array( // jass_bjConstant
      'bj_PI', 'bj_E', 'bj_CELLWIDTH', 'bj_CLIFFHEIGHT', 'bj_UNIT_FACING', 'bj_RADTODEG', 'bj_DEGTORAD',
      'bj_TEXT_DELAY_QUEST', 'bj_TEXT_DELAY_QUESTUPDATE', 'bj_TEXT_DELAY_QUESTDONE', 'bj_TEXT_DELAY_QUESTFAILED',
      'bj_TEXT_DELAY_QUESTREQUIREMENT', 'bj_TEXT_DELAY_MISSIONFAILED', 'bj_TEXT_DELAY_ALWAYSHINT',
      'bj_TEXT_DELAY_HINT', 'bj_TEXT_DELAY_SECRET', 'bj_TEXT_DELAY_UNITACQUIRED', 'bj_TEXT_DELAY_UNITAVAILABLE',
      'bj_TEXT_DELAY_ITEMACQUIRED', 'bj_TEXT_DELAY_WARNING', 'bj_QUEUE_DELAY_QUEST', 'bj_QUEUE_DELAY_HINT',
      'bj_QUEUE_DELAY_SECRET', 'bj_HANDICAP_EASY', 'bj_GAME_STARTED_THRESHOLD', 'bj_WAIT_FOR_COND_MIN_INTERVAL',
      'bj_POLLED_WAIT_INTERVAL', 'bj_POLLED_WAIT_SKIP_THRESHOLD', 'bj_MAX_INVENTORY', 'bj_MAX_PLAYERS',
      'bj_PLAYER_NEUTRAL_VICTIM', 'bj_PLAYER_NEUTRAL_EXTRA', 'bj_MAX_PLAYER_SLOTS', 'bj_MAX_SKELETONS',
      'bj_MAX_STOCK_ITEM_SLOTS', 'bj_MAX_STOCK_UNIT_SLOTS', 'bj_MAX_ITEM_LEVEL', 'bj_TOD_DAWN', 'bj_TOD_DUSK',
      'bj_MELEE_STARTING_TOD', 'bj_MELEE_STARTING_GOLD_V', 'bj_MELEE_STARTING_GOLD_V',
      'bj_MELEE_STARTING_LUMBER_V', 'bj_MELEE_STARTING_LUMBER_V', 'bj_MELEE_STARTING_HERO_TOKENS',
      'bj_MELEE_HERO_LIMIT', 'bj_MELEE_HERO_TYPE_LIMIT', 'bj_MELEE_MINE_SEARCH_RADIUS',
      'bj_MELEE_CLEAR_UNITS_RADIUS', 'bj_MELEE_CRIPPLE_TIMEOUT', 'bj_MELEE_CRIPPLE_MSG_DURATION',
      'bj_MELEE_MAX_TWINKED_HEROES_V', 'bj_MELEE_MAX_TWINKED_HEROES_V', 'bj_CREEP_ITEM_DELAY',
      'bj_STOCK_RESTOCK_INITIAL_DELAY', 'bj_STOCK_RESTOCK_INTERVAL', 'bj_STOCK_MAX_ITERATIONS',
      'bj_MAX_DEST_IN_REGION_EVENTS', 'bj_CAMERA_MIN_FARZ', 'bj_CAMERA_DEFAULT_DISTANCE', 'bj_CAMERA_DEFAULT_FARZ',
      'bj_CAMERA_DEFAULT_AOA', 'bj_CAMERA_DEFAULT_FOV', 'bj_CAMERA_DEFAULT_ROLL', 'bj_CAMERA_DEFAULT_ROTATION',
      'bj_RESCUE_PING_TIME', 'bj_NOTHING_SOUND_DURATION', 'bj_TRANSMISSION_PING_TIME', 'bj_TRANSMISSION_IND_RED',
      'bj_TRANSMISSION_IND_BLUE', 'bj_TRANSMISSION_IND_GREEN', 'bj_TRANSMISSION_IND_ALPHA',
      'bj_TRANSMISSION_PORT_HANGTIME', 'bj_CINEMODE_INTERFACEFADE', 'bj_CINEMODE_GAMESPEED',
      'bj_CINEMODE_VOLUME_UNITMOVEMENT', 'bj_CINEMODE_VOLUME_UNITSOUNDS', 'bj_CINEMODE_VOLUME_COMBAT',
      'bj_CINEMODE_VOLUME_SPELLS', 'bj_CINEMODE_VOLUME_UI', 'bj_CINEMODE_VOLUME_MUSIC',
      'bj_CINEMODE_VOLUME_AMBIENTSOUNDS', 'bj_CINEMODE_VOLUME_FIRE', 'bj_SPEECH_VOLUME_UNITMOVEMENT',
      'bj_SPEECH_VOLUME_UNITSOUNDS', 'bj_SPEECH_VOLUME_COMBAT', 'bj_SPEECH_VOLUME_SPELLS', 'bj_SPEECH_VOLUME_UI',
      'bj_SPEECH_VOLUME_MUSIC', 'bj_SPEECH_VOLUME_AMBIENTSOUNDS', 'bj_SPEECH_VOLUME_FIRE',
      'bj_SMARTPAN_TRESHOLD_PAN', 'bj_SMARTPAN_TRESHOLD_SNAP', 'bj_MAX_QUEUED_TRIGGERS',
      'bj_QUEUED_TRIGGER_TIMEOUT', 'bj_CAMPAIGN_INDEX_T', 'bj_CAMPAIGN_INDEX_H', 'bj_CAMPAIGN_INDEX_U',
      'bj_CAMPAIGN_INDEX_O', 'bj_CAMPAIGN_INDEX_N', 'bj_CAMPAIGN_INDEX_XN', 'bj_CAMPAIGN_INDEX_XH',
      'bj_CAMPAIGN_INDEX_XU', 'bj_CAMPAIGN_INDEX_XO', 'bj_CAMPAIGN_OFFSET_T', 'bj_CAMPAIGN_OFFSET_H',
      'bj_CAMPAIGN_OFFSET_U', 'bj_CAMPAIGN_OFFSET_O', 'bj_CAMPAIGN_OFFSET_N', 'bj_CAMPAIGN_OFFSET_XN',
      'bj_CAMPAIGN_OFFSET_XH', 'bj_CAMPAIGN_OFFSET_XU', 'bj_CAMPAIGN_OFFSET_XO', 'bj_MISSION_INDEX_T',
      'bj_MISSION_INDEX_T', 'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H',
      'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H',
      'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_H', 'bj_MISSION_INDEX_U', 'bj_MISSION_INDEX_U',
      'bj_MISSION_INDEX_U', 'bj_MISSION_INDEX_U', 'bj_MISSION_INDEX_U', 'bj_MISSION_INDEX_U', 'bj_MISSION_INDEX_U',
      'bj_MISSION_INDEX_U', 'bj_MISSION_INDEX_U', 'bj_MISSION_INDEX_U', 'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_O',
      'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_O',
      'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_O', 'bj_MISSION_INDEX_N',
      'bj_MISSION_INDEX_N', 'bj_MISSION_INDEX_N', 'bj_MISSION_INDEX_N', 'bj_MISSION_INDEX_N', 'bj_MISSION_INDEX_N',
      'bj_MISSION_INDEX_N', 'bj_MISSION_INDEX_N', 'bj_MISSION_INDEX_N', 'bj_MISSION_INDEX_N',
      'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XN',
      'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XN',
      'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XN', 'bj_MISSION_INDEX_XH',
      'bj_MISSION_INDEX_XH', 'bj_MISSION_INDEX_XH', 'bj_MISSION_INDEX_XH', 'bj_MISSION_INDEX_XH',
      'bj_MISSION_INDEX_XH', 'bj_MISSION_INDEX_XH', 'bj_MISSION_INDEX_XH', 'bj_MISSION_INDEX_XH',
      'bj_MISSION_INDEX_XH', 'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU',
      'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU',
      'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU',
      'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XU', 'bj_MISSION_INDEX_XO',
      'bj_CINEMATICINDEX_TOP', 'bj_CINEMATICINDEX_HOP', 'bj_CINEMATICINDEX_HED', 'bj_CINEMATICINDEX_OOP',
      'bj_CINEMATICINDEX_OED', 'bj_CINEMATICINDEX_UOP', 'bj_CINEMATICINDEX_UED', 'bj_CINEMATICINDEX_NOP',
      'bj_CINEMATICINDEX_NED', 'bj_CINEMATICINDEX_XOP', 'bj_CINEMATICINDEX_XED', 'bj_ALLIANCE_UNALLIED',
      'bj_ALLIANCE_UNALLIED_VISION', 'bj_ALLIANCE_ALLIED', 'bj_ALLIANCE_ALLIED_VISION', 'bj_ALLIANCE_ALLIED_UNITS',
      'bj_ALLIANCE_ALLIED_ADVUNITS', 'bj_ALLIANCE_NEUTRAL', 'bj_ALLIANCE_NEUTRAL_VISION',
      'bj_KEYEVENTTYPE_DEPRESS', 'bj_KEYEVENTTYPE_RELEASE', 'bj_KEYEVENTKEY_LEFT', 'bj_KEYEVENTKEY_RIGHT',
      'bj_KEYEVENTKEY_DOWN', 'bj_KEYEVENTKEY_UP', 'bj_TIMETYPE_ADD', 'bj_TIMETYPE_SET', 'bj_TIMETYPE_SUB',
      'bj_CAMERABOUNDS_ADJUST_ADD', 'bj_CAMERABOUNDS_ADJUST_SUB', 'bj_QUESTTYPE_REQ_DISCOVERED',
      'bj_QUESTTYPE_REQ_UNDISCOVERED', 'bj_QUESTTYPE_OPT_DISCOVERED', 'bj_QUESTTYPE_OPT_UNDISCOVERED',
      'bj_QUESTMESSAGE_DISCOVERED', 'bj_QUESTMESSAGE_UPDATED', 'bj_QUESTMESSAGE_COMPLETED',
      'bj_QUESTMESSAGE_FAILED', 'bj_QUESTMESSAGE_REQUIREMENT', 'bj_QUESTMESSAGE_MISSIONFAILED',
      'bj_QUESTMESSAGE_ALWAYSHINT', 'bj_QUESTMESSAGE_HINT', 'bj_QUESTMESSAGE_SECRET',
      'bj_QUESTMESSAGE_UNITACQUIRED', 'bj_QUESTMESSAGE_UNITAVAILABLE', 'bj_QUESTMESSAGE_ITEMACQUIRED',
      'bj_QUESTMESSAGE_WARNING', 'bj_SORTTYPE_SORTBYVALUE', 'bj_SORTTYPE_SORTBYPLAYER', 'bj_SORTTYPE_SORTBYLABEL',
      'bj_CINEFADETYPE_FADEIN', 'bj_CINEFADETYPE_FADEOUT', 'bj_CINEFADETYPE_FADEOUTIN', 'bj_REMOVEBUFFS_POSITIVE',
      'bj_REMOVEBUFFS_NEGATIVE', 'bj_REMOVEBUFFS_ALL', 'bj_REMOVEBUFFS_NONTLIFE', 'bj_BUFF_POLARITY_POSITIVE',
      'bj_BUFF_POLARITY_NEGATIVE', 'bj_BUFF_POLARITY_EITHER', 'bj_BUFF_RESIST_MAGIC', 'bj_BUFF_RESIST_PHYSICAL',
      'bj_BUFF_RESIST_EITHER', 'bj_BUFF_RESIST_BOTH', 'bj_HEROSTAT_STR', 'bj_HEROSTAT_AGI', 'bj_HEROSTAT_INT',
      'bj_MODIFYMETHOD_ADD', 'bj_MODIFYMETHOD_SUB', 'bj_MODIFYMETHOD_SET', 'bj_UNIT_STATE_METHOD_ABSOLUTE',
      'bj_UNIT_STATE_METHOD_RELATIVE', 'bj_UNIT_STATE_METHOD_DEFAULTS', 'bj_UNIT_STATE_METHOD_MAXIMUM',
      'bj_GATEOPERATION_CLOSE', 'bj_GATEOPERATION_OPEN', 'bj_GATEOPERATION_DESTROY', 'bj_GAMECACHE_BOOLEAN',
      'bj_GAMECACHE_INTEGER', 'bj_GAMECACHE_REAL', 'bj_GAMECACHE_UNIT', 'bj_GAMECACHE_STRING',
      'bj_ITEM_STATUS_HIDDEN', 'bj_ITEM_STATUS_OWNED', 'bj_ITEM_STATUS_INVULNERABLE', 'bj_ITEM_STATUS_POWERUP',
      'bj_ITEM_STATUS_SELLABLE', 'bj_ITEM_STATUS_PAWNABLE', 'bj_ITEMCODE_STATUS_POWERUP',
      'bj_ITEMCODE_STATUS_SELLABLE', 'bj_ITEMCODE_STATUS_PAWNABLE', 'bj_MINIMAPPINGSTYLE_SIMPLE',
      'bj_MINIMAPPINGSTYLE_FLASHY', 'bj_MINIMAPPINGSTYLE_ATTACK', 'bj_CORPSE_MAX_DEATH_TIME',
      'bj_CORPSETYPE_FLESH', 'bj_CORPSETYPE_BONE', 'bj_ELEVATOR_BLOCKER_CODE', 'bj_ELEVATOR_CODE',
      'bj_ELEVATOR_CODE', 'bj_ELEVATOR_WALL_TYPE_ALL', 'bj_ELEVATOR_WALL_TYPE_EAST', 'bj_ELEVATOR_WALL_TYPE_NORTH',
      'bj_ELEVATOR_WALL_TYPE_SOUTH', 'bj_ELEVATOR_WALL_TYPE_WEST'
    ),
    8 => array( // jass_bjVariable
      'bj_FORCE_ALL_PLAYERS', 'bj_FORCE_PLAYER', 'bj_MELEE_MAX_TWINKED_HEROES', 'bj_mapInitialPlayableArea',
      'bj_mapInitialCameraBounds', 'bj_forLoopAIndex', 'bj_forLoopBIndex', 'bj_forLoopAIndexEnd',
      'bj_forLoopBIndexEnd', 'bj_slotControlReady', 'bj_slotControlUsed', 'bj_slotControl', 'bj_gameStartedTimer',
      'bj_gameStarted', 'bj_volumeGroupsTimer', 'bj_isSinglePlayer', 'bj_dncSoundsDay', 'bj_dncSoundsNight',
      'bj_dayAmbientSound', 'bj_nightAmbientSound', 'bj_dncSoundsDawn', 'bj_dncSoundsDusk', 'bj_dawnSound',
      'bj_duskSound', 'bj_useDawnDuskSounds', 'bj_dncIsDaytime', 'bj_rescueSound', 'bj_questDiscoveredSound',
      'bj_questUpdatedSound', 'bj_questCompletedSound', 'bj_questFailedSound', 'bj_questHintSound',
      'bj_questSecretSound', 'bj_questItemAcquiredSound', 'bj_questWarningSound', 'bj_victoryDialogSound',
      'bj_defeatDialogSound', 'bj_stockItemPurchased', 'bj_stockUpdateTimer', 'bj_stockAllowedPermanent',
      'bj_stockAllowedCharged', 'bj_stockAllowedArtifact', 'bj_stockPickedItemLevel', 'bj_stockPickedItemType',
      'bj_meleeVisibilityTrained', 'bj_meleeVisibilityIsDay', 'bj_meleeGrantHeroItems', 'bj_meleeNearestMineToLoc',
      'bj_meleeNearestMine', 'bj_meleeNearestMineDist', 'bj_meleeGameOver', 'bj_meleeDefeated',
      'bj_meleeVictoried', 'bj_ghoul', 'bj_crippledTimer', 'bj_crippledTimerWindows', 'bj_playerIsCrippled',
      'bj_playerIsExposed', 'bj_finishSoonAllExposed', 'bj_finishSoonTimerDialog', 'bj_meleeTwinkedHeroes',
      'bj_rescueUnitBehavior', 'bj_rescueChangeColorUnit', 'bj_rescueChangeColorBldg', 'bj_cineSceneEndingTimer',
      'bj_cineSceneLastSound', 'bj_cineSceneBeingSkipped', 'bj_cineModePriorSpeed', 'bj_cineModePriorFogSetting',
      'bj_cineModePriorMaskSetting', 'bj_cineModeAlreadyIn', 'bj_cineModePriorDawnDusk', 'bj_cineModeSavedSeed',
      'bj_cineFadeFinishTimer', 'bj_cineFadeContinueTimer', 'bj_cineFadeContinueRed', 'bj_cineFadeContinueGreen',
      'bj_cineFadeContinueBlue', 'bj_cineFadeContinueTrans', 'bj_cineFadeContinueDuration',
      'bj_cineFadeContinueTex', 'bj_queuedExecTotal', 'bj_queuedExecTriggers', 'bj_queuedExecUseConds',
      'bj_queuedExecTimeoutTimer', 'bj_queuedExecTimeout', 'bj_destInRegionDiesCount', 'bj_destInRegionDiesTrig',
      'bj_groupCountUnits', 'bj_forceCountPlayers', 'bj_groupEnumTypeId', 'bj_groupEnumOwningPlayer',
      'bj_groupAddGroupDest', 'bj_groupRemoveGroupDest', 'bj_groupRandomConsidered', 'bj_groupRandomCurrentPick',
      'bj_groupLastCreatedDest', 'bj_randomSubGroupGroup', 'bj_randomSubGroupWant', 'bj_randomSubGroupTotal',
      'bj_randomSubGroupChance', 'bj_destRandomConsidered', 'bj_destRandomCurrentPick', 'bj_elevatorWallBlocker',
      'bj_elevatorNeighbor', 'bj_itemRandomConsidered', 'bj_itemRandomCurrentPick', 'bj_forceRandomConsidered',
      'bj_forceRandomCurrentPick', 'bj_makeUnitRescuableUnit', 'bj_makeUnitRescuableFlag', 'bj_pauseAllUnitsFlag',
      'bj_enumDestructableCenter', 'bj_enumDestructableRadius', 'bj_setPlayerTargetColor',
      'bj_isUnitGroupDeadResult', 'bj_isUnitGroupEmptyResult', 'bj_isUnitGroupInRectResult',
      'bj_isUnitGroupInRectRect', 'bj_changeLevelShowScores', 'bj_changeLevelMapName', 'bj_suspendDecayFleshGroup',
      'bj_suspendDecayBoneGroup', 'bj_delayedSuspendDecayTimer', 'bj_delayedSuspendDecayTrig',
      'bj_livingPlayerUnitsTypeId', 'bj_lastDyingWidget', 'bj_randDistCount', 'bj_randDistID', 'bj_randDistChance',
      'bj_lastCreatedUnit', 'bj_lastCreatedItem', 'bj_lastRemovedItem', 'bj_lastHauntedGoldMine',
      'bj_lastCreatedDestructable', 'bj_lastCreatedGroup', 'bj_lastCreatedFogModifier', 'bj_lastCreatedEffect',
      'bj_lastCreatedWeatherEffect', 'bj_lastCreatedTerrainDeformation', 'bj_lastCreatedQuest',
      'bj_lastCreatedQuestItem', 'bj_lastCreatedDefeatCondition', 'bj_lastStartedTimer',
      'bj_lastCreatedTimerDialog', 'bj_lastCreatedLeaderboard', 'bj_lastCreatedMultiboard', 'bj_lastPlayedSound',
      'bj_lastPlayedMusic', 'bj_lastTransmissionDuration', 'bj_lastCreatedGameCache', 'bj_lastLoadedUnit',
      'bj_lastCreatedButton', 'bj_lastReplacedUnit', 'bj_lastCreatedTextTag', 'bj_lastCreatedLightning',
      'bj_lastCreatedImage', 'bj_lastCreatedUbersplat', 'bj_wantDestroyGroup', 'bj_RADTODEG', 'bj_queuedExecTotal',
      'bj_queuedExecTriggers', 'bj_queuedExecUseConds', 'bj_queuedExecTotal', 'bj_queuedExecTriggers',
      'bj_queuedExecUseConds', 'bj_queuedExecTotal', 'bj_queuedExecTotal', 'bj_queuedExecTotal',
      'bj_queuedExecTotal', 'bj_queuedExecTotal', 'bj_forLoopAIndex', 'bj_forLoopAIndex', 'bj_forLoopBIndex',
      'bj_forLoopBIndex', 'bj_mapInitialCameraBounds', 'bj_mapInitialPlayableArea', 'bj_destInRegionDiesCount',
      'bj_destInRegionDiesTrig', 'bj_destInRegionDiesCount', 'bj_lastCreatedWeatherEffect',
      'bj_lastCreatedWeatherEffect', 'bj_lastCreatedWeatherEffect', 'bj_lastCreatedTerrainDeformation',
      'bj_lastCreatedTerrainDeformation', 'bj_lastCreatedTerrainDeformation', 'bj_lastCreatedTerrainDeformation',
      'bj_lastCreatedTerrainDeformation', 'bj_lastCreatedTerrainDeformation', 'bj_lastCreatedTerrainDeformation',
      'bj_lastCreatedTerrainDeformation', 'bj_lastCreatedTerrainDeformation', 'bj_lastCreatedLightning',
      'bj_lastCreatedLightning', 'bj_lastCreatedLightning', 'bj_lastCreatedFogModifier',
      'bj_lastCreatedFogModifier', 'bj_lastCreatedFogModifier', 'bj_lastCreatedFogModifier',
      'bj_lastCreatedFogModifier', 'bj_lastCreatedFogModifier', 'bj_lastCreatedFogModifier',
      'bj_lastCreatedFogModifier', 'bj_lastCreatedFogModifier', 'bj_lastCreatedImage', 'bj_lastCreatedImage',
      'bj_lastCreatedImage', 'bj_lastCreatedUbersplat', 'bj_lastCreatedUbersplat', 'bj_lastCreatedUbersplat',
      'bj_lastPlayedSound', 'bj_lastPlayedMusic', 'bj_lastPlayedMusic', 'bj_NOTHING_SOUND_DURATION',
      'bj_lastPlayedSound', 'bj_lastPlayedMusic', 'bj_gameStarted', 'bj_gameStarted', 'bj_gameStarted',
      'bj_useDawnDuskSounds', 'bj_useDawnDuskSounds', 'bj_dayAmbientSound', 'bj_nightAmbientSound',
      'bj_lastCreatedEffect', 'bj_lastCreatedEffect', 'bj_lastCreatedEffect', 'bj_lastCreatedEffect',
      'bj_lastCreatedEffect', 'bj_lastCreatedItem', 'bj_lastCreatedItem', 'bj_lastRemovedItem',
      'bj_lastRemovedItem', 'bj_lastRemovedItem', 'bj_lastCreatedItem', 'bj_lastCreatedItem', 'bj_lastCreatedItem',
      'bj_lastRemovedItem', 'bj_itemRandomConsidered', 'bj_itemRandomCurrentPick', 'bj_itemRandomConsidered',
      'bj_itemRandomCurrentPick', 'bj_itemRandomCurrentPick', 'bj_lastCreatedUnit', 'bj_lastCreatedUnit',
      'bj_lastCreatedUnit', 'bj_lastCreatedUnit', 'bj_lastCreatedGroup', 'bj_groupLastCreatedDest',
      'bj_groupLastCreatedDest', 'bj_lastCreatedUnit', 'bj_lastCreatedUnit', 'bj_suspendDecayBoneGroup',
      'bj_suspendDecayFleshGroup', 'bj_delayedSuspendDecayTrig', 'bj_lastCreatedUnit', 'bj_lastCreatedUnit',
      'bj_isUnitGroupDeadResult', 'bj_wantDestroyGroup', 'bj_isUnitGroupDeadResult', 'bj_isUnitGroupDeadResult',
      'bj_isUnitGroupEmptyResult', 'bj_wantDestroyGroup', 'bj_isUnitGroupEmptyResult', 'bj_isUnitGroupEmptyResult',
      'bj_isUnitGroupInRectResult', 'bj_isUnitGroupInRectResult', 'bj_isUnitGroupInRectRect',
      'bj_isUnitGroupInRectResult', 'bj_pauseAllUnitsFlag', 'bj_lastReplacedUnit', 'bj_lastReplacedUnit',
      'bj_lastReplacedUnit', 'bj_lastCreatedDestructable', 'bj_lastCreatedDestructable',
      'bj_lastCreatedDestructable', 'bj_lastCreatedDestructable', 'bj_lastCreatedDestructable',
      'bj_destRandomConsidered', 'bj_destRandomCurrentPick', 'bj_destRandomConsidered', 'bj_destRandomCurrentPick',
      'bj_destRandomCurrentPick', 'bj_enumDestructableCenter', 'bj_enumDestructableRadius', 'bj_elevatorNeighbor',
      'bj_elevatorNeighbor', 'bj_elevatorNeighbor', 'bj_elevatorWallBlocker', 'bj_elevatorWallBlocker',
      'bj_wantDestroyGroup', 'bj_wantDestroyGroup', 'bj_groupAddGroupDest', 'bj_wantDestroyGroup',
      'bj_groupRemoveGroupDest', 'bj_groupRandomConsidered', 'bj_groupRandomCurrentPick', 'bj_wantDestroyGroup',
      'bj_groupRandomConsidered', 'bj_groupRandomCurrentPick', 'bj_groupRandomCurrentPick',
      'bj_forceRandomConsidered', 'bj_forceRandomCurrentPick', 'bj_forceRandomConsidered',
      'bj_forceRandomCurrentPick', 'bj_forceRandomCurrentPick', 'bj_groupEnumOwningPlayer', 'bj_groupEnumTypeId',
      'bj_groupEnumTypeId', 'bj_FORCE_ALL_PLAYERS', 'bj_groupCountUnits', 'bj_wantDestroyGroup',
      'bj_groupCountUnits', 'bj_groupCountUnits', 'bj_forceCountPlayers', 'bj_forceCountPlayers',
      'bj_forceCountPlayers', 'bj_randomSubGroupWant', 'bj_randomSubGroupTotal', 'bj_randomSubGroupGroup',
      'bj_randomSubGroupWant', 'bj_randomSubGroupTotal', 'bj_randomSubGroupChance', 'bj_livingPlayerUnitsTypeId',
      'bj_lastCreatedButton', 'bj_lastCreatedButton', 'bj_lastCreatedButton', 'bj_lastCreatedButton',
      'bj_lastCreatedButton', 'bj_isSinglePlayer', 'bj_isSinglePlayer', 'bj_isSinglePlayer', 'bj_isSinglePlayer',
      'bj_isSinglePlayer', 'bj_changeLevelShowScores', 'bj_isSinglePlayer', 'bj_isSinglePlayer',
      'bj_isSinglePlayer', 'bj_isSinglePlayer', 'bj_changeLevelMapName', 'bj_changeLevelMapName',
      'bj_lastCreatedQuest', 'bj_lastCreatedQuest', 'bj_lastCreatedQuest', 'bj_lastCreatedQuestItem',
      'bj_lastCreatedQuestItem', 'bj_lastCreatedQuestItem', 'bj_lastCreatedDefeatCondition',
      'bj_lastCreatedDefeatCondition', 'bj_lastCreatedDefeatCondition', 'bj_lastStartedTimer',
      'bj_lastStartedTimer', 'bj_lastStartedTimer', 'bj_lastStartedTimer', 'bj_lastStartedTimer',
      'bj_lastCreatedTimerDialog', 'bj_lastCreatedTimerDialog', 'bj_lastCreatedTimerDialog',
      'bj_lastCreatedLeaderboard', 'bj_lastCreatedLeaderboard', 'bj_lastCreatedLeaderboard',
      'bj_lastCreatedMultiboard', 'bj_lastCreatedMultiboard', 'bj_lastCreatedMultiboard', 'bj_lastCreatedTextTag',
      'bj_lastCreatedTextTag', 'bj_lastCreatedTextTag', 'bj_lastCreatedTextTag', 'bj_lastCreatedTextTag',
      'bj_cineSceneBeingSkipped', 'bj_cineSceneLastSound', 'bj_lastTransmissionDuration', 'bj_lastPlayedSound',
      'bj_lastTransmissionDuration', 'bj_lastPlayedSound', 'bj_lastTransmissionDuration', 'bj_cineModeAlreadyIn',
      'bj_cineModePriorSpeed', 'bj_cineModePriorFogSetting', 'bj_cineModePriorMaskSetting',
      'bj_cineModePriorDawnDusk', 'bj_cineModeSavedSeed', 'bj_cineModeAlreadyIn', 'bj_cineFadeFinishTimer',
      'bj_cineFadeFinishTimer', 'bj_cineFadeContinueTimer', 'bj_cineFadeContinueRed', 'bj_cineFadeContinueGreen',
      'bj_cineFadeContinueBlue', 'bj_cineFadeContinueTrans', 'bj_cineFadeContinueDuration',
      'bj_cineFadeContinueTex', 'bj_cineFadeContinueTimer', 'bj_rescueUnitBehavior', 'bj_rescueChangeColorUnit',
      'bj_rescueChangeColorBldg', 'bj_makeUnitRescuableUnit', 'bj_makeUnitRescuableFlag',
      'bj_lastCreatedGameCache', 'bj_lastCreatedGameCache', 'bj_lastCreatedGameCache', 'bj_lastLoadedUnit',
      'bj_lastLoadedUnit', 'bj_lastLoadedUnit', 'bj_lastHauntedGoldMine', 'bj_lastHauntedGoldMine',
      'bj_lastHauntedGoldMine', 'bj_setPlayerTargetColor', 'bj_lastDyingWidget', 'bj_meleeTwinkedHeroes',
      'bj_meleeTwinkedHeroes', 'bj_meleeGrantHeroItems', 'bj_meleeNearestMine', 'bj_meleeNearestMineDist',
      'bj_meleeNearestMine', 'bj_meleeNearestMineDist', 'bj_meleeNearestMineToLoc', 'bj_meleeNearestMine',
      'bj_meleeGrantHeroItems', 'bj_ghoul', 'bj_meleeVictoried', 'bj_meleeDefeated', 'bj_meleeDefeated',
      'bj_meleeGameOver', 'bj_meleeGameOver', 'bj_meleeDefeated', 'bj_playerIsExposed', 'bj_finishSoonAllExposed',
      'bj_playerIsCrippled', 'bj_playerIsCrippled', 'bj_finishSoonAllExposed', 'bj_finishSoonAllExposed',
      'bj_playerIsCrippled', 'bj_playerIsCrippled', 'bj_meleeGameOver', 'bj_meleeGameOver',
      'bj_finishSoonTimerDialog', 'bj_meleeDefeated', 'bj_meleeVictoried', 'bj_playerIsCrippled',
      'bj_playerIsExposed', 'bj_crippledTimer', 'bj_crippledTimerWindows', 'bj_meleeDefeated', 'bj_meleeVictoried',
      'bj_slotControlUsed', 'bj_slotControl', 'bj_slotControlReady', 'bj_slotControlUsed', 'bj_slotControl',
      'bj_useDawnDuskSounds', 'bj_useDawnDuskSounds', 'bj_dncIsDaytime', 'bj_dncIsDaytime', 'bj_dawnSound',
      'bj_duskSound', 'bj_dncSoundsDawn', 'bj_dncSoundsDusk', 'bj_dncSoundsDay', 'bj_dncSoundsNight',
      'bj_FORCE_PLAYER', 'bj_FORCE_ALL_PLAYERS', 'bj_cineModePriorSpeed', 'bj_cineModePriorFogSetting',
      'bj_cineModePriorMaskSetting', 'bj_queuedExecTriggers', 'bj_queuedExecUseConds', 'bj_isSinglePlayer',
      'bj_isSinglePlayer', 'bj_rescueSound', 'bj_questDiscoveredSound', 'bj_questUpdatedSound',
      'bj_questCompletedSound', 'bj_questFailedSound', 'bj_questHintSound', 'bj_questSecretSound',
      'bj_questItemAcquiredSound', 'bj_questWarningSound', 'bj_victoryDialogSound', 'bj_defeatDialogSound',
      'bj_MELEE_MAX_TWINKED_HEROES', 'bj_MELEE_MAX_TWINKED_HEROES', 'bj_queuedExecTimeout',
      'bj_mapInitialPlayableArea', 'bj_mapInitialCameraBounds', 'bj_stockAllowedPermanent',
      'bj_stockAllowedCharged', 'bj_stockAllowedArtifact', 'bj_stockPickedItemType', 'bj_stockPickedItemLevel',
      'bj_stockAllowedPermanent', 'bj_stockAllowedCharged', 'bj_stockAllowedArtifact', 'bj_stockUpdateTimer',
      'bj_stockItemPurchased', 'bj_gameStarted', 'bj_gameStartedTimer', 'bj_randDistCount', 'bj_randDistID',
      'bj_randDistChance', 'bj_randDistCount'
    ),
    9 => array( // jass_bjFunction
      'BJDebugMsg', 'RMinBJ', 'RMaxBJ', 'RAbsBJ', 'RSignBJ', 'IMinBJ', 'IMaxBJ', 'IAbsBJ', 'ISignBJ', 'SinBJ',
      'CosBJ', 'TanBJ', 'AsinBJ', 'AcosBJ', 'AtanBJ', 'Atan2BJ', 'AngleBetweenPoints', 'DistanceBetweenPoints',
      'PolarProjectionBJ', 'GetRandomDirectionDeg', 'GetRandomPercentageBJ', 'GetRandomLocInRect', 'ModuloInteger',
      'ModuloReal', 'OffsetLocation', 'OffsetRectBJ', 'RectFromCenterSizeBJ', 'RectContainsCoords',
      'RectContainsLoc', 'RectContainsUnit', 'RectContainsItem', 'ConditionalTriggerExecute', 'TriggerExecuteBJ',
      'PostTriggerExecuteBJ', 'QueuedTriggerCheck', 'QueuedTriggerGetIndex', 'QueuedTriggerRemoveByIndex',
      'QueuedTriggerAttemptExec', 'QueuedTriggerAddBJ', 'QueuedTriggerRemoveBJ', 'QueuedTriggerDoneBJ',
      'QueuedTriggerClearBJ', 'QueuedTriggerClearInactiveBJ', 'QueuedTriggerCountBJ', 'IsTriggerQueueEmptyBJ',
      'IsTriggerQueuedBJ', 'GetForLoopIndexA', 'SetForLoopIndexA', 'GetForLoopIndexB', 'SetForLoopIndexB',
      'PolledWait', 'IntegerTertiaryOp', 'DoNothing', 'CommentString', 'StringIdentity', 'GetBooleanAnd',
      'GetBooleanOr', 'PercentToInt', 'PercentTo255', 'GetTimeOfDay', 'SetTimeOfDay', 'SetTimeOfDayScalePercentBJ',
      'GetTimeOfDayScalePercentBJ', 'PlaySound', 'CompareLocationsBJ', 'CompareRectsBJ', 'GetRectFromCircleBJ',
      'GetCurrentCameraSetup', 'CameraSetupApplyForPlayer', 'CameraSetupGetFieldSwap', 'SetCameraFieldForPlayer',
      'SetCameraTargetControllerNoZForPlayer', 'SetCameraPositionForPlayer', 'SetCameraPositionLocForPlayer',
      'RotateCameraAroundLocBJ', 'PanCameraToForPlayer', 'PanCameraToLocForPlayer', 'PanCameraToTimedForPlayer',
      'PanCameraToTimedLocForPlayer', 'PanCameraToTimedLocWithZForPlayer', 'SmartCameraPanBJ',
      'SetCinematicCameraForPlayer', 'ResetToGameCameraForPlayer', 'CameraSetSourceNoiseForPlayer',
      'CameraSetTargetNoiseForPlayer', 'CameraSetEQNoiseForPlayer', 'CameraClearNoiseForPlayer',
      'GetCurrentCameraBoundsMapRectBJ', 'GetCameraBoundsMapRect', 'GetPlayableMapRect', 'GetEntireMapRect',
      'SetCameraBoundsToRect', 'SetCameraBoundsToRectForPlayerBJ', 'AdjustCameraBoundsBJ',
      'AdjustCameraBoundsForPlayerBJ', 'SetCameraQuickPositionForPlayer', 'SetCameraQuickPositionLocForPlayer',
      'SetCameraQuickPositionLoc', 'StopCameraForPlayerBJ', 'SetCameraOrientControllerForPlayerBJ',
      'CameraSetSmoothingFactorBJ', 'CameraResetSmoothingFactorBJ', 'DisplayTextToForce',
      'DisplayTimedTextToForce', 'ClearTextMessagesBJ', 'SubStringBJ', 'TriggerRegisterTimerEventPeriodic',
      'TriggerRegisterTimerEventSingle', 'TriggerRegisterTimerExpireEventBJ',
      'TriggerRegisterPlayerUnitEventSimple', 'TriggerRegisterAnyUnitEventBJ',
      'TriggerRegisterPlayerSelectionEventBJ', 'TriggerRegisterPlayerKeyEventBJ',
      'TriggerRegisterPlayerEventVictory', 'TriggerRegisterPlayerEventDefeat', 'TriggerRegisterPlayerEventLeave',
      'TriggerRegisterPlayerEventAllianceChanged', 'TriggerRegisterPlayerEventEndCinematic',
      'TriggerRegisterGameStateEventTimeOfDay', 'TriggerRegisterEnterRegionSimple',
      'TriggerRegisterLeaveRegionSimple', 'TriggerRegisterEnterRectSimple', 'TriggerRegisterLeaveRectSimple',
      'TriggerRegisterDistanceBetweenUnits', 'TriggerRegisterUnitInRangeSimple', 'TriggerRegisterUnitLifeEvent',
      'TriggerRegisterUnitManaEvent', 'TriggerRegisterDialogEventBJ', 'TriggerRegisterShowSkillEventBJ',
      'TriggerRegisterBuildSubmenuEventBJ', 'TriggerRegisterGameLoadedEventBJ', 'TriggerRegisterGameSavedEventBJ',
      'RegisterDestDeathInRegionEnum', 'TriggerRegisterDestDeathInRegionEvent', 'AddWeatherEffectSaveLast',
      'GetLastCreatedWeatherEffect', 'RemoveWeatherEffectBJ', 'TerrainDeformationCraterBJ',
      'TerrainDeformationRippleBJ', 'TerrainDeformationWaveBJ', 'TerrainDeformationRandomBJ',
      'TerrainDeformationStopBJ', 'GetLastCreatedTerrainDeformation', 'AddLightningLoc', 'DestroyLightningBJ',
      'MoveLightningLoc', 'GetLightningColorABJ', 'GetLightningColorRBJ', 'GetLightningColorGBJ',
      'GetLightningColorBBJ', 'SetLightningColorBJ', 'GetLastCreatedLightningBJ', 'GetAbilityEffectBJ',
      'GetAbilitySoundBJ', 'GetTerrainCliffLevelBJ', 'GetTerrainTypeBJ', 'GetTerrainVarianceBJ',
      'SetTerrainTypeBJ', 'IsTerrainPathableBJ', 'SetTerrainPathableBJ', 'SetWaterBaseColorBJ',
      'CreateFogModifierRectSimple', 'CreateFogModifierRadiusLocSimple', 'CreateFogModifierRectBJ',
      'CreateFogModifierRadiusLocBJ', 'GetLastCreatedFogModifier', 'FogEnableOn', 'FogEnableOff',
      'FogMaskEnableOn', 'FogMaskEnableOff', 'UseTimeOfDayBJ', 'SetTerrainFogExBJ', 'ResetTerrainFogBJ',
      'SetDoodadAnimationBJ', 'SetDoodadAnimationRectBJ', 'AddUnitAnimationPropertiesBJ', 'CreateImageBJ',
      'ShowImageBJ', 'SetImagePositionBJ', 'SetImageColorBJ', 'GetLastCreatedImage', 'CreateUbersplatBJ',
      'ShowUbersplatBJ', 'GetLastCreatedUbersplat', 'PlaySoundBJ', 'StopSoundBJ', 'SetSoundVolumeBJ',
      'SetSoundOffsetBJ', 'SetSoundDistanceCutoffBJ', 'SetSoundPitchBJ', 'SetSoundPositionLocBJ',
      'AttachSoundToUnitBJ', 'SetSoundConeAnglesBJ', 'KillSoundWhenDoneBJ', 'PlaySoundAtPointBJ',
      'PlaySoundOnUnitBJ', 'PlaySoundFromOffsetBJ', 'PlayMusicBJ', 'PlayMusicExBJ', 'SetMusicOffsetBJ',
      'PlayThematicMusicBJ', 'PlayThematicMusicExBJ', 'SetThematicMusicOffsetBJ', 'EndThematicMusicBJ',
      'StopMusicBJ', 'ResumeMusicBJ', 'SetMusicVolumeBJ', 'GetSoundDurationBJ', 'GetSoundFileDurationBJ',
      'GetLastPlayedSound', 'GetLastPlayedMusic', 'VolumeGroupSetVolumeBJ', 'SetCineModeVolumeGroupsImmediateBJ',
      'SetCineModeVolumeGroupsBJ', 'SetSpeechVolumeGroupsImmediateBJ', 'SetSpeechVolumeGroupsBJ',
      'VolumeGroupResetImmediateBJ', 'VolumeGroupResetBJ', 'GetSoundIsPlayingBJ', 'WaitForSoundBJ',
      'SetMapMusicIndexedBJ', 'SetMapMusicRandomBJ', 'ClearMapMusicBJ', 'SetStackedSoundBJ',
      'StartSoundForPlayerBJ', 'VolumeGroupSetVolumeForPlayerBJ', 'EnableDawnDusk', 'IsDawnDuskEnabled',
      'SetAmbientDaySound', 'SetAmbientNightSound', 'AddSpecialEffectLocBJ', 'AddSpecialEffectTargetUnitBJ',
      'DestroyEffectBJ', 'GetLastCreatedEffectBJ', 'GetItemLoc', 'GetItemLifeBJ', 'SetItemLifeBJ',
      'AddHeroXPSwapped', 'SetHeroLevelBJ', 'DecUnitAbilityLevelSwapped', 'IncUnitAbilityLevelSwapped',
      'SetUnitAbilityLevelSwapped', 'GetUnitAbilityLevelSwapped', 'UnitHasBuffBJ', 'UnitRemoveBuffBJ',
      'UnitAddItemSwapped', 'UnitAddItemByIdSwapped', 'UnitRemoveItemSwapped', 'UnitRemoveItemFromSlotSwapped',
      'CreateItemLoc', 'GetLastCreatedItem', 'GetLastRemovedItem', 'SetItemPositionLoc', 'GetLearnedSkillBJ',
      'SuspendHeroXPBJ', 'SetPlayerHandicapXPBJ', 'GetPlayerHandicapXPBJ', 'SetPlayerHandicapBJ',
      'GetPlayerHandicapBJ', 'GetHeroStatBJ', 'SetHeroStat', 'ModifyHeroStat', 'ModifyHeroSkillPoints',
      'UnitDropItemPointBJ', 'UnitDropItemPointLoc', 'UnitDropItemSlotBJ', 'UnitDropItemTargetBJ',
      'UnitUseItemDestructable', 'UnitUseItemPointLoc', 'UnitItemInSlotBJ', 'GetInventoryIndexOfItemTypeBJ',
      'GetItemOfTypeFromUnitBJ', 'UnitHasItemOfTypeBJ', 'UnitInventoryCount', 'UnitInventorySizeBJ',
      'SetItemInvulnerableBJ', 'SetItemDropOnDeathBJ', 'SetItemDroppableBJ', 'SetItemPlayerBJ', 'SetItemVisibleBJ',
      'IsItemHiddenBJ', 'ChooseRandomItemBJ', 'ChooseRandomItemExBJ', 'ChooseRandomNPBuildingBJ',
      'ChooseRandomCreepBJ', 'EnumItemsInRectBJ', 'RandomItemInRectBJEnum', 'RandomItemInRectBJ',
      'RandomItemInRectSimpleBJ', 'CheckItemStatus', 'CheckItemcodeStatus', 'UnitId2OrderIdBJ', 'String2UnitIdBJ',
      'UnitId2StringBJ', 'String2OrderIdBJ', 'OrderId2StringBJ', 'GetIssuedOrderIdBJ', 'GetKillingUnitBJ',
      'CreateUnitAtLocSaveLast', 'GetLastCreatedUnit', 'CreateNUnitsAtLoc', 'CreateNUnitsAtLocFacingLocBJ',
      'GetLastCreatedGroupEnum', 'GetLastCreatedGroup', 'CreateCorpseLocBJ', 'UnitSuspendDecayBJ',
      'DelayedSuspendDecayStopAnimEnum', 'DelayedSuspendDecayBoneEnum', 'DelayedSuspendDecayFleshEnum',
      'DelayedSuspendDecay', 'DelayedSuspendDecayCreate', 'CreatePermanentCorpseLocBJ', 'GetUnitStateSwap',
      'GetUnitStatePercent', 'GetUnitLifePercent', 'GetUnitManaPercent', 'SelectUnitSingle', 'SelectGroupBJEnum',
      'SelectGroupBJ', 'SelectUnitAdd', 'SelectUnitRemove', 'ClearSelectionForPlayer', 'SelectUnitForPlayerSingle',
      'SelectGroupForPlayerBJ', 'SelectUnitAddForPlayer', 'SelectUnitRemoveForPlayer', 'SetUnitLifeBJ',
      'SetUnitManaBJ', 'SetUnitLifePercentBJ', 'SetUnitManaPercentBJ', 'IsUnitDeadBJ', 'IsUnitAliveBJ',
      'IsUnitGroupDeadBJEnum', 'IsUnitGroupDeadBJ', 'IsUnitGroupEmptyBJEnum', 'IsUnitGroupEmptyBJ',
      'IsUnitGroupInRectBJEnum', 'IsUnitGroupInRectBJ', 'IsUnitHiddenBJ', 'ShowUnitHide', 'ShowUnitShow',
      'IssueHauntOrderAtLocBJFilter', 'IssueHauntOrderAtLocBJ', 'IssueBuildOrderByIdLocBJ',
      'IssueTrainOrderByIdBJ', 'GroupTrainOrderByIdBJ', 'IssueUpgradeOrderByIdBJ', 'GetAttackedUnitBJ',
      'SetUnitFlyHeightBJ', 'SetUnitTurnSpeedBJ', 'SetUnitPropWindowBJ', 'GetUnitPropWindowBJ',
      'GetUnitDefaultPropWindowBJ', 'SetUnitBlendTimeBJ', 'SetUnitAcquireRangeBJ', 'UnitSetCanSleepBJ',
      'UnitCanSleepBJ', 'UnitWakeUpBJ', 'UnitIsSleepingBJ', 'WakePlayerUnitsEnum', 'WakePlayerUnits',
      'EnableCreepSleepBJ', 'UnitGenerateAlarms', 'DoesUnitGenerateAlarms', 'PauseAllUnitsBJEnum',
      'PauseAllUnitsBJ', 'PauseUnitBJ', 'IsUnitPausedBJ', 'UnitPauseTimedLifeBJ', 'UnitApplyTimedLifeBJ',
      'UnitShareVisionBJ', 'UnitRemoveBuffsBJ', 'UnitRemoveBuffsExBJ', 'UnitCountBuffsExBJ', 'UnitRemoveAbilityBJ',
      'UnitAddAbilityBJ', 'UnitRemoveTypeBJ', 'UnitAddTypeBJ', 'UnitMakeAbilityPermanentBJ', 'SetUnitExplodedBJ',
      'ExplodeUnitBJ', 'GetTransportUnitBJ', 'GetLoadedUnitBJ', 'IsUnitInTransportBJ', 'IsUnitLoadedBJ',
      'IsUnitIllusionBJ', 'ReplaceUnitBJ', 'GetLastReplacedUnitBJ', 'SetUnitPositionLocFacingBJ',
      'SetUnitPositionLocFacingLocBJ', 'AddItemToStockBJ', 'AddUnitToStockBJ', 'RemoveItemFromStockBJ',
      'RemoveUnitFromStockBJ', 'SetUnitUseFoodBJ', 'UnitDamagePointLoc', 'UnitDamageTargetBJ',
      'CreateDestructableLoc', 'CreateDeadDestructableLocBJ', 'GetLastCreatedDestructable', 'ShowDestructableBJ',
      'SetDestructableInvulnerableBJ', 'IsDestructableInvulnerableBJ', 'GetDestructableLoc',
      'EnumDestructablesInRectAll', 'EnumDestructablesInCircleBJFilter', 'IsDestructableDeadBJ',
      'IsDestructableAliveBJ', 'RandomDestructableInRectBJEnum', 'RandomDestructableInRectBJ',
      'RandomDestructableInRectSimpleBJ', 'EnumDestructablesInCircleBJ', 'SetDestructableLifePercentBJ',
      'SetDestructableMaxLifeBJ', 'ModifyGateBJ', 'GetElevatorHeight', 'ChangeElevatorHeight',
      'NudgeUnitsInRectEnum', 'NudgeItemsInRectEnum', 'NudgeObjectsInRect', 'NearbyElevatorExistsEnum',
      'NearbyElevatorExists', 'FindElevatorWallBlockerEnum', 'ChangeElevatorWallBlocker', 'ChangeElevatorWalls',
      'WaygateActivateBJ', 'WaygateIsActiveBJ', 'WaygateSetDestinationLocBJ', 'WaygateGetDestinationLocBJ',
      'UnitSetUsesAltIconBJ', 'ForceUIKeyBJ', 'ForceUICancelBJ', 'ForGroupBJ', 'GroupAddUnitSimple',
      'GroupRemoveUnitSimple', 'GroupAddGroupEnum', 'GroupAddGroup', 'GroupRemoveGroupEnum', 'GroupRemoveGroup',
      'ForceAddPlayerSimple', 'ForceRemovePlayerSimple', 'GroupPickRandomUnitEnum', 'GroupPickRandomUnit',
      'ForcePickRandomPlayerEnum', 'ForcePickRandomPlayer', 'EnumUnitsSelected', 'GetUnitsInRectMatching',
      'GetUnitsInRectAll', 'GetUnitsInRectOfPlayerFilter', 'GetUnitsInRectOfPlayer',
      'GetUnitsInRangeOfLocMatching', 'GetUnitsInRangeOfLocAll', 'GetUnitsOfTypeIdAllFilter',
      'GetUnitsOfTypeIdAll', 'GetUnitsOfPlayerMatching', 'GetUnitsOfPlayerAll', 'GetUnitsOfPlayerAndTypeIdFilter',
      'GetUnitsOfPlayerAndTypeId', 'GetUnitsSelectedAll', 'GetForceOfPlayer', 'GetPlayersAll',
      'GetPlayersByMapControl', 'GetPlayersAllies', 'GetPlayersEnemies', 'GetPlayersMatching',
      'CountUnitsInGroupEnum', 'CountUnitsInGroup', 'CountPlayersInForceEnum', 'CountPlayersInForceBJ',
      'GetRandomSubGroupEnum', 'GetRandomSubGroup', 'LivingPlayerUnitsOfTypeIdFilter',
      'CountLivingPlayerUnitsOfTypeId', 'ResetUnitAnimation', 'SetUnitTimeScalePercent', 'SetUnitScalePercent',
      'SetUnitVertexColorBJ', 'UnitAddIndicatorBJ', 'DestructableAddIndicatorBJ', 'ItemAddIndicatorBJ',
      'SetUnitFacingToFaceLocTimed', 'SetUnitFacingToFaceUnitTimed', 'QueueUnitAnimationBJ',
      'SetDestructableAnimationBJ', 'QueueDestructableAnimationBJ', 'SetDestAnimationSpeedPercent',
      'DialogDisplayBJ', 'DialogSetMessageBJ', 'DialogAddButtonBJ', 'DialogAddButtonWithHotkeyBJ', 'DialogClearBJ',
      'GetLastCreatedButtonBJ', 'GetClickedButtonBJ', 'GetClickedDialogBJ', 'SetPlayerAllianceBJ',
      'SetPlayerAllianceStateAllyBJ', 'SetPlayerAllianceStateVisionBJ', 'SetPlayerAllianceStateControlBJ',
      'SetPlayerAllianceStateFullControlBJ', 'SetPlayerAllianceStateBJ', 'SetForceAllianceStateBJ',
      'PlayersAreCoAllied', 'ShareEverythingWithTeamAI', 'ShareEverythingWithTeam', 'ConfigureNeutralVictim',
      'MakeUnitsPassiveForPlayerEnum', 'MakeUnitsPassiveForPlayer', 'MakeUnitsPassiveForTeam',
      'AllowVictoryDefeat', 'EndGameBJ', 'MeleeVictoryDialogBJ', 'MeleeDefeatDialogBJ', 'GameOverDialogBJ',
      'RemovePlayerPreserveUnitsBJ', 'CustomVictoryOkBJ', 'CustomVictoryQuitBJ', 'CustomVictoryDialogBJ',
      'CustomVictorySkipBJ', 'CustomVictoryBJ', 'CustomDefeatRestartBJ', 'CustomDefeatReduceDifficultyBJ',
      'CustomDefeatLoadBJ', 'CustomDefeatQuitBJ', 'CustomDefeatDialogBJ', 'CustomDefeatBJ', 'SetNextLevelBJ',
      'SetPlayerOnScoreScreenBJ', 'CreateQuestBJ', 'DestroyQuestBJ', 'QuestSetEnabledBJ', 'QuestSetTitleBJ',
      'QuestSetDescriptionBJ', 'QuestSetCompletedBJ', 'QuestSetFailedBJ', 'QuestSetDiscoveredBJ',
      'GetLastCreatedQuestBJ', 'CreateQuestItemBJ', 'QuestItemSetDescriptionBJ', 'QuestItemSetCompletedBJ',
      'GetLastCreatedQuestItemBJ', 'CreateDefeatConditionBJ', 'DestroyDefeatConditionBJ',
      'DefeatConditionSetDescriptionBJ', 'GetLastCreatedDefeatConditionBJ', 'FlashQuestDialogButtonBJ',
      'QuestMessageBJ', 'StartTimerBJ', 'CreateTimerBJ', 'DestroyTimerBJ', 'PauseTimerBJ', 'GetLastCreatedTimerBJ',
      'CreateTimerDialogBJ', 'DestroyTimerDialogBJ', 'TimerDialogSetTitleBJ', 'TimerDialogSetTitleColorBJ',
      'TimerDialogSetTimeColorBJ', 'TimerDialogSetSpeedBJ', 'TimerDialogDisplayForPlayerBJ',
      'TimerDialogDisplayBJ', 'GetLastCreatedTimerDialogBJ', 'LeaderboardResizeBJ',
      'LeaderboardSetPlayerItemValueBJ', 'LeaderboardSetPlayerItemLabelBJ', 'LeaderboardSetPlayerItemStyleBJ',
      'LeaderboardSetPlayerItemLabelColorBJ', 'LeaderboardSetPlayerItemValueColorBJ', 'LeaderboardSetLabelColorBJ',
      'LeaderboardSetValueColorBJ', 'LeaderboardSetLabelBJ', 'LeaderboardSetStyleBJ', 'LeaderboardGetItemCountBJ',
      'LeaderboardHasPlayerItemBJ', 'ForceSetLeaderboardBJ', 'CreateLeaderboardBJ', 'DestroyLeaderboardBJ',
      'LeaderboardDisplayBJ', 'LeaderboardAddItemBJ', 'LeaderboardRemovePlayerItemBJ', 'LeaderboardSortItemsBJ',
      'LeaderboardSortItemsByPlayerBJ', 'LeaderboardSortItemsByLabelBJ', 'LeaderboardGetPlayerIndexBJ',
      'LeaderboardGetIndexedPlayerBJ', 'PlayerGetLeaderboardBJ', 'GetLastCreatedLeaderboard', 'CreateMultiboardBJ',
      'DestroyMultiboardBJ', 'GetLastCreatedMultiboard', 'MultiboardDisplayBJ', 'MultiboardMinimizeBJ',
      'MultiboardSetTitleTextColorBJ', 'MultiboardAllowDisplayBJ', 'MultiboardSetItemStyleBJ',
      'MultiboardSetItemValueBJ', 'MultiboardSetItemColorBJ', 'MultiboardSetItemWidthBJ',
      'MultiboardSetItemIconBJ', 'TextTagSize2Height', 'TextTagSpeed2Velocity', 'SetTextTagColorBJ',
      'SetTextTagVelocityBJ', 'SetTextTagTextBJ', 'SetTextTagPosBJ', 'SetTextTagPosUnitBJ',
      'SetTextTagSuspendedBJ', 'SetTextTagPermanentBJ', 'SetTextTagAgeBJ', 'SetTextTagLifespanBJ',
      'SetTextTagFadepointBJ', 'CreateTextTagLocBJ', 'CreateTextTagUnitBJ', 'DestroyTextTagBJ',
      'ShowTextTagForceBJ', 'GetLastCreatedTextTag', 'PauseGameOn', 'PauseGameOff', 'SetUserControlForceOn',
      'SetUserControlForceOff', 'ShowInterfaceForceOn', 'ShowInterfaceForceOff', 'PingMinimapForForce',
      'PingMinimapLocForForce', 'PingMinimapForPlayer', 'PingMinimapLocForPlayer', 'PingMinimapForForceEx',
      'PingMinimapLocForForceEx', 'EnableWorldFogBoundaryBJ', 'EnableOcclusionBJ', 'CancelCineSceneBJ',
      'TryInitCinematicBehaviorBJ', 'SetCinematicSceneBJ', 'GetTransmissionDuration', 'WaitTransmissionDuration',
      'DoTransmissionBasicsXYBJ', 'TransmissionFromUnitWithNameBJ', 'TransmissionFromUnitTypeWithNameBJ',
      'GetLastTransmissionDurationBJ', 'ForceCinematicSubtitlesBJ', 'CinematicModeExBJ', 'CinematicModeBJ',
      'DisplayCineFilterBJ', 'CinematicFadeCommonBJ', 'FinishCinematicFadeBJ', 'FinishCinematicFadeAfterBJ',
      'ContinueCinematicFadeBJ', 'ContinueCinematicFadeAfterBJ', 'AbortCinematicFadeBJ', 'CinematicFadeBJ',
      'CinematicFilterGenericBJ', 'RescueUnitBJ', 'TriggerActionUnitRescuedBJ', 'TryInitRescuableTriggersBJ',
      'SetRescueUnitColorChangeBJ', 'SetRescueBuildingColorChangeBJ', 'MakeUnitRescuableToForceBJEnum',
      'MakeUnitRescuableToForceBJ', 'InitRescuableBehaviorBJ', 'SetPlayerTechResearchedSwap',
      'SetPlayerTechMaxAllowedSwap', 'SetPlayerMaxHeroesAllowed', 'GetPlayerTechCountSimple',
      'GetPlayerTechMaxAllowedSwap', 'SetPlayerAbilityAvailableBJ', 'SetCampaignMenuRaceBJ',
      'SetMissionAvailableBJ', 'SetCampaignAvailableBJ', 'SetCinematicAvailableBJ', 'InitGameCacheBJ',
      'SaveGameCacheBJ', 'GetLastCreatedGameCacheBJ', 'StoreRealBJ', 'StoreIntegerBJ', 'StoreBooleanBJ',
      'StoreStringBJ', 'StoreUnitBJ', 'GetStoredRealBJ', 'GetStoredIntegerBJ', 'GetStoredBooleanBJ',
      'GetStoredStringBJ', 'RestoreUnitLocFacingAngleBJ', 'RestoreUnitLocFacingPointBJ', 'GetLastRestoredUnitBJ',
      'FlushGameCacheBJ', 'FlushStoredMissionBJ', 'HaveStoredValue', 'ShowCustomCampaignButton',
      'IsCustomCampaignButtonVisibile', 'LoadGameBJ', 'SaveAndChangeLevelBJ', 'SaveAndLoadGameBJ',
      'RenameSaveDirectoryBJ', 'RemoveSaveDirectoryBJ', 'CopySaveGameBJ', 'GetPlayerStartLocationX',
      'GetPlayerStartLocationY', 'GetPlayerStartLocationLoc', 'GetRectCenter', 'IsPlayerSlotState',
      'GetFadeFromSeconds', 'AdjustPlayerStateSimpleBJ', 'AdjustPlayerStateBJ', 'SetPlayerStateBJ',
      'SetPlayerFlagBJ', 'SetPlayerTaxRateBJ', 'GetPlayerTaxRateBJ', 'IsPlayerFlagSetBJ', 'AddResourceAmountBJ',
      'GetConvertedPlayerId', 'ConvertedPlayer', 'GetRectWidthBJ', 'GetRectHeightBJ', 'BlightGoldMineForPlayerBJ',
      'BlightGoldMineForPlayer', 'GetLastHauntedGoldMine', 'IsPointBlightedBJ', 'SetPlayerColorBJEnum',
      'SetPlayerColorBJ', 'SetPlayerUnitAvailableBJ', 'LockGameSpeedBJ', 'UnlockGameSpeedBJ', 'IssueTargetOrderBJ',
      'IssuePointOrderLocBJ', 'IssueTargetDestructableOrder', 'IssueTargetItemOrder', 'IssueImmediateOrderBJ',
      'GroupTargetOrderBJ', 'GroupPointOrderLocBJ', 'GroupImmediateOrderBJ', 'GroupTargetDestructableOrder',
      'GroupTargetItemOrder', 'GetDyingDestructable', 'SetUnitRallyPoint', 'SetUnitRallyUnit',
      'SetUnitRallyDestructable', 'SaveDyingWidget', 'SetBlightRectBJ', 'SetBlightRadiusLocBJ', 'GetAbilityName',
      'MeleeStartingVisibility', 'MeleeStartingResources', 'ReducePlayerTechMaxAllowed', 'MeleeStartingHeroLimit',
      'MeleeTrainedUnitIsHeroBJFilter', 'MeleeGrantItemsToHero', 'MeleeGrantItemsToTrainedHero',
      'MeleeGrantItemsToHiredHero', 'MeleeGrantHeroItems', 'MeleeClearExcessUnit', 'MeleeClearNearbyUnits',
      'MeleeClearExcessUnits', 'MeleeEnumFindNearestMine', 'MeleeFindNearestMine', 'MeleeRandomHeroLoc',
      'MeleeGetProjectedLoc', 'MeleeGetNearestValueWithin', 'MeleeGetLocWithinRect', 'MeleeStartingUnitsHuman',
      'MeleeStartingUnitsOrc', 'MeleeStartingUnitsUndead', 'MeleeStartingUnitsNightElf',
      'MeleeStartingUnitsUnknownRace', 'MeleeStartingUnits', 'MeleeStartingUnitsForPlayer', 'PickMeleeAI',
      'MeleeStartingAI', 'LockGuardPosition', 'MeleePlayerIsOpponent', 'MeleeGetAllyStructureCount',
      'MeleeGetAllyCount', 'MeleeGetAllyKeyStructureCount', 'MeleeDoDrawEnum', 'MeleeDoVictoryEnum',
      'MeleeDoDefeat', 'MeleeDoDefeatEnum', 'MeleeDoLeave', 'MeleeRemoveObservers', 'MeleeCheckForVictors',
      'MeleeCheckForLosersAndVictors', 'MeleeGetCrippledWarningMessage', 'MeleeGetCrippledTimerMessage',
      'MeleeGetCrippledRevealedMessage', 'MeleeExposePlayer', 'MeleeExposeAllPlayers',
      'MeleeCrippledPlayerTimeout', 'MeleePlayerIsCrippled', 'MeleeCheckForCrippledPlayers', 'MeleeCheckLostUnit',
      'MeleeCheckAddedUnit', 'MeleeTriggerActionConstructCancel', 'MeleeTriggerActionUnitDeath',
      'MeleeTriggerActionUnitConstructionStart', 'MeleeTriggerActionPlayerDefeated',
      'MeleeTriggerActionPlayerLeft', 'MeleeTriggerActionAllianceChange', 'MeleeTriggerTournamentFinishSoon',
      'MeleeWasUserPlayer', 'MeleeTournamentFinishNowRuleA', 'MeleeTriggerTournamentFinishNow',
      'MeleeInitVictoryDefeat', 'CheckInitPlayerSlotAvailability', 'SetPlayerSlotAvailable', 'TeamInitPlayerSlots',
      'MeleeInitPlayerSlots', 'FFAInitPlayerSlots', 'OneOnOneInitPlayerSlots', 'InitGenericPlayerSlots',
      'SetDNCSoundsDawn', 'SetDNCSoundsDusk', 'SetDNCSoundsDay', 'SetDNCSoundsNight', 'InitDNCSounds',
      'InitBlizzardGlobals', 'InitQueuedTriggers', 'InitMapRects', 'InitSummonableCaps', 'UpdateStockAvailability',
      'UpdateEachStockBuildingEnum', 'UpdateEachStockBuilding', 'PerformStockUpdates', 'StartStockUpdates',
      'RemovePurchasedItem', 'InitNeutralBuildings', 'MarkGameStarted', 'DetectGameStarted', 'InitBlizzard',
      'RandomDistReset', 'RandomDistAddItem', 'RandomDistChoose', 'UnitDropItem', 'WidgetDropItem'
    )
  ),
  'SYMBOLS' => array( // , ( ) [ ] . / * + - = " ' 
    '+', '-', '*', '/', 
    '==', '~=', '<=', '>=', '<', '>', '=',
    '(', ')', '[', ']',
    ',', '.'
    ),
  'CASE_SENSITIVE' => array(
    GESHI_COMMENTS => false,
    1 => true,
    2 => true,
    3 => true,
    4 => true,
    5 => true,
    6 => true,
    7 => true,
    8 => true,
    9 => true,
    ),
  'STYLES' => array(
    'KEYWORDS' => array(
      1 => 'color: #000000; font-weight: bold',
      2 => 'color: #4477aa; font-weight: bold',
      3 => 'color: #4477aa; font-weight: bold',
      4 => 'color: purple',
      5 => 'color: #4477AA; font-weight: bold',
      6 => 'color: purple',
      7 => 'color: #990000',
      8 => 'color: #4477AA',
      9 => 'color: #FF0000',
      ),
    'COMMENTS' => array(
      1 => 'color: #993300;',
      2 => 'color: #009933;',
      'MULTI' => 'color: #009933;'
      ),
    'ESCAPE_CHAR' => array(
      0 => '',
      1 => '',
      2 => ''
      ),
    'BRACKETS' => array(
      0 => 'color: sienna;'
      ),
    'STRINGS' => array(
      0 => 'color: blue;'
      ),
    'NUMBERS' => array(
      0 => 'color: #3333FF;'
      ),
    'METHODS' => array(
      1 => 'color: #aa9900;'
      ),
    'SYMBOLS' => array(
      0 => 'color: sienna;'
      ),
    'REGEXPS' => array(
      ),
    'SCRIPT' => array(
      )
    ),
  'URLS' => array(
    1 => '',
    2 => '',
    3 => '',
    4 => '',
    5 => ''
    ),
  'OOLANG' => true,
  'OBJECT_SPLITTERS' => array(
    1 => '.',
    ),
  'REGEXPS' => array(
    ),
  'STRICT_MODE_APPLIES' => GESHI_NEVER,
  'SCRIPT_DELIMITERS' => array(
    ),
  'HIGHLIGHT_STRICT_BLOCK' => array(
    )
);

?>